const fs = require('fs'); 
let data = fs.readFileSync('public/units/australia/data.js', 'utf8'); 

const oldAss2Start = `"theme_heading": "Assessment 2: 'How Useful' Source Analysis",`;
const oldAss2Block = `        {
          "type": "narrative",
          "theme_heading": "Assessment 2: 'How Useful' Source Analysis",
          "text": "<p>Study Sources A and B below. Then answer the question: <strong>How useful are Sources A and B for an enquiry into the impact of British colonization on Aboriginal Australians?</strong></p>\\n\\n<div style='display:flex; gap: 20px; flex-wrap: wrap;'>\\n<div style='flex:1; min-width:300px; background:#f0fdf4; padding:15px; border-left:4px solid #16a34a; margin-bottom:15px;'>\\n<strong>Source A: Extract from a letter written by a British squatter in New South Wales, published in a London newspaper in 1840.</strong><br/><br/>\\"The land here is vast and entirely unimproved by the native people, who simply wander across it. We have brought civilization, built permanent farms, and our flocks of sheep are multiplying rapidly. We are turning a wasteland into a highly profitable jewel of the Empire. The natives are melting away, which is the natural outcome when a superior race arrives.\\"<br/><br/><em>Provenance Clue: Written by a wealthy squatter trying to encourage more British investment, in an era where racism was common.</em>\\n</div>\\n\\n<div style='flex:1; min-width:300px; background:#f0fdf4; padding:15px; border-left:4px solid #16a34a; margin-bottom:15px;'>\\n<strong>Source B: Extract from a report by Lancelot Threlkeld, a Christian missionary living among the Awabakal people, written in 1838.</strong><br/><br/>\\"It is a tragedy to witness the complete destruction of these people. The white settlers have stolen their hunting grounds. When the starving natives steal a single sheep to survive, they are hunted down and shot like dogs by the squatters. The British government has done nothing to protect them from this slaughter.\\"<br/><br/><em>Provenance Clue: Written by a missionary whose job was to protect Aboriginal people, meaning he sympathised with them and saw the brutality of the squatters firsthand.</em>\\n</div>\\n</div>\\n\\n<div style='margin-top:20px; padding: 15px; background-color: #fffbeb; border-left: 4px solid #fbbf24;'>\\n<h4>Scaffolding: How to analyze these sources</h4>\\n<p>For <strong>both</strong> sources, make sure you address:</p>\\n<ul>\\n<li><strong>Content:</strong> What does the source actually say? What details are useful?</li>\\n<li><strong>Context:</strong> What do you know about this from your lessons that supports or challenges the source?</li>\\n<li><strong>Provenance (NOP):</strong> Who wrote it, when, and why? How does that affect its reliability and usefulness?</li>\\n</ul>\\n</div>",
          "tasks": []
        }`;

const newAss2Block = `        {
          "type": "narrative",
          "theme_heading": "Assessment 2: 'How Useful' Source Analysis",
          "text": "<p>Study Sources A and B below. Then answer the question: <strong>How useful are Sources A and B for an enquiry into the impact of British colonization on Aboriginal Australians?</strong></p>\\n\\n<div style='display:flex; gap: 20px; flex-wrap: wrap;'>\\n<div style='flex:1; min-width:300px; background:#f0fdf4; padding:15px; border-left:4px solid #16a34a; margin-bottom:15px;'>\\n<strong>Source A: Extract from a letter written by a British squatter in New South Wales, published in a London newspaper in 1840.</strong><br/><br/>\\"The land here is vast and entirely unimproved by the native people, who simply wander across it. We have brought civilization, built permanent farms, and our flocks of sheep are multiplying rapidly. We are turning a wasteland into a highly profitable jewel of the Empire. The natives are melting away, which is the natural outcome when a superior race arrives.\\"<br/><br/><em>Provenance Clue: Written by a wealthy squatter trying to encourage more British investment, in an era where racism was common.</em>\\n</div>\\n\\n<div style='flex:1; min-width:300px; background:#f0fdf4; padding:15px; border-left:4px solid #16a34a; margin-bottom:15px;'>\\n<strong>Source B: Extract from a report by Lancelot Threlkeld, a Christian missionary living among the Awabakal people, written in 1838.</strong><br/><br/>\\"It is a tragedy to witness the complete destruction of these people. The white settlers have stolen their hunting grounds. When the starving natives steal a single sheep to survive, they are hunted down and shot like dogs by the squatters. The British government has done nothing to protect them from this slaughter.\\"<br/><br/><em>Provenance Clue: Written by a missionary whose job was to protect Aboriginal people, meaning he sympathised with them and saw the brutality of the squatters firsthand.</em>\\n</div>\\n</div>",
          "tasks": [
            {
              "type": "extended_writing",
              "question": "How useful are Sources A and B for an enquiry into the impact of British colonization on Aboriginal Australians? (8 marks)"
            }
          ]
        }`;

data = data.replace(oldAss2Block, newAss2Block);
fs.writeFileSync('public/units/australia/data.js', data); 
console.log(data.includes("How useful are Sources A and B for an enquiry into the impact of British colonization on Aboriginal Australians? (8 marks)"));
