const fs = require('fs');

const lesson5Quiz = [
  {
    "question": "What were the three main stages of the Triangular Trade?",
    "options": ["Europe to Africa, Africa to the Americas, the Americas to Europe.", "Europe to Asia, Asia to Africa, Africa to Europe.", "The Americas to Europe, Europe to Asia, Asia to the Americas.", "Africa to the Americas, the Americas to Asia, Asia to Africa."],
    "answer": 0,
    "explanation": "The Triangular Trade connected Europe, Africa, and the Americas in a continuous cycle of exploitation and profit."
  },
  {
    "question": "Which of the following was NOT a typical good traded by Europeans in West Africa?",
    "options": ["Sugar", "Guns", "Alcohol", "Textiles"],
    "answer": 0,
    "explanation": "Sugar was produced in the Americas. Europeans traded manufactured goods like guns, alcohol, and textiles in West Africa."
  },
  {
    "question": "What was the 'Middle Passage'?",
    "options": ["The brutal forced voyage of enslaved Africans across the Atlantic.", "The overland trade route across the Sahara Desert.", "The journey of manufactured goods from Europe to Africa.", "The transport of sugar and tobacco from the Americas to Europe."],
    "answer": 0,
    "explanation": "The Middle Passage was the horrific transatlantic journey where millions of enslaved Africans were transported in appalling conditions."
  },
  {
    "question": "What was the primary crop grown on Caribbean plantations such as in Jamaica and Barbados?",
    "options": ["Sugar", "Tobacco", "Cotton", "Indigo"],
    "answer": 0,
    "explanation": "Sugar was the incredibly profitable but brutally demanding primary crop of the Caribbean."
  },
  {
    "question": "How did the experience of enslaved people in Virginia generally compare to those in the Caribbean by the 1700s?",
    "options": ["The enslaved population in Virginia became 'self-sustaining' due to a different climate and slightly better diet.", "Virginia plantations relied on a 'death camp' model to constantly import new enslaved people.", "Enslaved people in Virginia primarily farmed sugar rather than tobacco.", "There was no significant difference between the two regions."],
    "answer": 0,
    "explanation": "In Virginia, the population began to grow through childbirth, unlike the Caribbean where the brutal conditions necessitated constant importation."
  },
  {
    "question": "What is an 'absentee landlord' in the context of Caribbean sugar plantations?",
    "options": ["A wealthy owner who lived in Britain and left the plantation to be run by brutal overseers.", "An enslaved person who escaped the plantation.", "A European merchant who never visited West Africa.", "An overseer who refused to work on the plantation."],
    "answer": 0,
    "explanation": "Absentee landlords enjoyed the immense profits of sugar in London while ignoring the brutal realities of the labor that produced it."
  },
  {
    "question": "Why was the Caribbean sugar system often described as a 'death camp' model?",
    "options": ["Overseers calculated it was cheaper to work enslaved people to death and simply buy replacements.", "It was a system designed primarily to punish criminals.", "The plantations were located in areas with high rates of natural disasters.", "Enslaved people frequently died from starvation during the Middle Passage."],
    "answer": 0,
    "explanation": "The extreme profitability of sugar led overseers to brutally exploit enslaved people, knowing they could easily purchase more from the slave trade."
  },
  {
    "question": "How did the Triangular Trade fuel the Industrial Revolution in Britain?",
    "options": ["Profits from slave-produced goods were invested in British banks, infrastructure, and factories.", "Enslaved Africans were brought to Britain to work in factories.", "Britain stopped trading with Europe to focus solely on the Americas.", "The British government used taxes from the trade to build free public schools."],
    "answer": 0,
    "explanation": "The immense wealth generated by the exploitation of enslaved labor in the Americas provided the capital needed for Britain's industrialization."
  },
  {
    "question": "According to the UCL Legacies of British Slavery Database, what happened in 1833?",
    "options": ["The British government paid massive compensation to former slave owners.", "The British government paid reparations to formerly enslaved people.", "The Triangular Trade officially began.", "The first slave ship arrived in Virginia."],
    "answer": 0,
    "explanation": "When slavery was abolished, the British government controversially paid millions in compensation to the enslavers, not the enslaved."
  },
  {
    "question": "How does the reality of the Transatlantic Slave Trade challenge the idea of 18th-century Britain as a purely 'modern' and enlightened society?",
    "options": ["It demonstrates that Britain's wealth and modern financial systems were built on horrific brutality and chattel slavery.", "It shows that Britain was less technologically advanced than its European rivals.", "It proves that the Enlightenment had no impact on British politics.", "It highlights the fact that Britain was still primarily a feudal society."],
    "answer": 0,
    "explanation": "The juxtaposition of sophisticated financial markets in London with the brutal reality of plantation slavery reveals a dark contradiction in Britain's 'modernity'."
  }
];

const lesson6Quiz = [
  {
    "question": "What were the 'Maroons' in Jamaica?",
    "options": ["Communities of escaped enslaved people who fought guerrilla wars against the British.", "British politicians who campaigned for the abolition of the slave trade.", "A secret network of safe houses in the American South.", "Enslaved people who worked primarily as domestic servants."],
    "answer": 0,
    "explanation": "The Maroons were fierce communities of formerly enslaved people who successfully resisted British control in the Jamaican mountains."
  },
  {
    "question": "What was the significance of the Haitian Revolution (1791-1804)?",
    "options": ["It was the only successful large-scale slave revolt in history, resulting in an independent nation.", "It led to the immediate abolition of slavery throughout the British Empire.", "It was a peaceful transition to independence negotiated by French politicians.", "It resulted in the creation of the Underground Railroad."],
    "answer": 0,
    "explanation": "The Haitian Revolution, led by figures like Toussaint Louverture, utterly shattered the myth that enslaved people would not fight back and win."
  },
  {
    "question": "Who was Harriet Tubman?",
    "options": ["A famous 'Conductor' on the Underground Railroad who rescued dozens of enslaved people.", "A British politician who campaigned alongside William Wilberforce.", "The leader of the First Maroon War in Jamaica.", "A Jamaican plantation overseer who wrote a diary about enslaved resistance."],
    "answer": 0,
    "explanation": "Harriet Tubman demonstrated immense courage by repeatedly returning to the South to guide enslaved people to freedom."
  },
  {
    "question": "What was the 'Underground Railroad'?",
    "options": ["A secret network of safe houses and routes that helped enslaved people escape.", "A literal subterranean train system built by enslaved people.", "A British political movement to abolish the slave trade.", "A trade route used by the Maroons to smuggle goods."],
    "answer": 0,
    "explanation": "This grassroots resistance network was a vital lifeline for enslaved people seeking freedom in the American North or Canada."
  },
  {
    "question": "What was 'Obeah' in the context of the Caribbean?",
    "options": ["A spiritual belief system utilizing botanical knowledge, sometimes used for silent resistance.", "A type of cash crop grown alongside sugar.", "The name of a famous British slave ship.", "A term used to describe absentee landlords."],
    "answer": 0,
    "explanation": "Obeah practitioners used their expert knowledge of plants not only for healing but occasionally to secretly poison brutal enslavers."
  },
  {
    "question": "Why did enslavers live in constant terror of Obeah?",
    "options": ["Because practitioners could use their botanical knowledge to slowly and undetectably poison them.", "Because Obeah leaders frequently organized massive armed rebellions.", "Because Obeah was supported by the British government.", "Because it encouraged enslaved people to stop working entirely."],
    "answer": 0,
    "explanation": "The silent, psychological, and chemical threat posed by Obeah created deep paranoia among plantation owners."
  },
  {
    "question": "What is the 'White Savior Narrative' regarding the abolition of slavery?",
    "options": ["The idea that slavery was ended almost entirely by moral, upper-class white politicians like William Wilberforce.", "The belief that enslaved people freed themselves without any outside help.", "The argument that slavery ended primarily due to economic factors.", "The view that abolition was a mistake supported only by a small minority."],
    "answer": 0,
    "explanation": "This traditional narrative often ignores the crucial role played by enslaved people's own resistance."
  },
  {
    "question": "According to historians like Eric Williams, what were the two TRUE main reasons for the abolition of slavery?",
    "options": ["Declining economic profitability of sugar and massive, terrifying armed rebellions by enslaved people.", "The moral campaigning of William Wilberforce and the Enlightenment.", "The invention of the steam engine and the end of the Triangular Trade.", "The discovery of new trade routes to Asia and the decline of the Royal Navy."],
    "answer": 0,
    "explanation": "Williams argues that economic shifts and the immense cost/danger of suppressing slave revolts forced the British government's hand."
  },
  {
    "question": "How does the story of the Underground Railroad challenge traditional historical narratives?",
    "options": ["It shows enslaved people actively dismantling the system themselves, rather than waiting passively for white politicians.", "It proves that slavery was not as brutal as some historians claim.", "It suggests that abolition was primarily an American, rather than British, achievement.", "It demonstrates that the Triangular Trade was economically unsustainable."],
    "answer": 0,
    "explanation": "The active, courageous resistance of individuals like Harriet Tubman refutes the idea that enslaved people were mere passive victims."
  },
  {
    "question": "Based on Source A (Olaudah Equiano), what was a primary cause of death during the Middle Passage?",
    "options": ["Suffocation and sickness caused by severe overcrowding and lack of ventilation.", "Starvation due to a complete lack of food provisions.", "Execution by the ship's crew for attempted mutiny.", "Drowning from ships sinking in frequent Atlantic storms."],
    "answer": 0,
    "explanation": "Equiano describes the 'closeness of the place' and 'copious perspirations' leading to sickness and death in the horrific conditions of the ship's hold."
  }
];

let data;
try {
    const raw = fs.readFileSync('public/units/early_modern_world/data.js', 'utf8');
    const match = raw.match(/export const unitData = ([\s\S]+);/);
    data = eval('(' + match[1] + ')');
} catch (e) {
    console.error("Error", e);
    process.exit(1);
}

// Ensure unique quizzes
const existingQuiz5 = data.lessons[4].quiz || [];
const existingQuiz6 = data.lessons[5].quiz || [];

data.lessons[4].quiz = lesson5Quiz;
data.lessons[5].quiz = lesson6Quiz;

const newDataStr = `export const unitData = ${JSON.stringify(data, null, 2)};\n`;
fs.writeFileSync('public/units/early_modern_world/data.js', newDataStr, 'utf8');
fs.writeFileSync('early_modern_world/data.js', newDataStr, 'utf8');

console.log("Injected quizzes into Lesson 5 and 6!");
