const fs = require('fs');

const answersMap = {
  "Identify how Iron Age communit": "Iron Age communities usually lived near natural water sources such as rivers or springs. However, as settlements grew into towns, these natural sources became polluted or insufficient, leading to the need for engineered water systems.",
  "Knowledge Retrieval: Complete the summary table using the information from the text.": "<ul><li><strong>Who:</strong> Key individuals or groups involved in the event.</li><li><strong>What:</strong> A brief description of the main events or actions.</li><li><strong>Where:</strong> The specific locations where these events took place.</li><li><strong>When:</strong> The dates or timeframe of the event.</li><li><strong>Why:</strong> The causes or motivations behind the event.</li></ul>",
  "Describe one feature of the British Empire's contribution to the First World War. (2 marks)": "One feature of the British Empire's contribution was the sheer scale of manpower provided. For example, over 1.4 million men from the Indian Army volunteered, providing crucial combat support on the Western Front and in the Middle East.",
  "Q5. Study Source B and read the text on Racial Hierarchy. How does the impression given by the photograph contrast with the reality described in the text?": "Source B portrays the soldiers of different races standing together as equals, giving the impression of a unified and equal imperial force. In reality, the British military enforced a strict racial hierarchy, paying non-white troops significantly less and often assigning them to brutal manual labor or dangerous vanguard roles rather than commanding positions.",
  "Why do you think the 140,000 men of the Chinese Labour Corps were deliberately left out of the victory parades and historical memory?": "The British government deliberately marginalized the Chinese Labour Corps to maintain the narrative of a 'white man's victory'. Recognizing the crucial logistical contribution of non-white laborers would have challenged the era's racist ideologies and the concept of white imperial supremacy.",
  "Study Source C (Members of the Chinese Labour Corps). Why was the recruitment of the CLC critical to the British war effort, and how were they treated in return?": "The CLC was critical for logistics; they dug trenches, unloaded ships, and cleared battlefields, freeing up British soldiers for combat. In return, they were treated poorly, kept in segregated camps behind barbed wire, and faced harsh discipline and racism.",
  "Study Source A (the photograph of the British Indian Army).<br><br>How useful is Source A for an inquiry into the global nature of the First World War? (8 marks)": "Source A is highly useful for an inquiry into the global nature of the war because it visually proves that the conflict extended far beyond European armies. The photograph shows Indian soldiers deploying for combat, illustrating that the British Empire relied heavily on its colonies for manpower. The provenance (a photograph taken during the war) provides an objective snapshot of the imperial troops actually present. However, its usefulness is limited as a single photograph cannot show the full scale of global involvement, such as the Chinese Labour Corps or fighting in African theaters, nor does it reveal the systemic racism and unequal pay these soldiers faced.",
  "Why might mid-20th-century textbooks (Interpretation 1) have ignored the story of Khudadad Khan and the Taranto Mutiny?": "Mid-20th-century textbooks often reflected the prevailing Eurocentric and imperialist attitudes of the time. Ignoring figures like Khudadad Khan and events like the Taranto Mutiny helped maintain a simplified, patriotic narrative that focused entirely on British heroism, deliberately omitting the vital contributions of, and the racial injustices faced by, colonial troops.",
  "According to Interpretation 2, why did the British Empire deliberately construct the narrative of a 'white man's war'?": "According to Interpretation 2, the narrative of a 'white man's war' was constructed to protect the ideology of imperial supremacy. If colonial subjects were acknowledged as equal saviors of the Empire, they would naturally demand equal political rights and self-determination after the war, which threatened British control over its colonies.",
  "Why has the contribution of Empire troops often been forgotten?": "The contribution of Empire troops has often been forgotten because historical narratives were deliberately constructed by the imperial powers to highlight European heroism and maintain a hierarchy of race. Post-war commemorations, textbooks, and media largely excluded colonial soldiers to avoid acknowledging their crucial role and the subsequent demands for colonial independence.",
  "Explain why the contribution of Empire troops was so important to the British war effort.": "<strong>Point 1: Manpower</strong><br>The British army was heavily depleted by trench warfare; Empire troops provided essential reinforcements, with India alone sending over 1.4 million men to fight.<br><br><strong>Point 2: Logistics</strong><br>The war required massive logistical support. Groups like the Chinese Labour Corps dug trenches and transported supplies, allowing British troops to focus on combat.<br><br><strong>Point 3: Global Theatres</strong><br>Empire troops were vital for fighting in non-European theatres, such as the Middle East and Africa, securing British imperial interests against the Ottoman Empire.",
  "Study Source B (the painting of the Munitionettes).<br><br>How useful is Source B for an inquiry into the impact of the war on women? (8 marks)": "Source B is highly useful as it visually demonstrates the radical shift in women's roles, showing them performing heavy, industrial labor in munitions factories—work previously restricted to men. The provenance (a wartime painting) captures the scale of female mobilization. However, its usefulness is limited; as a piece of likely patriotic art, it may romanticize the work and omit the harsh realities, such as the deadly risk of TNT poisoning ('canaries') and the unequal pay women received compared to their male counterparts.",
  "Many people in 1916 believed Conscientious Objectors were cowards. How could you argue that it actually took immense bravery to be a 'Conchie'?": "Being a Conscientious Objector took immense bravery because they faced overwhelming social ostracization, public shaming (like receiving white feathers), and severe state punishment. Many 'Absolutists' endured brutal conditions in military prisons, including solitary confinement and physical abuse, standing firm in their moral or religious convictions despite immense pressure to conform.",
  "Study Source C (The 'Shot at Dawn' Memorial). Based on modern historical understanding, why is the execution of these 306 soldiers considered a tragic injustice?": "Modern understanding recognizes that many of the executed soldiers were suffering from severe Shell Shock (PTSD), a condition poorly understood at the time. They were not cowards but psychologically broken men who were denied fair military trials and were executed as an example to maintain discipline, making their deaths a tragic miscarriage of justice.",
  "Looking at Source D, why did the British government use DORA to mandate the strict censorship of soldiers' letters home? (Give two specific reasons).": "1. <strong>Preventing intelligence leaks:</strong> To ensure that operational details, troop movements, and locations did not accidentally fall into enemy hands.<br>2. <strong>Maintaining morale:</strong> To prevent the horrific realities of trench warfare from reaching the Home Front, which could damage civilian morale and reduce support for the war.",
  "How did the Defence of the Realm Act (DORA) change the relationship between the citizen and the state?": "DORA drastically altered the relationship by granting the state unprecedented control over citizens' daily lives. It restricted freedom of speech (censorship), movement, and commerce (pub opening hours, rationing), shifting Britain from a liberal democracy to a tightly regulated wartime state where individual rights were subordinated to national security.",
  "Explain how the Defence of the Realm Act (DORA) changed everyday life in Britain.": "<strong>Point 1: State Control and Censorship</strong><br>DORA allowed the government to heavily censor newspapers and soldiers' letters, ensuring the public only read positive, sanitized versions of the war to maintain morale.<br><br><strong>Point 2: Daily Restrictions</strong><br>It introduced numerous petty restrictions on daily life, such as diluting beer, restricting pub opening hours, and banning activities like flying kites or feeding ducks, to maximize productivity and resources.<br><br><strong>Point 3: Industrial and Economic Mobilisation</strong><br>DORA gave the government the power to take over factories for munitions production and eventually introduce strict food rationing to combat German U-boat blockades.",
  "Describe one feature of the military restrictions placed on Germany by the Treaty of Versailles. (2 marks)": "One feature of the military restrictions was the severe limitation on the size of the German army. The army was restricted to just 100,000 men, and conscription was completely banned, aiming to prevent Germany from ever starting another war.",
  "Study Source B (the 1919 political cartoon). What is the cartoonist suggesting about the long-term consequences of the Treaty of Versailles?": "The cartoonist is suggesting that the Treaty of Versailles is overly harsh and vindictive. By forcing Germany to swallow the 'peace terms' like a giant pill, it implies that the treaty is deeply humiliating and damaging, planting the seeds for future resentment and inevitably leading to another conflict.",
  "Was the Treaty of Versailles a fair settlement or a vindictive peace that guaranteed a future war?": "While some argue the Treaty was fair given the devastating damage Germany inflicted on France, it is widely considered a vindictive peace. The extreme reparations, the humiliating War Guilt Clause (Article 231), and the crippling military restrictions created deep economic instability and national resentment in Germany, directly fueling the rise of extremist parties like the Nazis and laying the groundwork for WWII.",
  "Explain why the Treaty of Versailles caused so much resentment in Germany.": "<strong>Point 1: The 'Diktat' and War Guilt</strong><br>Germany was not allowed to negotiate the treaty (a 'dictated peace') and was forced to accept full blame for starting the war under Article 231, which was deeply humiliating for a proud nation.<br><br><strong>Point 2: Economic Ruin</strong><br>The treaty demanded exorbitant reparations (£6.6 billion) while simultaneously stripping Germany of its wealthy industrial territories (like the Saar), plunging the country into a severe economic crisis and hyperinflation.<br><br><strong>Point 3: Military Vulnerability</strong><br>The restriction of the army to 100,000 men and the demilitarization of the Rhineland left Germany feeling defenseless and vulnerable to its hostile neighbors, dealing a massive blow to national pride.",
  "Where was the Stubbington War Memorial erected in 1922?": "The Stubbington War Memorial was erected in the center of the village, specifically built as a wooden shelter over the village's water pump.",
  "How many local names from Stubbington and Hill Head are carved into the memorial?": "There are 71 local names from Stubbington and Hill Head carved into the memorial.",
  "Study Source A (the Stubbington War Memorial). Why are local memorials like this crucial for a historian studying the human cost of the First World War?": "Local memorials are crucial because they humanize the vast, incomprehensible statistics of the war. They show the specific, devastating impact on small, tight-knit communities, demonstrating how entire generations of young men from specific streets and families were wiped out.",
  "Why is the story of the three Lowry brothers historically significant when studying the impact of the First World War?": "The Lowry brothers' story highlights the extreme tragedy of 'Pals Battalions' and sibling enlistment. It demonstrates the profound localized grief experienced by families who lost multiple sons, emphasizing that the war's trauma was deeply concentrated in specific households.",
  "Study Source B (the \\\"Dead Man's Penny\\\"). What does this source tell us about how the British government attempted to console grieving families, and why might it have felt inadequate?": "Source B shows that the government mass-produced bronze plaques to offer symbolic recognition of a soldier's sacrifice. However, it likely felt grossly inadequate because a generic piece of metal could never replace a lost son or husband, highlighting the disconnect between state commemoration and intense personal grief.",
  "<em>Instructions: Choose one of the five historical investigation tasks below": "This is a differentiated research task. Ensure your response directly addresses the specific prompts of the path you chose. For example, if you chose Path 1, your paragraph must explain how the 1911 Census reveals the civilian lives, ages, and occupations of the soldiers, transforming them from mere names on a plaque into real, contributing members of the village.",
  "How did the loss of a generation impact small communities like Stubbington?": "The loss of a generation devastated small communities economically and socially. The sudden absence of young men crippled local industries and farming, while the collective psychological trauma of mass mourning permanently altered the social fabric and optimism of the village.",
  "Explain the impact of the First World War on local communities like Stubbington.": "<strong>Point 1: Demographic Devastation</strong><br>Villages lost a significant percentage of their young male population, completely wiping out a generation of fathers, brothers, and husbands.<br><br><strong>Point 2: Economic Disruption</strong><br>The deaths of skilled tradesmen, laborers, and farmers severely impacted the local economy, forcing women and older generations to permanently take on new burdens to sustain the community.<br><br><strong>Point 3: Collective Trauma</strong><br>The shared grief created a permanent atmosphere of mourning. The erection of war memorials at the center of villages served as a constant, daily reminder of the colossal human cost paid by the community.",
  "1a. Describe one feature of the Home Front during the First World War. (2 marks)<br>1b. Describe one feature of the Treaty of Versailles. (2 marks)": "<strong>1a.</strong> One feature of the Home Front was the massive mobilization of women into the workforce. For example, thousands of women worked as 'munitionettes' in dangerous factories to supply the army.<br><br><strong>1b.</strong> One feature of the Treaty of Versailles was the War Guilt Clause (Article 231). This forced Germany to accept complete blame for starting the war, providing the justification for demanding massive financial reparations.",
  "How useful is Source A for an inquiry into the impact of the First World War on women? (8 marks)": "Source A is useful as it shows women taking on new, highly skilled, and dangerous industrial roles in munitions factories, proving that the war drastically expanded female employment beyond domestic service. Its provenance (a photograph taken during the war) makes it reliable evidence of the conditions inside these factories. However, its usefulness is limited because it does not show the long-term impact on women, such as the fact that most were forced out of these jobs when men returned in 1918, nor does it address the political impact, such as the subsequent granting of the vote to some women.",
  "How far do you agree with Interpretation 1? Explain your answer using your own knowledge. (16 marks + 4 SPaG)": "<strong>Paragraph 1: Agreeing with the Interpretation</strong><br>I agree with Interpretation 1 that the war was a catalyst for social change, particularly for women. The demand for labor on the Home Front led to women working in munitions, transport, and agriculture. This crucial contribution directly influenced the 1918 Representation of the People Act, which granted the vote to women over 30.<br><br><strong>Paragraph 2: Disagreeing (Short-term vs. Long-term)</strong><br>However, I disagree that the change was entirely permanent. When the war ended, the Restoration of Pre-War Practices Act forced many women out of their industrial jobs to make way for returning soldiers, returning them to domestic roles.<br><br><strong>Paragraph 3: Disagreeing (Focus on State Control)</strong><br>Furthermore, the interpretation ignores the negative impacts. The war introduced strict state control through DORA (censorship, rationing), demonstrating that the conflict also severely restricted civilian freedoms rather than just advancing them.<br><br><strong>Conclusion</strong><br>Overall, I partially agree. While the war undoubtedly accelerated political rights for women, the immediate social and economic changes were often temporary, and the conflict introduced unprecedented state interference in civilian life."
};

let content = fs.readFileSync('units/great_war_part2/data.js', 'utf8');
let changes = 0;

for (const [qText, aText] of Object.entries(answersMap)) {
  const targetDouble = '"' + qText + '",';
  const targetSingle = "'" + qText + "',";
  const targetNoComma = '"' + qText + '"'; // maybe it's the last item
  
  const formattedAnswer = aText.replace(/\"/g, '\\\\\"');
  const injectString = '\n              answer: "' + formattedAnswer + '",';
  
  if (content.includes(targetDouble)) {
    content = content.replace(targetDouble, targetDouble + injectString);
    changes++;
  } else if (content.includes(targetSingle)) {
    content = content.replace(targetSingle, targetSingle + injectString);
    changes++;
  } else if (content.includes(targetNoComma)) {
    content = content.replace(targetNoComma, targetNoComma + ',' + injectString);
    changes++;
  } else {
    // If it's multiline or has quotes inside it, the simple literal match fails.
    // So let's fall back to just replacing the string literal itself (not the quotes).
    // Just find qText and append after the quotes.
    const i = content.indexOf(qText);
    if (i !== -1) {
       // found the text inside some quotes.
       const substringFromText = content.substring(i + qText.length);
       // find the next quote
       let endQuoteIndex = substringFromText.indexOf('"');
       let endQuoteSingle = substringFromText.indexOf("'");
       let eq = -1;
       if (endQuoteIndex !== -1 && endQuoteSingle !== -1) {
           eq = Math.min(endQuoteIndex, endQuoteSingle);
       } else {
           eq = Math.max(endQuoteIndex, endQuoteSingle);
       }
       
       if (eq !== -1 && eq < 10) { // end quote is very close
          // find if there's a comma
          let endComma = substringFromText.indexOf(',', eq);
          if (endComma !== -1 && endComma < 15) {
             const before = content.substring(0, i + qText.length + endComma + 1);
             const after = content.substring(i + qText.length + endComma + 1);
             content = before + injectString + after;
             changes++;
          }
       }
    } else {
      console.log("Could not find:", qText.substring(0, 30) + '...');
    }
  }
}

fs.writeFileSync('units/great_war_part2/data.js', content);
console.log("Injected " + changes + " missing answers.");
