const fs = require('fs');

const content = fs.readFileSync('early_modern_world/data.js', 'utf8');
const prefix = 'export const unitData = ';
const jsonStr = content.replace(prefix, '').trim().replace(/;$/, '');
let data = eval('(' + jsonStr + ')');

data.cover_image = '/images/global_cover_collage.jpg';
// Change the short description to reference the grid
data.description = "Study the four sources on the cover. How did an isolated island in 1450 become the center of global trade by 1750? This unit explores the rapid transformation of Britain through exploration, trade, empire, and slavery.";

// Inject to Lesson 1: Canton
let l1 = data.lessons[0];
l1.narrative_blocks.splice(1, 0, {
    "title": "Macro-History: The Wealth of the East",
    "text": "Before 1750, European powers did not dominate the world. The true economic superpowers were Asian empires like Qing China and Mughal India. European merchants were desperate to access the silk, tea, and porcelain of China, but the Chinese Emperor severely restricted their access. European traders were forced to live and work in small, heavily regulated zones on the edge of the Pearl River in Canton, closely watched by Chinese authorities.",
    "image": "/images/global_canton.jpg",
    "image_alt": "View of the Thirteen Factories in Canton",
    "image_caption": "The Thirteen Factories in Canton, the only place where foreigners were legally allowed to trade in Qing China.",
    "source_letter": "A",
    "tasks": [
        {
            "type": "comprehension",
            "question": "Based on Source A, how does the reality of the Thirteen Factories in Canton challenge the idea that Europeans dominated global trade in the 1700s?",
            "model_answer": "It shows that Europeans did not dominate trade; instead, they were forced into small, heavily regulated zones (the Thirteen Factories) by the powerful Chinese Emperor, showing that Asian empires held the true economic power and dictated the terms of trade."
        }
    ]
});

// Inject to Lesson 2: Mercator
let l2 = data.lessons[1];
l2.narrative_blocks.splice(1, 0, {
    "title": "Macro-History: Navigating the Unknown",
    "text": "Driven by religious competition and a desperate need for resources, European sailors began charting the massive, terrifying unknown of the global oceans. Mapmakers like Gerardus Mercator developed revolutionary new map projections that helped sailors navigate the vast distances of the Atlantic and Pacific, shrinking the world and connecting isolated continents for the first time.",
    "image": "/images/global_mercator.jpg",
    "image_alt": "Mercator World Map 1569",
    "image_caption": "The revolutionary 1569 world map by Gerardus Mercator, which allowed sailors to plot straight-line courses across vast oceans.",
    "source_letter": "B",
    "tasks": []
});

// Inject to Lesson 4: Thames / Exchange
let l4 = data.lessons[3];
l4.narrative_blocks.splice(2, 0, {
    "title": "Macro-History: The Financial Hub",
    "text": "By the 1700s, the geography of wealth in Britain had fundamentally changed. London was no longer just the seat of the King; it had become the beating heart of a new global financial empire. The River Thames was choked with a forest of wooden ship masts from the East India Company and transatlantic slave ships. The wealth generated by this massive maritime trade built institutions like the Bank of England and the Royal Exchange, shifting power from the monarchy to the merchant class.",
    "image": "/images/royal_exchange.jpg",
    "image_alt": "The Royal Exchange in London",
    "image_caption": "The Royal Exchange in London, where merchants from across the globe met to trade shares, insurance, and commodities.",
    "source_letter": "C",
    "tasks": [
        {
            "type": "comprehension",
            "question": "How did the visual appearance of London change as it became a global financial hub?",
            "model_answer": "The River Thames became choked with a 'forest of wooden ship masts' from global trading vessels, and the city saw the rise of grand financial institutions like the Royal Exchange."
        }
    ]
});

// Inject to Lesson 6: Britannia
let l6 = data.lessons[5];
l6.narrative_blocks.splice(1, 0, {
    "title": "Macro-History: The Ideology of Empire",
    "text": "As Britain grew incredibly wealthy from the transatlantic slave trade and the East India Company, it developed a powerful new self-image. The British elite did not view themselves as brutal conquerors; instead, they believed they were bringing civilization and order to the world. Art from this period heavily utilized classical mythology to portray Britannia as a righteous, glorious figure receiving the willing submission and wealth of the globe.",
    "image": "/images/global_britannia.jpg",
    "image_alt": "The East Offering its Riches to Britannia",
    "image_caption": "An allegorical ceiling painting commissioned by the East India Company in 1778, showing Britannia receiving jewels, spices, and silk from personifications of Asia, Africa, and India.",
    "source_letter": "A",
    "tasks": [
        {
            "type": "source_analysis",
            "question": "Study Source A. How does this painting glorify the British Empire while masking the brutal realities of colonization?",
            "model_answer": "The painting glorifies the empire by showing a majestic Britannia peacefully receiving riches from willing, kneeling figures representing Asia and Africa. It masks the brutal realities by completely ignoring the violence, exploitation, and slavery (like the Transatlantic slave trade) that actually generated this wealth."
        }
    ]
});

const output = prefix + JSON.stringify(data, null, 4) + ';\n';
fs.writeFileSync('early_modern_world/data.js', output, 'utf8');
console.log('Global sources injected.');
