const fs = require('fs');

const dataPath = 'edexcel_medicine/data.js';
let dataCode = fs.readFileSync(dataPath, 'utf8');
let dataObjStr = dataCode.replace(/^export\s+default\s+/, '').replace(/;$/, '');
const lastBrace = dataObjStr.lastIndexOf('}');
const dataObj = eval('(' + dataObjStr.substring(0, lastBrace + 1) + ')');

const newAnswers = {
  'lesson_5_1': `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;"><tbody><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb; width: 40%;">Detail in Source A that I would follow up:</td><td style="border: 1px solid #ddd; padding: 12px;">"We cannot use the motor ambulances as the heavy rains and artillery have turned the roads into deep quagmires of mud."</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">Question I would ask:</td><td style="border: 1px solid #ddd; padding: 12px;">How did transport delays caused by mud and damaged roads affect the average time it took stretcher bearers to evacuate wounded soldiers to Dressing Stations?</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">What type of source I could use:</td><td style="border: 1px solid #ddd; padding: 12px;">RAMC Field Ambulance operational logs and battalion war diaries from the Battle of the Somme (1916).</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">How this might help answer my question:</td><td style="border: 1px solid #ddd; padding: 12px;">These documents provide daily notes on weather conditions, evacuation routes, and transport bottlenecks, helping a historian trace how stretcher bearer teams adapted when motor vehicles failed.</td></tr></tbody></table>`,
  
  'lesson_5_2': `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;"><tbody><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb; width: 40%;">Detail in Source A that I would follow up:</td><td style="border: 1px solid #ddd; padding: 12px;">"Altogether about 200 men had to be evacuated from our section of the trenches with swollen, numb feet due to the freezing mud."</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">Question I would ask:</td><td style="border: 1px solid #ddd; padding: 12px;">How widespread was the problem of trench foot evacuations across different divisions of the British Army on the Western Front during the winter of 1914–15?</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">What type of source I could use:</td><td style="border: 1px solid #ddd; padding: 12px;">Official British Army medical database records and RAMC Admission and Discharge registers from 1914–15.</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">How this might help answer my question:</td><td style="border: 1px solid #ddd; padding: 12px;">These records provide quantitative statistical data showing the total number of soldiers hospitalized or sent back to Britain for trench foot, helping to measure the scale of the epidemic.</td></tr></tbody></table>`,
  
  'lesson_5_4': `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;"><tbody><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb; width: 40%;">Detail in Source A that I would follow up:</td><td style="border: 1px solid #ddd; padding: 12px;">"The surgeons are constantly amputating limbs to stop the spread of gangrene before putting the men on the trains."</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">Question I would ask:</td><td style="border: 1px solid #ddd; padding: 12px;">What was the survival rate of wounded soldiers who underwent amputations at Casualty Clearing Stations to stop gangrene from spreading?</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">What type of source I could use:</td><td style="border: 1px solid #ddd; padding: 12px;">Casualty Clearing Station medical registers, surgical logs, and Base Hospital admission records from 1916.</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">How this might help answer my question:</td><td style="border: 1px solid #ddd; padding: 12px;">By cross-referencing CCS surgical lists with downstream Base Hospital records, a historian could track patient outcomes and calculate the success rate of frontline emergency amputations.</td></tr></tbody></table>`,

  'lesson_5_5': `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;"><tbody><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb; width: 40%;">Detail in Source A that I would follow up:</td><td style="border: 1px solid #ddd; padding: 12px;">"Several unsuccessful trials this morning to extract a shell fragment from a soldier's brain. Finally, we decided to try using a large wire nail as a magnet."</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">Question I would ask:</td><td style="border: 1px solid #ddd; padding: 12px;">How effective was the use of magnets or electromagnetic probes in extracting metallic shrapnel from brain injuries on the Western Front?</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">What type of source I could use:</td><td style="border: 1px solid #ddd; padding: 12px;">Articles and reports by military neurosurgeons published in contemporary medical journals like the Lancet or the Journal of the Royal Army Medical Corps (1916–1918).</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">How this might help answer my question:</td><td style="border: 1px solid #ddd; padding: 12px;">These medical papers would outline the clinical success and development of magnetic extraction techniques, explaining whether it became standard practice for dealing with complex shrapnel wounds to the cranium.</td></tr></tbody></table>`
};

dataObj.lessons.forEach(l => {
    if (newAnswers[l.id]) {
        let q = l.exam_practice.find(x => x.type === '4-mark');
        if (q) {
            q.answer = newAnswers[l.id];
        }
    }
});

const newDataCode = 'export default ' + JSON.stringify(dataObj, null, 2) + ';';
fs.writeFileSync(dataPath, newDataCode, 'utf8');
console.log('Successfully patched the remaining 4 answers.');
