const fs = require('fs');

const dataPath = 'edexcel_medicine/data.js';
let dataCode = fs.readFileSync(dataPath, 'utf8');
let dataObjStr = dataCode.replace(/^export\s+default\s+/, '').replace(/;$/, '');
const lastBrace = dataObjStr.lastIndexOf('}');
const dataObj = eval('(' + dataObjStr.substring(0, lastBrace + 1) + ')');

dataObj.lessons.forEach(l => {
    // 1. Update lesson_5_1 (8-mark question)
    if (l.id === 'lesson_5_1') {
        let q = l.exam_practice.find(x => x.type === '8-mark');
        if (q) {
            q.question = "<strong>How useful are Sources A and B for an enquiry into the difficulties faced by soldiers in the trench system of the Western Front?</strong> Explain your answer, using Sources A and B and your knowledge of the historical context.";
            q.stimulus = [
                "<strong>Source A: From the personal pocket diary of Private Thomas Atkins, serving with the British Infantry in the Ypres Salient, November 1916.</strong> 'The communication trenches are flooded with three feet of icy water, and the clay walls are collapsing into thick slime. Our boots are permanently waterlogged, and we have to dig out our firesteps constantly. The enemy shelled our support lines yesterday, throwing up colossal geysers of wet mud that choked our drainage channels.'",
                "<strong>Source B: An official photograph taken on the Somme in October 1916. It shows British soldiers attempting to maintain a communication trench.</strong> (Visual Description: A high-contrast black-and-white photograph depicting three British infantrymen wearing flat woolen trench caps and muddy service dress. They are standing thigh-deep in liquid mud inside a narrow, zig-zagged communication trench. One soldier is using a hand pump to clear water, while another uses a spade to shore up the sliding earth walls. The wooden duckboards at the bottom of the trench are completely submerged and invisible. In the background, the desolate trench line stretches back under a bleak, rain-filled sky.)"
            ];
            q.answer = `<p><strong>Source A is highly useful for an enquiry into the difficulties faced by soldiers in the trenches because it provides a raw, first-hand account of the physical decay of the defensive lines under severe weather and bombardment.</strong> The content of Source A reveals that communication trenches were prone to deep flooding and that the physical walls constantly collapsed into "thick slime." This is extremely useful because it shows how difficult it was for soldiers to maintain basic defensive structures (like firesteps) and navigate the trench system. The provenance of Source A enhances its utility; as a private diary written at the time by an active infantryman, it was not intended for publication and was not subject to official military censorship. It therefore reflects the genuine, unvarnished misery of daily life in the trenches.</p>
<p>From my own knowledge, I can verify these details. During the winter of 1916, particularly in mud-prone sectors like Ypres and the Somme, heavy rainfall combined with shellfire destroyed the natural drainage of the soil. This constant exposure to waterlogged trenches led to a massive rise in trench illnesses, most notably <strong>trench foot</strong>, which required soldiers to change socks twice a day and apply whale oil to prevent gangrene.</p>
<p><strong>Source B is also highly useful because it provides contemporary visual evidence of the physical labor and waterlogged conditions that defined trench maintenance.</strong> The content of the photograph shows soldiers standing "thigh-deep" in liquid mud and actively using a hand pump to clear water. This is useful because it highlights the primitive technology available to combat flooding and the constant, exhausting physical work required just to keep communication lines open.</p>
<p>The provenance of Source B, as an official photograph, means it may have been composed or approved by army censors, potentially downplaying the chaos of battle to avoid damaging morale in Britain. However, the sheer depth of the mud and the bleakness of the background make it highly useful as an accurate depiction of the environmental hardships. From my own knowledge, I know that communication trenches were vital for transporting food, ammunition, and wounded soldiers away from the front line. When these became choked with mud, as depicted in the source, it delayed stretcher bearers, meaning wounded men remained in No Man's Land or frontline positions for hours, increasing their risk of developing gas gangrene from soil-contaminated shrapnel wounds.</p>
<p><strong>In conclusion, both sources are highly useful when analyzed together.</strong> Source A provides a highly personal, emotional description of the mental and physical toll of the flooding, while Source B offers undeniable visual corroboration of the immense physical labor required to survive the waterlogged terrain.</p>`;
        }
    }

    // 2. Update lesson_5_5 (8-mark question)
    if (l.id === 'lesson_5_5') {
        let q = l.exam_practice.find(x => x.type === '8-mark');
        if (q) {
            q.question = "<strong>How useful are Sources A and B for an enquiry into the effectiveness of new medical developments used to treat wounded soldiers on the Western Front?</strong> Explain your answer, using Sources A and B and your knowledge of the historical context.";
            q.stimulus = [
                "<strong>Source A: From an official clinical report written by Captain Arthur Vaughan, a surgeon serving with the Royal Army Medical Corps (RAMC) at a Casualty Clearing Station (CCS) behind the frontline, October 1916.</strong> 'Our medical team at the Casualty Clearing Station has fully adopted the new leg traction splint. Before we received this iron frame, almost every compound femur fracture arrived at our ward in a state of terminal shock due to the jagged bones grating inside the flesh during transit. Since implementing this immobilization frame last month, we have kept the fractured limbs completely rigid. Out of forty admissions with thigh wounds, we have lost only six patients.'",
                "<strong>Source B: A photograph from a British medical instruction manual, published in 1917, showing the deployment of a traction device.</strong> (Visual Description: A detailed, black-and-white studio photograph showing a soldier lying flat on a wooden stretcher. His right leg is suspended and held rigid inside a metallic Thomas splint, which consists of a padded leather ring pushed up against the groin and parallel steel rods running down both sides of the limb. Bandages and canvas straps are wrapped tightly around the thigh and calf to keep the leg completely straight. A canvas sling is hooked to the end of the splint to pull the foot forward, creating traction. Two medical orderlies in clean aprons stand alongside, demonstrating how to attach the secure traction cords.)"
            ];
            q.answer = `<p><strong>Source A is highly useful for an enquiry into medical advances because it provides direct, statistical, and clinical evidence of the impact of the Thomas splint.</strong> The content of Source A highlights a dramatic reduction in fatalities, noting that before the splint's introduction, soldiers with shattered thigh bones regularly arrived in "terminal shock" due to blood loss caused by bones grating internally during transit. It shows that by keeping the leg rigid, the splint stabilized the injury. This is extremely useful because it provides a comparative look at medical outcomes before and after the development. The provenance of Source A is an official clinical report written by a practicing RAMC surgeon. Its purpose was to document medical outcomes for the army, meaning Captain Vaughan had an incentive to be highly precise with his clinical facts and figures, making the source highly reliable and useful for a historian.</p>
<p>From my own contextual knowledge, I can verify that in 1914 and 1915, a compound fracture of the femur carried a mortality rate of approximately <strong>80%</strong>, primarily due to the severe bleeding and shock caused by transport in rough, horse-drawn ambulances. The introduction of the <strong>Thomas splint</strong> (originally developed by Hugh Owen Thomas and brought to the Western Front by Robert Jones in late 1915) successfully kept the leg under traction and rigid, dropping the mortality rate to just <strong>20%</strong> by late 1916.</p>
<p><strong>Source B is also highly useful because it provides an incredibly detailed, clear illustration of the physical design and mechanical function of the Thomas splint.</strong> The photograph clearly shows the leather ring fitted against the groin and the steel rods running down the leg to provide the tension required to keep the bone aligned. This content is useful because it shows exactly how the apparatus was constructed and applied to a patient on a standard stretcher.</p>
<p>The provenance of Source B, being an official medical instruction manual published in 1917, means it was designed to train thousands of orderlies and stretcher-bearers rapidly as the splint was rolled out on a mass scale. While the studio setting is staged and does not reflect the muddy, chaotic reality of a frontline Regimental Aid Post, it remains highly useful for demonstrating the exact, standardized method of treatment. From my own knowledge, I know that the training of frontline staff in this method was a key reason why the splint was so effective; stretcher bearers applied the splint directly in the frontline trenches, preventing shock before the patient was even moved to a Dressing Station or Casualty Clearing Station.</p>
<p><strong>In conclusion, both sources are highly valuable.</strong> Source A provides the clinical justification and survival statistics proving the splint's medical effectiveness, while Source B provides the technical, physical layout showing exactly how this life-saving traction was achieved.</p>`;
        }
    }

    // 3. Update lesson_5_3 (4-mark follow up question)
    if (l.id === 'lesson_5_3') {
        let q = l.exam_practice.find(x => x.type === '4-mark');
        if (q) {
            q.answer = `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;"><tbody><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb; width: 40%;">Detail in Source A that I would follow up:</td><td style="border: 1px solid #ddd; padding: 12px;">"...many of the men did not adjust their woolen flannel pads quickly enough."</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">Question I would ask:</td><td style="border: 1px solid #ddd; padding: 12px;">What specific advancements in protective respiratory technology were introduced by the British Army after May 1915 to replace simple flannel pads?</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">What type of source I could use:</td><td style="border: 1px solid #ddd; padding: 12px;">Official British Army medical supply records and RAMC equipment logs from late 1915 and 1916.</td></tr><tr><td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; background-color: #f9fafb;">How this might help answer my question:</td><td style="border: 1px solid #ddd; padding: 12px;">These official supply records would detail the chronological development and distribution of more advanced protective gear, such as the gas-neutralizing 'Hypo Helmet' or the 'Small Box Respirator,' showing how quickly the army responded to the threat of gas to prevent blindness and suffocation.</td></tr></tbody></table>`;
        }
    }
});

const newDataCode = 'export default ' + JSON.stringify(dataObj, null, 2) + ';';
fs.writeFileSync(dataPath, newDataCode, 'utf8');
console.log('Successfully patched the user provided answers.');
