const fs = require('fs');
let file = 'public/units/early_modern_world/data.js';
let c = fs.readFileSync(file, 'utf8');

let l6TN = `"teacher_notes": {
        "primer": "This lesson focuses on the economic transformation of Britain. Students will explore how the rise of joint-stock companies, the Bank of England, and the transatlantic slave trade shifted true power away from the Crown and into the hands of a new capitalist merchant class.",
        "objectives": [
          {
            "objective": "Explain the role of the Royal Exchange and the Bank of England in creating a modern financial system.",
            "primer": "Direct students to analyze Source A (The Royal Exchange) to visualize how London transformed into a global financial hub.",
            "question": "How did institutions like the Bank of England permanently change the way the British government funded its wars and empire?"
          },
          {
            "objective": "Evaluate how transatlantic trade and slavery fueled the rise of the merchant class.",
            "primer": "Use the Macro-History section to emphasize that the River Thames was filled with ships funded by slave labor and colonial cash crops.",
            "question": "How did the wealth generated by enslaved labor in the colonies physically alter the landscape of London?"
          },
          {
            "objective": "Analyze the shift in power from the Monarchy to the Merchants.",
            "primer": "Have students compare the power of a medieval King with the power of an 18th-century merchant.",
            "question": "By 1700, who held more practical power in Britain: the King, or the directors of the East India Company? Why?"
          }
        ]
      }`;

let l6DoNow = `"do_now": {
        "title": "Do Now: Previous Knowledge",
        "type": "questions",
        "items": [
          {
            "question": "What was the 'Divine Right of Kings'?",
            "answer": "The belief that a monarch's authority comes directly from God."
          },
          {
            "question": "What was the name of the professional, religiously motivated army created by Parliament?",
            "answer": "The New Model Army."
          },
          {
            "question": "What happened to King Charles I in 1649?",
            "answer": "He was executed for treason."
          },
          {
            "question": "What were the Navigation Acts of 1651 designed to do?",
            "answer": "Ensure that all colonial trade was carried in English ships to boost mercantile wealth."
          },
          {
            "question": "What cash crops grown on Caribbean plantations made English merchants incredibly wealthy?",
            "answer": "Sugar and tobacco."
          }
        ]
      }`;

// We split by "title": "Who controlled Britain? The Economic Shift",
let parts = c.split('"title": "Who controlled Britain? The Economic Shift",');
if (parts.length > 1) {
    let secondPart = parts[1];
    // Find where vocab starts
    let vocabIdx = secondPart.indexOf('"vocab":');
    let replacedBlock = `
      ${l6TN},
      ${l6DoNow},
      `;
    c = parts[0] + '"title": "Who controlled Britain? The Economic Shift",' + replacedBlock + secondPart.substring(vocabIdx);
    fs.writeFileSync(file, c);
    console.log("Successfully patched L6!");
}
