const fs = require('fs');
let data = fs.readFileSync('public/units/trip_ypres/data.js', 'utf8');

const target = `Take a moment to read the inscription before the Last Post begins at 8:00 PM.</p></div></div>"`;

const replacement = `Take a moment to read the inscription before the Last Post begins at 8:00 PM.</p><div style='background: #f1f5f9; padding: 15px; border-radius: 6px; border: 1px solid #e2e8f0; margin-bottom: 15px;'><p style='margin: 0 0 10px 0; color: #334155; font-weight: bold;'><i class='fa-solid fa-video' style='color: #e11d48;'></i> The Empire\\'s War: Global Voices in Flanders</p><p style='margin: 0 0 10px 0; color: #475569;'>David Olusoga’s WW1 Uncut series brilliantly dismantles the traditional, whitewashed image of the trenches, making it the perfect digital companion for this stop.</p><p style='margin: 0 0 10px 0; color: #475569;'><strong>Action:</strong> Watch the embedded David Olusoga video on your device, then stand before the Indian Forces Memorial and complete these three steps:</p><ol style='margin: 0; padding-left: 20px; color: #475569;'><li style='margin-bottom: 8px;'><strong>Observe the Symbolism:</strong> Look closely at the monument\\'s base and the four Asian lions facing outward (the State Emblem of India). This memorial was unveiled in 2011. Why do you think it took nearly a century for a dedicated national monument to be placed here, and what does this delay tell us about how history is remembered?</li><li style='margin-bottom: 8px;'><strong>Challenge the Image:</strong> Olusoga explains that the Western Front was one of the most diverse spaces on earth. Look down at the Menin Gate, where 413 Indian soldiers with no known grave are carved into the stone alongside British troops. How does standing here change the traditional textbook image of the \\"British Tommy\\" in the mud?</li><li style='margin-bottom: 8px;'><strong>Discuss the Impact:</strong> Indian Expeditionary Force A arrived in freezing conditions in late 1914, plugging critical gaps in the British line just in time to prevent a German breakthrough. Discuss with your partner: How might the First Battle of Ypres have ended if those 45,000 Empire troops had not been deployed?</li></ol></div><div style='text-align: center; margin-bottom: 15px;'><iframe width='100%' height='315' src='https://www.youtube.com/embed/WRTm7mw25WU?start=182' frameborder='0' allowfullscreen></iframe><p style='font-size: 0.9rem; color: #64748b; margin-top: 5px; text-align: left;'><strong>Watch (6 mins 31 secs):</strong> Historian David Olusoga reveals the true diversity of the World War One trenches. Pay attention to the sheer number of nations that fought and died in the exact mud you are standing on today. <em>Contrast this with the Chattri Memorial on the South Downs in Sussex, where wounded Indian soldiers were cremated after being treated at the Royal Pavilion in Brighton.</em></p></div></div></div>"`;

if(data.includes(target)) {
  data = data.replace(target, replacement);
  fs.writeFileSync('public/units/trip_ypres/data.js', data);
  console.log('Successfully replaced Indian Forces text.');
} else {
  console.log('Target string not found!');
}
