const fs = require('fs');

function patchGreatWar() {
    let content = fs.readFileSync('great_war/data.js', 'utf8');
    let jsonStr = content.replace('export default great_war;', '').replace('const great_war =', '').trim();
    if (jsonStr.endsWith(';')) jsonStr = jsonStr.slice(0, -1);
    let data = eval('(' + jsonStr + ')');

    let l4 = data.lessons[3];
    l4.narrative_blocks[1].text = l4.narrative_blocks[1].text.replace('<strong></strong>', '<strong>Two-Power Standard</strong>');
    
    // There are four strong tags in L4 B5
    let b5text = l4.narrative_blocks[5].text;
    b5text = b5text.replace('<strong></strong>', '<strong>Scapa Flow</strong>');
    b5text = b5text.replace('<strong></strong>', '<strong>Wilhelmshaven</strong>');
    b5text = b5text.replace('<strong></strong>', '<strong>North Sea</strong>');
    b5text = b5text.replace('<strong></strong>', '<strong>Kiel Canal</strong>');
    l4.narrative_blocks[5].text = b5text;

    let l5 = data.lessons[4];
    let b2text = l5.narrative_blocks[2].text;
    b2text = b2text.replace('<strong></strong>', '<strong>Triple Alliance</strong>');
    b2text = b2text.replace('<strong></strong>', '<strong>Triple Entente</strong>');
    l5.narrative_blocks[2].text = b2text;

    let b3text = l5.narrative_blocks[3].text;
    b3text = b3text.replace('<strong></strong>', '<strong>encirclement</strong>');
    b3text = b3text.replace('<strong></strong>', '<strong>Conrad von Hötzendorf</strong>');
    b3text = b3text.replace('<strong></strong>', '<strong>inevitable</strong>');
    l5.narrative_blocks[3].text = b3text;

    let l6 = data.lessons[5];
    let l6b1text = l6.narrative_blocks[1].text;
    l6b1text = l6b1text.replace('<strong></strong>', '<strong>Pan-Slavism</strong>');
    l6b1text = l6b1text.replace('<strong></strong>', '<strong>annexed</strong>');
    l6.narrative_blocks[1].text = l6b1text;

    l6.narrative_blocks[2].text = l6.narrative_blocks[2].text.replace('<strong></strong>', '<strong>Appel Quay</strong>');
    l6.narrative_blocks[5].text = l6.narrative_blocks[5].text.replace('<strong></strong>', '<strong>Treaty of London (1839)</strong>');

    fs.writeFileSync('great_war/data.js', "const great_war = " + JSON.stringify(data, null, 2) + ";\n\nexport default great_war;");
    console.log('Patched great_war');
}

function patchIndEmp() {
    let content = fs.readFileSync('industrialisation_and_empire/data.js', 'utf8');
    let jsonStr = content.replace('export default industrialisation_and_empire;', '').replace('const industrialisation_and_empire =', '').trim();
    if (jsonStr.endsWith(';')) jsonStr = jsonStr.slice(0, -1);
    let data = eval('(' + jsonStr + ')');

    let l1 = data.lessons[0];
    if (l1.narrative_blocks[5].tasks.length === 0) {
        l1.narrative_blocks[5].tasks.push({
            type: "comprehension",
            question: "Why do modern historians argue that the profits from the Transatlantic Slave Trade were essential to the Industrial Revolution?",
            model_answer: "Historians argue that the immense capital required to build massive ironworks and kickstart the industrial economy was largely generated by the wealth extracted from enslaved labor on Caribbean sugar plantations, and British factories continued to rely on slave-picked American cotton."
        });
    }

    let l5 = data.lessons[4];
    if (l5.narrative_blocks[5].tasks.length === 0) {
        l5.narrative_blocks[5].tasks.push({
            type: "comprehension",
            question: "What was the most significant consequence of the 1857 Indian Rebellion for how India was governed?",
            model_answer: "The most significant consequence was that the East India Company was formally abolished by Parliament in 1858. Its territories were transferred directly to the British Crown, establishing the British Raj, because the government realised a private corporation could no longer safely govern the subcontinent."
        });
    }

    fs.writeFileSync('industrialisation_and_empire/data.js', "const industrialisation_and_empire = " + JSON.stringify(data, null, 2) + ";\n\nexport default industrialisation_and_empire;");
    console.log('Patched industrialisation_and_empire');
}

patchGreatWar();
patchIndEmp();
