%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Conventional Arab Armies Defeated 1967] --> B[Grassroots Nationalist Awakening]
  B --> C[Radical Splinter Groups Form e.g. PFLP]
  C --> D[Strategy of Internationalized Terror]
  D --> E[Dawson's Field Hijackings 1970]
  E --> F[World Spotlight Forced onto Palestinian Issue]