%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[ARAFAT'S 1974 DIPLOMATIC COGNITION]
  A --> B(Arafat's Metaphorical Warning)
  A --> C(UN Resolution 3236 Nov 1974)
  B --> D["Bearer of 'olive branch' (diplomacy)<br>Bearer of 'freedom fighter's gun' (violence)<br>Demanded sovereign homeland"]
  C --> E["Recognized right to self-determination<br>Conferred permanent UN Observer Status<br>Legitimized PLO as sole representative"]