%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Arafat backs Saddam Hussein in Gulf War] --> B[Gulf States cut off vital PLO funding]
  B --> C[PLO is diplomatically & financially isolated]
  C --> D[US/USSR co-sponsor Madrid Conference 1991]
  D --> E[Direct Arab-Israeli talks deadlocked]
  E --> F[Paves way for secret Norwegian channel]