%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE STRATEGIC OCCUPIED BUFFER ZONES]
  A --> B(The Golan Heights)
  A --> C(The Sinai Peninsula)
  A --> D(The West Bank & Gaza)
  B --> E["Prevented Syrian shelling<br>of Galilee farming"]
  C --> F["Kept Egyptian artillery<br>far from Israeli cities"]
  D --> G["Created defensible borders<br>Blocked cross-border raids"]