%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE 1964 CAIRO CONFERENCE]
  A --> B(Establishment of the PLO)
  A --> C(Dispute Over River Jordan)
  B --> D["Goal: Unite resistance groups<br>Officially backed by Arab League<br>Emergence of Fatah as military force"]
  C --> E["Israel builds National Water Carrier<br>Arab states build diversion canals<br>Led to intense border tank/artillery battles"]