%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE CAMP DAVID SUMMIT SEPT 1978]
  A --> B[13 Days of Seclusion]
  B --> C[Jimmy Carter's Mediation]
  C --> D[Two Framework Agreements]