%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE COGNITIVE IMPACT OF OPEC'S EMBARGO]
  A --> B(United States Peace Incentive)
  B --> C["Economy severely damaged by inflation and fuel shortages<br>Realized they must stabilize the Middle East to prevent future oil crises<br>and limit expanding Soviet influence in Egypt and Syria"]