%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE RISE OF 'FATAHLAND' IN LEBANON]
  A --> B[PLO Expelled from Jordan 1970]
  B --> C[PLO Establishes HQ in Southern Lebanon]
  C --> D[Cross-Border Katyusha Rocket Attacks]
  D --> E[Galilee Settlements Targeted]
  E --> F[1975 Lebanese Civil War Erupts]
  F --> G[PLO Allies with Leftist Muslim Coalition]