%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[1955 Gaza Raid Humiliates Egypt] --> B(Nasser Realises Military Weakness)
  B --> C[1955 Czech Arms Deal Soviet Bloc]
  C --> D(Egypt Receives Advanced Jets/Tanks)
  D --> E[Western Alarm: US/UK Cancel Dam Loan]
  E --> F(Nasser Nationalises Suez Canal)