%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE ISRAEL-JORDAN PEACE TREATY 1994]
  A --> B(King Hussein's Economic Crisis)
  A --> C(US Financial Inducements)
  B --> D["Jordan badly hit by Gulf War and<br>loss of trade; needed peace to rebuild"]
  C --> E["Clinton promises to cancel<br>Jordan's multi-million-dollar debts"]
  D --> F[Jordan becomes 2nd Arab nation to recognize Israel]
  E --> F