%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Labour Government elected under Yitzhak Rabin] --> B[Secret talks opened in Norway Dec 1992]
  B --> C[Hamas launches first suicide bombings 1993]
  C --> D[Rabin views PLO as a moderate alternative]
  D --> E[Arafat and Rabin sign Oslo I Accords]
  E --> F[Establishment of Palestinian Authority PNA]