%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE 1982 LEBANESE INVASION]
  A --> B[Ambassador Shlomo Argov Shot 3 June]
  B --> C[Operation Peace for Galilee 6 June]
  C --> D[IDF Bypasses UNIFIL and Races North]
  D --> E[Heavy Syrian Air Clashes 100 MiGs Shot Down]
  E --> F[Siege of West Beirut Encirclement]
  F --> G[14,000 PLO Fighters Evacuated to Tunis]