%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[LONG-TERM RESULTS OF LEBANESE INVASION]
  A --> B(PLO Expelled to Tunis)
  A --> C(The Rise of Hezbollah)
  A --> D(Israeli Security Zone)
  B --> E["Leadership moved 2,400km<br>away from Israel's borders<br>Weakened military threat"]
  C --> F["Formed by Shia militants<br>to resist IDF occupation<br>Backed directly by Iran"]
  D --> G["Narrow corridor 5-15km<br>SLA and IDF manned corridor<br>High IDF casualties"]