%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Nasser's Domestic & Geopolitical Aims]
  A --> B(Throw Off British Imperialism)
  A --> C(Socialist Internal Reforms)
  A --> D(The Aswan High Dam)
  B --> E["Expelled 80,000 British<br>troops from Suez Canal zone<br>Stood as champion of Arab pride"]
  C --> F["Redistributed fertile land<br>to the poor peasants<br>Built schools & hospitals"]
  D --> G["Ultimate pride project<br>Required massive foreign<br>loans to build on Nile"]