%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[OPERATION FOCUS: 5 JUNE 1967]
  A --> B[Low-altitude surprise air strike]
  B --> C[Egyptian radar successfully bypassed]
  C --> D[Bomb runways & destroy 309 Egyptian jets]
  D --> E[Total Israeli air superiority secured]