%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE OSLO II DIVISION OF LAND]
  A --> B(Area A: 3% of West Bank)
  A --> C(Area B: 27% of West Bank)
  A --> D(Area C: 70% of West Bank)
  B --> E["Full Palestinian PNA civil<br>and internal security<br>Encompassed major cities<br>(Ramallah, Nablus, Jenin)"]
  C --> F["Palestinian civil control,<br>but joint Israeli-Palestinian security<br>Covered 450 small towns"]
  D --> G["Full Israeli military & civil control<br>Encompassed settlements, bases, and bypass roads"]