%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Sadat faces economic collapse & riots] --> B[Realises conventional war is too costly]
  B --> C[Declares to Egyptian Parliament]
  C --> D[Will go to 'the ends of the earth' for peace]
  D --> E[Begin extends formal invitation]
  E --> F[Sadat lands at Ben Gurion Airport 19 Nov 1977]