%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[SADAT'S DIPLOMATIC ATTEMPTS 1971-72]
  A --> B(The Golda Meir Proposal)
  A --> C(Expelling the Soviets)
  B --> D["Sadat offers peace in return<br>for the complete return of Sinai<br><br>Rejected by Golda Meir"]
  C --> E["Sadat expels 15,000 Soviet advisors<br>Aim: Please USA and force them<br>Result: Met with complete US indifference"]