%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[ISRAELI SETTLEMENT POLICY]
  A --> B(Labor Government: Security)
  A --> C(Likud/Gush Emunim: Biblical)
  B --> D["Guided by the 'Allon Plan'<br>Built settlements as defensive<br>barriers along borders"]
  C --> E["Claimed divine right to Eretz Israel<br>Aimed to block any future<br>Palestinian statehood"]