%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Sinai returned to Egypt phased] --> B[Egypt grants diplomatic recognition to Israel]
  B --> C[Sinai demilitarised & monitored]
  C --> D[Suez Canal & Straits of Tiran fully open to IDF]