%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE SOVIET COLLAPSE GEOPOLITICAL DOMINO EFFECT]
  A --> B[USSR Dissolves Dec 1991]
  B --> C[PLO loses main finance & arms supplier]
  C --> D[200000 Soviet Jews migrate to Israel]
  D --> E[Settlement expansion in West Bank]
  E --> F[Unemployed Palestinians displaced]
  F --> G[Arafat pressured to seek urgent peace]