%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[CONSEQUENCES OF SUEZ FOR ISRAEL]
  A --> B(UNEF Deployment in Sinai)
  A --> C(Straits of Tiran Open)
  A --> D(IDF Military Deterrence)
  B --> E["Stationed as a buffer<br>Gaza Fedayeen raids<br>stopped for 10 years"]
  C --> F["Port of Eilat reopened<br>Secured vital trade<br>with Asia/Africa"]
  D --> G["Egyptian army routed<br>Deterred Arab states<br>from war until 1967"]