%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[THE SUPERPOWER GEOPOLITICAL FACE-OFF]
  A --> B(The US Weapons Airlift)
  A --> C(Soviet Intervention Threat)
  A --> D(The Arab OPEC Oil Embargo)
  B --> E["Nixon sends tanks/jets<br>Stabilizes IDF defenses"]
  C --> F["Brezhnev threatens troops<br>US goes to DEFCON 3 alert"]
  D --> G["OPEC quadruples oil prices<br>Chokes Western economies"]