%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Surprise Attack launched on Yom Kippur] --> B[IDF caught off-guard; mobilization slowed]
  B --> C[Egyptians breach the Bar Lev Line]
  C --> D[Syrian tanks overrun the Golan Heights]
  D --> E[IDF suffers heavy initial losses]
  E --> F[Superpower arms airlifts begin 15 Oct]