%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[Syria funds/arms Fatah guerrillas] --> B[Fatah launches sabotage raids into Israel]
  B --> C[IDF launches massive reprisal on Jordanian Samu]
  C --> D[King Hussein is deeply alienated]