%%{init: {'theme': 'base', 'themeVariables': { 'fontFamily': 'arial', 'primaryColor': '#ECECFF', 'primaryBorderColor': '#9370DB', 'primaryTextColor': '#333', 'lineColor': '#333333'}}}%%
flowchart TD
  A[UN RESOLUTION 242] --> B(English Wording: Loophole)
  A --> C(French Wording: Strict)
  B --> D["Withdrawal from territories<br>Israel argued it did NOT mean ALL<br>territories; allowed border expansion"]
  C --> E["'des territoires occupés'<br>Interpreted as requiring a<br>complete withdrawal to 1967 lines"]