const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, 'data.js');
let content = fs.readFileSync(targetPath, 'utf8');

// Parse the data safely
let data;
try {
  data = new Function(content.replace('export const unitData = ', 'return ').replace(/;$/, '') + ';')();
} catch (e) {
  console.error("Failed to parse data.js", e);
  process.exit(1);
}

const newTasks = {
  "lesson_2": {
    1: [{ type: "written", text: "What happened to the remaining portions of mandate Palestine (the West Bank and Gaza Strip) following the 1948-49 war? (P2)", model: "The West Bank and East Jerusalem were occupied and annexed by King Abdullah of Transjordan, while the Gaza Strip was placed under the military and administrative control of Egypt." }],
    2: [{ type: "written", text: "How did the United Nations attempt to cope with the vast humanitarian emergency created by the displacement of 700,000 Palestinian Arabs? (P3)", model: "The UN established the United Nations Relief and Works Agency (UNRWA) in December 1949 to construct and manage temporary refugee camps, providing basic food rations, tents, healthcare, and schooling." }],
    3: [{ type: "written", text: "Why did both Israel and the Arab host states refuse to permanently integrate the Palestinian refugees into their societies? (P4)", model: "Israel refused to allow refugees to return because it would destroy the Jewish majority and compromise national security. Arab states refused to integrate them to keep permanent diplomatic and moral pressure on Israel to honor the right of return." }],
    4: [{ type: "written", text: "Why was the establishment of the Israeli Defence Forces (IDF) in May 1948 highly significant for Israel's internal politics and national security? (P5)", model: "It systematically dismantled independent paramilitary groups (Haganah, Irgun, Lehi) and unified them under a single, highly professional state command, transforming Israel into a highly mobilized 'nation in arms' with a powerful national army." }],
    5: [{ type: "written", text: "Explain the demographic impact of the 1950 Law of Return on the new State of Israel. (P6)", model: "The Law of Return granted any Jew automatic citizenship, triggering an immense demographic boom that doubled Israel's population in a few years and supplied the IDF with a constant stream of military manpower." }],
    6: [{ type: "written", text: "Why did President Harry Truman authorise massive emergency loans and grants to Israel in its early years? (P7)", model: "Truman was driven by strong domestic sympathy for Holocaust survivors and intense political lobbying, providing critical financial and political aid to help Israel survive a severe economic crisis and an Arab League boycott." }],
    8: [{ type: "written", text: "Describe two ways that Egypt attempted to strangle Israel economically and militarily in the early 1950s. (P9)", model: "First, Egypt closed the Suez Canal to Israeli ships and confiscated cargo. Second, Egypt established a military blockade at the Straits of Tiran and used the Gaza Strip as a launchpad for Fedayeen guerrilla raids into Israel." }],
    9: [{ type: "written", text: "How did David Ben-Gurion attempt to deter Fedayeen border raids, and what was the consequence? (P10)", model: "Ben-Gurion implemented a severe reprisal policy, ordering the IDF to respond to every raid with disproportionate military force. This created an escalating border war that kept the region on the brink of conflict." }]
  },
  "lesson_3": {
    2: [{ type: "written", text: "What were Gamal Abdel Nasser’s immediate political and domestic objectives after taking power in Egypt? (P3)", model: "Politically, he pressured Britain to withdraw 80,000 troops from the Suez Canal Zone by June 1956. Domestically, he initiated sweeping reforms to help poor peasants, including land redistribution and building schools and clinics." }],
    3: [{ type: "written", text: "Why did Israel launch a devastating reprisal raid on the Gaza Strip on 28 February 1955, and what was the result? (P4)", model: "Israel launched the raid in retaliation for the ambush and murder of an Israeli civilian. IDF paratroopers killed 38 Egyptian soldiers, leaving Nasser's army thoroughly humiliated and proving his forces were too weakly equipped." }],
    5: [{ type: "written", text: "What was the significance of the 1955 Czech Arms Deal for the balance of power in the Middle East? (P6)", model: "The deal supplied Egypt with a massive arsenal of modern Soviet military hardware (including MiG-15 jets and tanks), bringing the Cold War directly into the Middle East and deeply alarming Israel and the West." }],
    6: [{ type: "written", text: "How did President Nasser respond when the United States and Great Britain abruptly withdrew their funding for the Aswan High Dam? (P7)", model: "On 26 July 1956, Nasser delivered a fiery speech announcing the nationalisation of the Suez Canal Company, seizing it from British and French shareholders to use the toll revenues to fund the dam." }],
    7: [{ type: "written", text: "What was the secret Protocol of Sèvres in October 1956? (P8)", model: "It was a highly secret conspiracy between Britain, France, and Israel to plan a coordinated military intervention to overthrow Nasser and retake the Suez Canal." }],
    9: [{ type: "written", text: "Explain how Britain and France planned to use an Israeli invasion of the Sinai as a pretext to retake the Suez Canal. (P10)", model: "Once Israel launched a pre-emptive strike toward the canal, Britain and France would issue an ultimatum for both sides to pull back. When Egypt inevitably refused, Britain and France would invade to 'protect' international shipping." }],
    10: [{ type: "written", text: "Why did the Anglo-French-Israeli conspiracy backfire and end in a humiliating retreat? (P11)", model: "The conspiracy faced furious resistance from global superpowers. The Soviet Union threatened nuclear strikes, and US President Eisenhower applied massive economic pressure on Britain, threatening to refuse loans and block oil access." }],
    14: [{ type: "written", text: "Identify two vital security guarantees Israel received in exchange for withdrawing its forces from the Sinai Peninsula. (P15)", model: "First, the deployment of the UN Emergency Force (UNEF) buffer along the border halted Fedayeen raids for 10 years. Second, UNEF forced Egypt to reopen the Straits of Tiran, securing Israel's vital trade port of Eilat." }]
  },
  "lesson_4": {
    1: [{ type: "written", text: "What was the primary objective of the Palestine Liberation Organisation (PLO) when it was established at the 1964 Cairo Conference? (P2)", model: "The primary objective was to unite various Palestinian resistance groups under a single political umbrella to destroy the State of Israel and reclaim the lost homeland for Palestinian refugees." }],
    3: [{ type: "written", text: "How did the dispute over the River Jordan escalate tensions between Israel and the Arab states in the mid-1960s? (P4)", model: "Arab leaders agreed to divert the headwaters of the River Jordan to starve Israel's new National Water Carrier of water. Israel responded by using tanks and artillery to destroy Syrian diversion equipment, leading to an active border war." }],
    5: [{ type: "written", text: "How did the new Syrian government support the Fatah guerrilla movement from 1966 onwards? (P6)", model: "The Syrian government provided Fatah with funds, modern explosives, and training bases inside Syrian territory, enabling them to launch a relentless campaign of cross-border sabotage raids into Israel." }],
    7: [{ type: "written", text: "What was the outcome of the April 1967 air clash over Damascus, and how did it affect the Syrian leadership? (P8)", model: "Israeli fighter jets shot down six Syrian Soviet-built MiG-21 jets in a single afternoon. This humiliating defeat left the Syrian leadership desperate to restore their military honor." }],
    9: [{ type: "written", text: "How did the Soviet Union's misinformation in May 1967 act as a catalyst for the crisis? (P10)", model: "The Soviet Union falsely warned President Nasser that Israel was massing ten brigades on the Syrian border for a full-scale invasion, placing immense pressure on Nasser to act." }],
    10: [{ type: "written", text: "Identify two dangerous gambles President Nasser took between 15 May and 23 May 1967. (P11)", model: "First, he ordered UN peacekeepers to withdraw from the Sinai border. Second, he closed the Straits of Tiran to all Israeli shipping, an action Israel considered a formal act of war." }],
    12: [{ type: "written", text: "Describe the success of Operation Focus launched by the Israeli air force on 5 June 1967. (P13)", model: "Operation Focus was a highly successful pre-emptive strike where Israeli jets flew low over the Mediterranean to evade radar and destroyed 309 of Egypt's combat aircraft on the tarmac within three hours." }],
    15: [{ type: "written", text: "What were the key territorial conquests of the Israeli Defence Forces during the land war? (P16)", model: "The IDF captured the entire Sinai Peninsula and Gaza Strip from Egypt, the West Bank and East Jerusalem from Jordan, and the strategic Golan Heights from Syria." }]
  },
  "lesson_5": {
    2: [{ type: "written", text: "How did Israel and the Arab states interpret the ambiguous wording of UN Resolution 242 differently? (P3)", model: "Israel used the English text ('territories occupied') to argue it only had to withdraw from some territories, while Arab states used the French text ('des territoires occupés') to demand a complete withdrawal to pre-war boundaries." }],
    3: [{ type: "written", text: "What was the defiant response of the Arab states at the August 1967 Arab League Summit in Khartoum? (P4)", model: "They issued the 'Three Nos of Khartoum': No peace with Israel, No recognition of Israel, and No negotiations with Israel, resulting in a diplomatic deadlock." }],
    6: [{ type: "written", text: "Explain the strategic significance of the captured territories for Israel's military security. (P7)", model: "The territories acted as vast physical buffers: the Sinai kept Egyptian artillery away, the West Bank created a defensible border along the River Jordan, and the Golan Heights prevented Syria from shelling Galilee farming villages." }],
    7: [{ type: "written", text: "How did the Israeli policy of building Jewish settlements in the occupied territories impact the local Arab population? (P8)", model: "The settlements created permanent 'facts on the ground' that fragmented Palestinian society, restricted movement through military checkpoints, and deeply alienated the local Arab population." }],
    10: [{ type: "written", text: "Why did the Popular Front for the Liberation of Palestine (PFLP) hijack commercial airliners to Dawson's Field in 1970? (P11)", model: "The PFLP pioneered international aviation terrorism to grab global attention and force the Palestinian issue onto the international diplomatic stage, though it deeply embarrassed King Hussein of Jordan." }],
    11: [{ type: "written", text: "Why did King Hussein of Jordan view the PLO as a threat to his sovereignty by 1970? (P12)", model: "The PLO had established a 'state-within-a-state' in Jordan, collecting taxes, running checkpoints, and launching unauthorized rocket attacks on Israel that drew destructive military reprisals onto Jordanian territory." }],
    13: [{ type: "written", text: "What was the outcome of the 'Black September' civil war in Jordan in 1970? (P14)", model: "The Jordanian army used heavy artillery and tanks to crush the PLO forces. Yasser Arafat and thousands of PLO fighters were defeated and forcibly expelled from Jordan, relocating their headquarters to Lebanon." }],
    16: [{ type: "written", text: "Describe the events and consequences of the 1972 Munich Olympic Games terrorist attack. (P17)", model: "Black September terrorists took 11 Israeli athletes hostage, demanding the release of Palestinian prisoners. During a botched German rescue attempt, all hostages and 5 terrorists were killed on live television, drawing severe global condemnation." }]
  },
  "lesson_6": {
    2: [{ type: "written", text: "How did Israel respond to Nasser's artillery bombardments during the War of Attrition, and what was Nasser's reaction? (P3)", model: "Israel conducted deep-penetration bombing raids into Egypt targeting military and industrial sites. In response, Nasser turned to his Soviet patrons, resulting in 15,000 Soviet military advisers and SAM-3 missile bases being stationed in Egypt." }],
    4: [{ type: "written", text: "Why did Anwar Sadat believe he desperately needed to secure the return of the Sinai Peninsula? (P5)", model: "Sadat needed to return the Sinai and reopen the Suez Canal to revive Egypt's collapsing economy and send home his one million mobilized soldiers, who were straining the country's resources." }],
    6: [{ type: "written", text: "What was the 'Peace for Sinai' offer proposed by Anwar Sadat, and why did Golda Meir reject it? (P7)", model: "Sadat offered a formal peace agreement and the reopening of the Suez Canal in exchange for the return of the Sinai Peninsula. Golda Meir rejected it because Israel was confident in its military superiority and refused to return to vulnerable pre-1967 borders." }],
    7: [{ type: "written", text: "Why did Sadat expel 15,000 Soviet advisers from Egypt in July 1972, and what was the US reaction? (P8)", model: "Sadat expelled them hoping to win diplomatic favor with the US and prompt them to pressure Israel into concessions. However, the Nixon administration was preoccupied with Vietnam and met the gesture with total indifference." }],
    10: [{ type: "written", text: "What was the Bar Lev Line, and what was its purpose? (P11)", model: "The Bar Lev Line was a massive Israeli military fortification along the east bank of the Suez Canal, consisting of a 20-meter-high sand wall, concrete bunkers, and artillery designed to make any Egyptian crossing impossible." }],
    13: [{ type: "written", text: "How did the Egyptian army successfully breach the Bar Lev Line at the start of the Yom Kippur War? (P14)", model: "Egyptian forces crossed the Suez Canal and used high-pressure water hoses to rapidly wash away and breach Israel's formidable sand-wall defenses, pouring infantry and tanks into Sinai." }],
    15: [{ type: "written", text: "Describe the superpower proxy conflict that emerged during the Yom Kippur War. (P16)", model: "US President Richard Nixon authorized Operation Nickel Grass, a massive airlift of advanced weapons to Israel. Simultaneously, the Soviet Union launched a massive arms resupply to Egypt and Syria, turning the conflict into a Cold War proxy war." }],
    17: [{ type: "written", text: "How did the Arab members of OPEC attempt to force the United States to restrain Israel? (P18)", model: "They unleashed the 'Oil Weapon' by placing a total oil embargo on the US and Western nations supporting Israel, cutting production and quadrupling oil prices to trigger a severe global energy crisis." }]
  },
  "lesson_7": {
    2: [{ type: "written", text: "How did the 1973 Yom Kippur War change the diplomatic calculations of the United States? (P3)", model: "Badly hit by the oil embargo, the US gained a powerful financial incentive to broker lasting peace to ensure the stable flow of Middle Eastern oil, and wanted to use negotiations to pull Egypt out of the Soviet sphere of influence." }],
    4: [{ type: "written", text: "What was the result of Henry Kissinger's Sinai II Agreement (September 1975)? (P5)", model: "Israel surrendered the strategic Gidi and Mitla passes and the vital Abu Rudeis oil fields to Egypt. Crucially, the US established manned early-warning electronic monitoring stations in Sinai to guarantee compliance." }],
    7: [{ type: "written", text: "What dramatic gesture did Anwar Sadat make on 19 November 1977 to break the diplomatic deadlock? (P8)", model: "Sadat flew to Israel, landed at Ben Gurion Airport, and addressed the Israeli Knesset, offering Israel complete recognition and permanent peace in exchange for a complete withdrawal from occupied Arab lands." }],
    9: [{ type: "written", text: "Outline the key terms of Framework 2 of the 1978 Camp David Accords. (P10)", model: "Framework 2 outlined a bilateral peace treaty: Israel agreed to a phased, complete withdrawal from the Sinai Peninsula, and Egypt agreed to normalise relations and officially recognize Israel's right to exist." }],
    11: [{ type: "written", text: "What was the tragic personal consequence for Anwar Sadat following the signing of the peace treaty? (P12)", model: "On 6 October 1981, Anwar Sadat was assassinated by radical Islamic militants within the Egyptian army who opposed his peace with Israel." }]
  },
  "lesson_8": {
    2: [{ type: "written", text: "What was the significance of UN Resolution 3236 (November 1974) for the PLO? (P3)", model: "The resolution formally recognized the inalienable rights of the Palestinian people to self-determination, granted the PLO permanent Observer Status at the UN, and legitimized the PLO diplomatically." }],
    4: [{ type: "written", text: "What was 'Fatahland' and how did it threaten Israeli security? (P5)", model: "Fatahland was a powerful PLO 'state-within-a-state' in southern Lebanon. From these bases, PLO guerrillas launched cross-border raids and fired Katyusha rockets into northern Israel, terrorizing civilian settlements in the Galilee." }],
    6: [{ type: "written", text: "What pretext did Israeli Defense Minister Ariel Sharon use to launch Operation Peace for Galilee in June 1982? (P7)", model: "Sharon used the attempted assassination of Shlomo Argov (Israel's ambassador to Great Britain) by the Abu Nidal Organization as the pretext to launch a long-planned, total invasion of Lebanon." }],
    8: [{ type: "written", text: "What were Ariel Sharon’s larger geopolitical ambitions behind the 1982 invasion of Lebanon? (P9)", model: "Sharon's true ambitions were to completely destroy the PLO in Lebanon, defeat Syrian forces, and install a pro-Israeli Christian government in Beirut led by Maronite leader Bashir Gemayel." }],
    11: [{ type: "written", text: "Describe the events and consequences of the Sabra and Shatila massacre in September 1982. (P12)", model: "Israeli forces allowed Lebanese Christian Phalangist militias into the refugee camps, who slaughtered between 800 and 3,500 unarmed civilians. The atrocities triggered furious global condemnation, forcing Ariel Sharon to resign after the Kahan Commission found him indirectly responsible." }],
    13: [{ type: "written", text: "What event marked the start of the First Palestinian Intifada in December 1987? (P14)", model: "An Israeli military truck collided with a civilian car, killing four Palestinians. This sparked massive, spontaneous demonstrations across Gaza and the West Bank." }],
    15: [{ type: "written", text: "How did the First Intifada shift global public sympathy toward the Palestinian cause? (P16)", model: "The Intifada featured grassroots civil disobedience and unarmed youth throwing stones at tanks. Television cameras broadcasting footage of heavily armed Israeli soldiers beating children under Rabin's 'Iron Fist' policy severely damaged Israel’s international moral standing." }]
  },
  "lesson_9": {
    2: [{ type: "written", text: "How did Yasser Arafat enact a historic shift in PLO strategy in late 1988? (P3)", model: "Arafat officially accepted the two-state solution, recognizing Israel's right to exist. In a UN speech, he explicitly renounced all forms of terrorism, forcing the US to open formal diplomatic talks with the PLO." }],
    5: [{ type: "written", text: "How did the collapse of the Soviet Union in 1991 severely damage the PLO's geopolitical position? (P6)", model: "The PLO lost its primary funding and diplomatic backing. Additionally, over 200,000 Soviet Jews migrated to Israel, leading to the expansion of West Bank settlements and displacing Palestinian workers." }],
    7: [{ type: "written", text: "Why was the PLO left bankrupt and diplomatically isolated following the 1991 Gulf War? (P8)", model: "Arafat made the disastrous decision to publicly support Saddam Hussein's invasion of Kuwait. Outraged Gulf Arab states cut off all financial donations, and Kuwait expelled over 300,000 Palestinian workers." }],
    9: [{ type: "written", text: "What convinced Israeli Prime Minister Yitzhak Rabin to engage in secret negotiations with the PLO in 1993? (P10)", model: "The rising violence of Hamas, including their first suicide car bombing in April 1993, convinced Rabin that Arafat’s PLO was a moderate alternative that he needed to negotiate with." }],
    13: [{ type: "written", text: "Why did the Oslo II Accords trigger a massive political backlash among Palestinians? (P14)", model: "Palestinians were frustrated that the newly formed Palestinian National Authority only controlled a fragmented archipelago (Area A, 3% of land), while Israel retained full military and civil control over 70% of the West Bank (Area C)." }],
    15: [{ type: "written", text: "What event dealt a fatal blow to the peace process on 4 November 1995? (P16)", model: "Israeli Prime Minister Yitzhak Rabin was assassinated at a peace rally in Tel Aviv by a radical right-wing Jewish extremist, leaving the permanent status issues of the peace process unresolved." }]
  }
};

data.lessons.forEach(lesson => {
  if (newTasks[lesson.id]) {
    const patchTasks = newTasks[lesson.id];
    if (lesson.narrative_blocks) {
      lesson.narrative_blocks.forEach((block, index) => {
        if (patchTasks[index]) {
          block.tasks = patchTasks[index];
        }
      });
    }
  }
});

// Write back to file
const newContent = 'export const unitData = ' + JSON.stringify(data, null, 2) + ';';
fs.writeFileSync(targetPath, newContent, 'utf8');
console.log('Successfully updated data.js with all new questions!');
