const fs = require('fs');

const dataPath = 'edexcel_medicine/data.js';
let rawData = fs.readFileSync(dataPath, 'utf8');

// Parse the data
let jsonStr = rawData.replace(/^export default /, '').trim();
if (jsonStr.endsWith(';')) jsonStr = jsonStr.slice(0, -1);
let data = JSON.parse(jsonStr);

// Process the Western Front lessons
data.lessons.forEach(lesson => {
  if (lesson.id.startsWith('lesson_5_') && lesson.extended && lesson.extended.model) {
    if (lesson.id === 'lesson_5_1') {
      lesson.extended.model = `<strong>Source A is highly useful for an enquiry into the difficulties faced by soldiers in the trench system because its content vividly describes the reality of the muddy conditions.</strong> It reveals that trenches were flooded with <strong style="color: #0284c7;">"three feet of icy water"</strong> and that artillery shells threw up <strong style="color: #0284c7;">"colossal geysers of wet mud"</strong>. <strong style="color: #16a34a;">I can support this with my own contextual knowledge: constant bombardment destroyed the drainage systems in areas like Ypres, turning the clay soil into a deep, waterlogged quagmire that caused trench foot and made movement nearly impossible.</strong> <strong style="color: #9333ea;">Furthermore, the provenance makes the source incredibly useful; it is a personal pocket diary written by a soldier serving on the frontline in 1916. Because it is a private diary, it is an honest, uncensored eyewitness record of the sheer misery and physical difficulties the men endured.</strong> Overall, Source A provides highly useful, accurate evidence of the terrible conditions.<br><br><strong>Source B is also highly useful for this enquiry because its content provides direct visual evidence of the physical difficulties the soldiers faced.</strong> It shows soldiers struggling thigh-deep in liquid mud, forced to use a hand pump to clear the trench. <strong style="color: #16a34a;">My contextual knowledge confirms that duckboards were often completely submerged by the mud, and the crumbling walls required constant shoring up with spades and sandbags just to keep the trenches from collapsing in on the men.</strong> <strong style="color: #9333ea;">The provenance makes the source useful as it is an official photograph taken during the Battle of the Somme in 1916. While official photographs were often subject to censorship to keep morale high back home, the undeniable presence of the deep mud in this photograph provides an objective, literal snapshot of the severe physical difficulties the troops navigated daily.</strong> Therefore, Source B is extremely useful as it demonstrates exactly what the muddy conditions looked like.`;
    } else if (lesson.id === 'lesson_5_2') {
      lesson.extended.model = `<strong>Source A is highly useful for an enquiry into the transport of the wounded because its content highlights the severe physical distress caused to patients by the poor transport infrastructure.</strong> It describes the journeys as <strong style="color: #0284c7;">"perfect nightmares"</strong> because it was <strong style="color: #0284c7;">"impossible not to bump"</strong> over the <strong style="color: #0284c7;">"appalling roads full of holes"</strong>. <strong style="color: #16a34a;">I can support this with my own contextual knowledge: constant artillery shelling completely destroyed the roads and terrain on the Western Front, meaning ambulance journeys were violently bumpy. This shaking frequently worsened soldiers' injuries and increased fatal blood loss before they could reach a Casualty Clearing Station for surgery.</strong> <strong style="color: #9333ea;">The provenance makes the source extremely useful; as a published autobiography from an actual FANY ambulance driver who worked during the 1916 Somme offensive, it provides a highly reliable, eyewitness account of the emotional and physical reality of evacuating the wounded over devastated terrain.</strong> Overall, Source A provides highly useful evidence of how poor roads made motor transport agonizing for the wounded.<br><br><strong>Source B is also highly useful for this enquiry because its content provides direct visual evidence of the types of transport the medical services were forced to rely on due to the terrible conditions.</strong> It shows a basic, horse-drawn ambulance wagon navigating a muddy, rutted track. <strong style="color: #16a34a;">My contextual knowledge confirms that although 512 motor ambulances were introduced after a public appeal in 1914, heavy motor vehicles frequently got stuck in the deep mud. This forced the RAMC to continue relying heavily on horse-drawn wagons—sometimes requiring up to six horses to pull them through the sludge—which were much slower and bumpier for the casualties inside.</strong> <strong style="color: #9333ea;">The provenance makes the source useful as it is a photograph taken precisely at the time of the Battle of the Somme in September 1916, providing an objective, literal snapshot of the difficult, muddy environment the Field Ambulance had to operate in.</strong> Therefore, Source B is extremely useful as it demonstrates why modern motor ambulances could not entirely replace slower horse-drawn transport on the muddy Western Front.`;
    } else if (lesson.id === 'lesson_5_3') {
      lesson.extended.model = `<strong>Source A is highly useful for an enquiry into the effects of gas attacks because its content vividly details the horrific physical symptoms it caused.</strong> It reveals that chlorine gas caused <strong style="color: #0284c7;">"a flooding of the lungs"</strong> and the <strong style="color: #0284c7;">"coughing up of a greenish froth"</strong>, ultimately <strong style="color: #0284c7;">"resulting in death"</strong>. <strong style="color: #16a34a;">I can support this with my own contextual knowledge: chlorine gas was first used as a weapon at the Second Battle of Ypres in 1915 and worked by suffocating the victim from the inside out, causing massive panic among the troops who were completely unprepared for it.</strong> <strong style="color: #9333ea;">Furthermore, the provenance makes the source incredibly useful; it is a first-hand notebook account from Lance Sergeant Elmer Cotton who served during 1915, making it a reliable, eyewitness record of the sheer terror and physical trauma the gas inflicted on the men.</strong> Overall, Source A provides highly useful, accurate evidence of the deadly physical impact of early gas attacks.<br><br><strong>Source B is also highly useful for this enquiry because its content provides direct evidence of the lethal effectiveness and visual impact of gas on the victims.</strong> It describes a <strong style="color: #0284c7;">"huge, greenish cloud of smoke"</strong> that caused a man's face to turn <strong style="color: #0284c7;">"dark blue"</strong> as he was <strong style="color: #0284c7;">"struggling to breathe"</strong>. <strong style="color: #16a34a;">My contextual knowledge confirms that chlorine gas formed a visible green cloud that destroyed the lungs, and because the British army did not issue proper gas masks until July 1915, casualty rates in early attacks could be devastatingly high.</strong> <strong style="color: #9333ea;">The provenance makes the source useful as it is a personal account from a soldier who directly witnessed the aftermath of the attack at the ambulances, providing a raw, emotional insight into the suffering.</strong> Therefore, Source B is extremely useful as it demonstrates exactly how vulnerable the soldiers initially were to the suffocating effects of this terrifying new weapon.`;
    }
  }
});

// Save back
const newFileContent = `export default ${JSON.stringify(data, null, 2)};\n`;
fs.writeFileSync(dataPath, newFileContent, 'utf8');
console.log('Successfully updated models in data.js');
