const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');
const { PATHS } = require('./config.cjs');

const publicDir = PATHS.PUBLIC;
const pdfsDir = PATHS.PDFS;

if (!fs.existsSync(pdfsDir)) {
  fs.mkdirSync(pdfsDir, { recursive: true });
}

// Year Group Mappings
const curriculumMapPath = path.join(__dirname, 'curriculum_map.json');
const fullCurriculumMap = JSON.parse(fs.readFileSync(curriculumMapPath, 'utf8'));

// Source/PEEL metadata (auto-generated by diagnose script)
const sourcePeelPath = path.join(publicDir, 'source_peel_metadata.json');
const sourcePeelMeta = fs.existsSync(sourcePeelPath)
  ? JSON.parse(fs.readFileSync(sourcePeelPath, 'utf8'))
  : {};

// Flatten for the overview PDF mapping
const curriculumMap = { ...fullCurriculumMap.KS3, ...fullCurriculumMap.KS4 };

const enquiryPatchMap = {
  the_shoah:
    'How did a modern, civilized nation commit the systematic murder of six million Jewish people?',
  cold_war:
    'Why did the ideological clash between Capitalism and Communism bring the world to the brink of nuclear destruction?',
};

const commonHead = `
    <head>
        <meta charset="UTF-8">
        <title>Meoncross School History Department</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=Outfit:wght@300;400;500;600;700;800&display=swap');
            body { font-family: 'Outfit', sans-serif; color: #1e293b; background: #fff; margin: 0; padding: 0; font-size: 11pt; line-height: 1.5; }
            h1, h2, h3, h4 { font-family: 'Playfair Display', serif; color: #1b365d; margin-top: 0; }
            .cover-page { height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; background: #f8fafc; border: 10px solid #facc15; padding: 40px; box-sizing: border-box; }
            .cover-title { font-size: 48pt; font-weight: 700; color: #1b365d; margin-bottom: 20px; }
            .cover-subtitle { font-size: 24pt; color: #facc15; font-family: 'Outfit', sans-serif; font-weight: 300; text-transform: uppercase; letter-spacing: 2px; }
            .page-break { page-break-before: always; }
            .container { padding: 40px 60px; }
            .header-banner { background: #1b365d; color: #fff; padding: 20px; text-align: center; border-radius: 8px; margin-bottom: 30px; border-bottom: 4px solid #facc15; }
            .header-banner h1 { color: #fff; margin: 0; font-size: 24pt; }
            .year-section { margin-bottom: 40px; }
            .year-title { background: #facc15; color: #1b365d; padding: 10px 20px; border-radius: 4px; font-size: 18pt; margin-bottom: 20px; display: inline-block; font-family: 'Outfit', sans-serif; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }
            .unit-card { border: 1px solid #cbd5e1; border-radius: 8px; padding: 20px; margin-bottom: 20px; background: #f1f5f9; border-left: 5px solid #1b365d; }
            .unit-card h3 { font-size: 16pt; margin-bottom: 10px; color: #1b365d; }
            .unit-card .enquiry { font-weight: 600; color: #b89c30; font-size: 12pt; margin-bottom: 10px; }
            .unit-card .desc { font-size: 11pt; color: #475569; }
            
            /* SOW Styles */
            .sow-unit-container { margin-bottom: 50px; page-break-inside: auto; }
            .sow-unit-header { background: #1b365d; color: #fff; padding: 20px; border-radius: 8px 8px 0 0; border-bottom: 4px solid #facc15; margin-bottom: 20px; }
            .sow-unit-header h2 { color: #fff; margin: 0 0 10px 0; font-size: 22pt; }
            .sow-unit-header p { margin: 0; color: #e2e8f0; font-family: 'Outfit', sans-serif; font-size: 12pt; }
            .primer-box { background: #fef3c7; border: 1px solid #fde68a; border-left: 4px solid #d97706; padding: 15px; border-radius: 4px; margin-bottom: 25px; }
            .primer-box h4 { margin: 0 0 10px 0; color: #92400e; font-family: 'Outfit', sans-serif; text-transform: uppercase; font-size: 10pt; letter-spacing: 1px; }
            
            table { width: 100%; border-collapse: collapse; margin-bottom: 30px; page-break-inside: auto; }
            tr { page-break-inside: avoid; page-break-after: auto; border-bottom: 1px solid #e2e8f0; }
            tr:nth-child(even) { background-color: #f8fafc; }
            th { background: #0f172a; color: #ffffff; text-align: left; padding: 14px; font-family: 'Outfit', sans-serif; font-weight: 600; font-size: 10.5pt; border: none; }
            td { padding: 14px; border: none; vertical-align: top; font-size: 10pt; color: #334155; }
            
            .lesson-num { font-weight: 700; color: #1b365d; white-space: nowrap; }
            .lesson-title { font-weight: 700; margin-bottom: 5px; color: #1e40af; font-size: 11pt; }
            
            .hinge-question { color: #b91c1c; font-style: italic; font-weight: 600; margin-top: 8px; display: block; border-left: 2px solid #ef4444; padding-left: 8px; }
            
            ul.obj-list { margin: 5px 0 0 0; padding-left: 20px; }
            ul.obj-list li { margin-bottom: 5px; }
            
            .task-list { margin: 0; padding-left: 20px; color: #334155; }
            .task-list li { margin-bottom: 4px; }
            
        </style>
    </head>
`;

function generateOverviewHTML(db) {
  let html = `<!DOCTYPE html><html lang="en">${commonHead}<body>`;

  html += `
        <div class="cover-page">
            <div class="cover-title">Meoncross School History Department</div>
            <div class="cover-subtitle">5-Year Curriculum Overview (2026-2027)</div>
            <div style="margin-top: 40px; font-size: 14pt; color: #475569;">Key Stage 3 & 4 (Years 7 - 11)</div>
        </div>
        <div class="page-break"></div>
        <div class="container">
            <div class="header-banner">
                <h1>History Curriculum Map</h1>
            </div>
    `;

  for (const [yearGroup, unitIds] of Object.entries(curriculumMap)) {
    html += `<div class="year-section"><div class="year-title">${yearGroup}</div>`;
    for (const uid of unitIds) {
      const unitData = db[uid]?.data;
      if (!unitData) continue;

      const title = unitData.title || uid;
      let enquiry = unitData.enquiry || unitData.enquiry_question || '';
      if (enquiryPatchMap[uid]) {
        enquiry = enquiryPatchMap[uid];
      }

      const desc =
        unitData.desc ||
        (unitData.lessons && unitData.lessons.length
          ? 'An in-depth study featuring ' + unitData.lessons.length + ' lessons.'
          : '');

      html += `
                <div class="unit-card">
                    <h3>${title}</h3>
                    ${enquiry ? `<div class="enquiry"><strong style="color:#1b365d">Enquiry:</strong> ${enquiry}</div>` : ''}
                    <div class="desc">${desc}</div>
                </div>
            `;
    }
    html += `</div>`;
  }
  html += `</div></body></html>`;

  const outPath = path.join(publicDir, 'curriculum_overview.html');
  fs.writeFileSync(outPath, html);
  return outPath;
}

function generateSOWHTML(db, yearGroup, unitIds) {
  let html = `<!DOCTYPE html><html lang="en">${commonHead}<body>`;

  html += `
        <div class="cover-page">
            <div class="cover-title">Meoncross School History Department</div>
            <div class="cover-subtitle">${yearGroup} Scheme of Work (2026-2027)</div>
            <div style="margin-top: 40px; font-size: 14pt; color: #475569;">Teacher Companion Guide</div>
        </div>
    `;

  html += `
        <div class="page-break"></div>
        <div class="container" style="padding-top: 60px;">
            <div class="header-banner">
                <h1>Curriculum Evaluation & Pedagogical Strengths</h1>
            </div>
            
            <div style="margin-bottom: 30px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 10px;">Strengths & Commendable Practices</h2>
                
                <h3 style="color: #1e40af; margin-bottom: 5px;">Strong Local History Connections</h3>
                <p style="margin-top: 0;">Integrating local context into national and global events serves as a fantastic pedagogical hook. Mentions of the "Fareham ironmaster" in the Industrialisation unit and the profound impact of the "Lost Generation" on the "village of Stubbington" directly ground the history for our pupils. This makes the narrative tangible and relevant to their lived environment, fostering deeper engagement.</p>
                
                <h3 style="color: #1e40af; margin-bottom: 5px;">Thematic GCSE Preparation</h3>
                <p style="margin-top: 0;">The inclusion of <em>Water and Sanitation Through Time</em> acts as an excellent, low-stakes conceptual primer for the Edexcel GCSE <em>Medicine Through Time</em> thematic study. It introduces pupils to broad chronology (Roman to Industrial) and core concepts of change, continuity, and significance long before they hit the rigor of GCSE, ensuring a seamless transition.</p>

                <h3 style="color: #1e40af; margin-bottom: 5px;">Solid Chronological Foundation</h3>
                <p style="margin-top: 0;">By correctly sequencing the curriculum to transition from the broad sweep of <em>Water and Sanitation</em> directly into <em>Medieval England (1066-1485)</em>, pupils gain the vital contextual bedrock (feudalism, Church power, the monarchy) needed to understand the complex religious and power shifts of the Early Modern era.</p>

                <h3 style="color: #1e40af; margin-bottom: 5px;">De-centering the British Narrative</h3>
                <p style="margin-top: 0;">Starting with, or heavily featuring, the <em>History of Australia</em> and framing the Early Modern unit as <em>Global Encounters (1450–1750)</em> is a very modern, progressive approach. It intentionally moves away from the traditional, purely anglocentric Tudor/Stuart narrative to look critically at the mechanics of early empire, global trade, and the Transatlantic Slave Trade, creating a more diverse and inclusive curriculum.</p>
                
                <h3 style="color: #1e40af; margin-bottom: 5px;">Deep Dive on World War I</h3>
                <p style="margin-top: 0;">Splitting the Great War into two distinct units (Causes vs. The War) allows for rigorous historical debate (e.g., the Anglo-German naval race, alliance systems). This ensures pupils aren't just learning the "mud and blood" narrative, but are actively grappling with complex geopolitical causation.</p>
            </div>

            <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-left: 5px solid #d97706; padding: 20px; border-radius: 4px;">
                <h2 style="color: #92400e; margin-top: 0; border-bottom: 1px solid #fcd34d; padding-bottom: 10px;">Points for Improvement for 2026/2027</h2>
                
                <h4 style="margin-bottom: 5px; color: #1b365d;">1. Overweighting the 20th Century</h4>
                <p style="margin-top: 0; font-size: 10pt;">Currently, there are two whole units dedicated to the Great War, plus units mapped out for the Second World War, the Shoah, the Cold War, and Post-War Britain. While vital, this risks creating a "modern-heavy" curriculum, sometimes at the expense of early world history.</p>
                
                <h4 style="margin-bottom: 5px; color: #1b365d;">2. Pre-1450 Global Diversity</h4>
                <p style="margin-top: 0; font-size: 10pt;">The curriculum would benefit from a deep dive into non-European civilizations before European contact. Exploring the Islamic Golden Age, the Mali Empire, or the Silk Roads <em>before</em> looking at European "Global Encounters" in 1450 would give pupils a much more balanced view of global history, rather than encountering diverse cultures primarily through the lens of European colonization.</p>
            </div>
            ${yearGroup === 'Year 9' ? `
            <div style="margin-top: 30px; background: #eff6ff; border: 1px solid #bfdbfe; border-left: 5px solid #3b82f6; padding: 20px; border-radius: 4px;">
                <h2 style="color: #1e3a8a; margin-top: 0;">Notice on Year 9 Curriculum Development</h2>
                <p style="margin: 0; color: #1e40af; font-weight: 600; font-size: 11pt;">Please note that the Year 9 units are currently incomplete. These units (including The Second World War, The Shoah, and The Cold War) will be fully built and mapped out over the next few months to ensure they meet our high pedagogical standards.</p>
            </div>
            ` : ''}
        </div>

        <div class="page-break"></div>
        <div class="container" style="padding-top: 60px;">
            <div class="header-banner">
                <h1>Evidence of Impact & Curriculum Mapping</h1>
            </div>
            
            <div style="margin-bottom: 30px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 10px;">1. Local Context & Coastal Connections</h2>
                <p style="margin-top: 0; font-size: 11pt; color: #475569;">As a coastal school, our curriculum is intentionally designed to root global and national historical events in the maritime geography and lived environment of our pupils.</p>
                <ul style="color: #334155; font-size: 10.5pt; line-height: 1.6;">
                    <li style="margin-bottom: 8px;"><strong>Oceanic Voyages & Penal Colonies:</strong> The Year 8 Australia unit is deeply tied to maritime history, the brutality of ocean voyages, and the establishment of coastal settlements like Botany Bay.</li>
                    <li style="margin-bottom: 8px;"><strong>Maritime Trade & Naval Dominance:</strong> Our Early Modern World unit explicitly links global power to mastery of the oceans, naval exploration, and control of the Transatlantic Slave Trade.</li>
                    <li style="margin-bottom: 8px;"><strong>The Anglo-German Naval Race:</strong> The Year 8 Great War unit features a dedicated study on HMS <em>Dreadnought</em>, proving how a contest for control of the sea directly sparked global conflict.</li>
                    <li style="margin-bottom: 8px;"><strong>Local Coastal Impact:</strong> We explicitly study the "Fareham ironmaster" and the impact of the "Lost Generation" on the coastal village of Stubbington, bridging global events with local geography.</li>
                </ul>
            </div>

            <div style="margin-bottom: 30px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 10px;">2. Historical Skills Progression</h2>
                <p style="margin-top: 0; font-size: 11pt; color: #475569;">Our curriculum ensures rigorous, sequential development of disciplinary thinking from Year 7 through to Year 9, preparing pupils for GCSE demands.</p>
                <ul style="color: #334155; font-size: 10.5pt; line-height: 1.6;">
                    <li style="margin-bottom: 8px;"><strong>Source Utility:</strong> Moves from basic comprehension in Year 7 to evaluating provenance, motive, and audience (e.g., analyzing WWI propaganda and recruitment posters) in Year 8.</li>
                    <li style="margin-bottom: 8px;"><strong>Historical Interpretations:</strong> Progresses from identifying differing views to critically evaluating opposing academic debates (e.g., assessing modern vs. traditional interpretations of the Magna Carta or the 'Lions led by Donkeys' WWI debate) using contextual knowledge.</li>
                    <li style="margin-bottom: 8px;"><strong>Argumentation (PEEL):</strong> Pupils progress from supported, structured paragraphs to independent, multi-causal essays evaluating 'significance' and 'change over time'.</li>
                    <li style="margin-bottom: 8px;"><strong>Causation:</strong> Transitions from identifying simple triggers to categorizing long-term vs. short-term causes (e.g., the complex alliance systems and naval race of 1914).</li>
                </ul>
            </div>

            <div style="margin-bottom: 30px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 10px;">3. Diversity, Equity & Representation</h2>
                <p style="margin-top: 0; font-size: 11pt; color: #475569;">We are committed to delivering a curriculum that de-centers traditional anglocentric narratives, elevating the voices of the marginalized and giving pupils a truly global perspective.</p>
                <ul style="color: #334155; font-size: 10.5pt; line-height: 1.6;">
                    <li style="margin-bottom: 8px;"><strong>Indigenous Perspectives:</strong> The History of Australia unit critically examines the impact of British settlement on Indigenous peoples, moving beyond the traditional 'discovery' narrative.</li>
                    <li style="margin-bottom: 8px;"><strong>Enslaved Voices:</strong> The Early Modern World unit focuses on the mechanics of the Transatlantic Slave Trade and actively highlights how enslaved Africans resisted.</li>
                    <li style="margin-bottom: 8px;"><strong>The 'Ordinary' Voice:</strong> The Industrialisation unit explores how ordinary working-class people, rather than just monarchs, fought for a voice and the expansion of democracy.</li>
                    <li style="margin-bottom: 8px;"><strong>The Forgotten Armies:</strong> The Great War unit deliberately questions how much of a 'World' war it was by uncovering the forgotten contributions of the Empire's troops.</li>
                    <li style="margin-bottom: 8px;"><strong>Experiential Learning (Ypres Trip):</strong> The upcoming Year 9 Battlefields Trip to Ypres provides an invaluable opportunity for pupils to walk the ground of the Great War, cementing their classroom learning with powerful lived experience.</li>
                </ul>
            </div>

            <div style="margin-bottom: 30px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 10px;">4. Pedagogical Strengths (SEND & Accessibility)</h2>
                <p style="margin-top: 0; font-size: 11pt; color: #475569;">The integrated use of the Meoncross School History Department app alongside printed A4 workbooks and textbooks is deliberately designed to provide maximum support for SEND pupils:</p>
                <ul style="color: #334155; font-size: 10.5pt; line-height: 1.6;">
                    <li style="margin-bottom: 8px;"><strong>Cognitive Offloading:</strong> The combination of guided workbooks directly matched to structured digital tasks significantly reduces working memory strain, allowing pupils to focus entirely on historical thinking.</li>
                    <li style="margin-bottom: 8px;"><strong>Dual Coding & Scaffolding:</strong> The app utilizes consistent visual layouts, dual-coded images for vocabulary, and highly structured scaffolding (like sentence starters and PEEL frameworks) to support pupils with dyslexia or processing needs.</li>
                    <li style="margin-bottom: 8px;"><strong>Multimodal Engagement:</strong> By seamlessly transitioning between interactive digital tasks and focused reading from printed textbooks, the curriculum caters to diverse learning profiles while preventing screen fatigue.</li>
                </ul>
            </div>

            <div style="margin-bottom: 30px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 10px;">5. Substantive Concept Mapping</h2>
                <p style="margin-top: 0; font-size: 11pt; color: #475569;">In line with modern KS3 history pedagogy, we actively track and weave substantive concepts ("big ideas" like Empire, Religion, and Power) across different periods. Rather than teaching these as isolated definitions, pupils build complex mental schemas by encountering them in varied contexts—from the power of the Medieval Church, through to the ideological clashes of the Cold War.</p>
            </div>

            <div style="margin-bottom: 30px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 10px;">6. "Worldbuilding" & Cultural Literacy</h2>
                <p style="margin-top: 0; font-size: 11pt; color: #475569;">Before pupils can effectively tackle abstract disciplinary concepts (such as causation or source utility), they require a rich "picture of the past". Our curriculum deliberately immerses pupils in the sensory and lived experiences of historical periods—such as daily life in a medieval village or the harsh realities of a WW1 trench—ensuring a secure cultural and chronological grounding prior to high-level analysis.</p>
            </div>
        </div>
    `;

  for (const uid of unitIds) {
    const unitData = db[uid]?.data;
    if (!unitData) continue;

    const title = unitData.title || uid;
    let enquiry = unitData.enquiry || unitData.enquiry_question || '';
    if (enquiryPatchMap[uid]) {
      enquiry = enquiryPatchMap[uid];
    }

    // Fix Vocab Bleed: Reset the vocabulary variable to empty before parsing each new unit
    let vocabulary = [];
    if (unitData.glossary && Array.isArray(unitData.glossary)) {
      vocabulary = unitData.glossary;
    }

    html += `<div class="container sow-unit-container">`;
    html += `
                <div class="sow-unit-header">
                    <h2>${title}</h2>
                    <p><strong>${yearGroup}</strong> ${enquiry ? '| ' + enquiry : ''}</p>
                </div>
            `;

    if (unitData.teacher_notes && unitData.teacher_notes.primer) {
      html += `
                    <div class="primer-box">
                        <h4>Pedagogical Goals & Primer</h4>
                        <div>${unitData.teacher_notes.primer}</div>
                    </div>
                `;
    }

    if (['cold_war', 'second_world_war', 'the_shoah'].includes(uid)) {
      html += `
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 9pt;">
                        <thead>
                            <tr>
                                <th style="width: 25%">Lesson Number & Title</th>
                                <th style="width: 30%">Learning Objectives</th>
                                <th style="width: 45%">Core Assessment & Tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="3" style="text-align: center; font-style: italic; color: #64748b; font-size: 14pt; padding: 20px;">Unit in Development – Content TBC</td>
                            </tr>
                        </tbody>
                    </table>
                `;
    } else if (unitData.lessons && unitData.lessons.length > 0) {
      html += `
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 9pt;">
                        <thead>
                            <tr>
                                <th style="width: 25%">Lesson Number & Title</th>
                                <th style="width: 30%">Learning Objectives</th>
                                <th style="width: 45%">Core Assessment & Tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                `;

      unitData.lessons.forEach((lesson, idx) => {
        // Extract Learning Objectives dynamically
        let objsHTML = '';
        let hinge = '';

        if (
          lesson.learning_objectives &&
          Array.isArray(lesson.learning_objectives) &&
          lesson.learning_objectives.length > 0
        ) {
          // Flat array of strings (Year 8+ format)
          objsHTML =
            `<ul class="obj-list">` +
            lesson.learning_objectives.map((o) => `<li>${o}</li>`).join('') +
            `</ul>`;
        } else if (
          lesson.learning_objectives &&
          Array.isArray(lesson.learning_objectives.scaffolded) &&
          lesson.learning_objectives.scaffolded.length > 0
        ) {
          // Nested object with scaffolded array (Year 7 / legacy format)
          objsHTML =
            `<ul class="obj-list">` +
            lesson.learning_objectives.scaffolded.map((o) => `<li>${o}</li>`).join('') +
            `</ul>`;
        } else if (lesson.intent && Array.isArray(lesson.intent) && lesson.intent.length > 0) {
          objsHTML =
            `<ul class="obj-list">` + lesson.intent.map((o) => `<li>${o}</li>`).join('') + `</ul>`;
        } else if (lesson.learning_objective) {
          objsHTML = `<ul class="obj-list"><li>${lesson.learning_objective}</li></ul>`;
        } else {
          objsHTML = '<span style="color:#94a3b8; font-style:italic;">Historical Enquiry</span>';
        }

        // Extract Hinge Question from teacher_notes if available
        if (unitData.teacher_notes && unitData.teacher_notes.objectives) {
          const lessonObjs = unitData.teacher_notes.objectives.filter(
            (o) =>
              (lesson.learning_objective && o.objective === lesson.learning_objective) ||
              (lesson.learning_objectives &&
                lesson.learning_objectives.scaffolded &&
                lesson.learning_objectives.scaffolded.includes(o.objective)) ||
              (lesson.title && o.objective && o.objective.includes(lesson.title.split(':')[0])) ||
              (lesson.title && lesson.title.includes(o.objective)),
          );
          const hingeObj = lessonObjs.find((o) => o.question);
          if (hingeObj) hinge = hingeObj.question;
        }

        // Extract Disciplinary Focus
        let discFocus =
          lesson.disciplinary_concept ||
          lesson.disciplinary_focus ||
          lesson.historical_concept ||
          '';
        if (!discFocus) {
           // Check source_tasks from lesson data OR from metadata fallback
           const metaLesson = sourcePeelMeta[uid]?.lessons?.[idx];
           const hasSourceTasks = lesson.source_tasks ||
             (metaLesson && metaLesson.source_task_count > 0) ||
             (lesson.formative_assessment && lesson.formative_assessment.type === 'source_utility');
           
           if (hasSourceTasks)
             discFocus = 'Source Utility';
          else if (lesson.peel_paragraph) discFocus = 'Historical Argumentation';
          else if (lesson.exam_practice && lesson.exam_practice.length > 0)
            discFocus = 'Historical Enquiry & Exam Skills';
          else {
            // Bespoke labels to avoid repetitive "Historical Knowledge & Understanding"
            const bespokeLabels = {
              medieval_england: "Medieval Society & Power",
              industrialisation_and_empire: "Empire & Societal Shift",
              great_war: "Geopolitical Context",
              great_war_part2: "Modern Warfare Dynamics",
              water_and_sanitation: "Chronological Frameworks",
              early_modern_world: "Global Trade & Colonisation",
              australia: "Indigenous Encounters & Settlement"
            };
            discFocus = bespokeLabels[uid] || 'Knowledge & Schema Building';
          }
        }

        // Extract Core Assessment & Tasks
        let tasks = [];

        // Formative Assessments
        if (lesson.formative_assessment) {
          const faArray = Array.isArray(lesson.formative_assessment)
            ? lesson.formative_assessment
            : [lesson.formative_assessment];
          faArray.forEach((fa) => {
            if (fa.question) {
              tasks.push(`Assessment: ${fa.question}`);
            } else if (fa.type === 'source_utility') {
              tasks.push(`Source Utility Analysis`);
            } else {
              tasks.push(`Formative Assessment Activity`);
            }
          });
        }

        // PEEL Paragraph
        if (lesson.peel_paragraph) {
          if (lesson.peel_paragraph.question) {
            let concept = 'Argumentation';
            if (discFocus.toLowerCase().includes('causation')) concept = 'Causation';
            else if (discFocus.toLowerCase().includes('change')) concept = 'Change & Continuity';
            else if (discFocus.toLowerCase().includes('significance')) concept = 'Significance';

            tasks.push(`PEEL Paragraph (${concept}): ${lesson.peel_paragraph.question}`);
          } else {
            tasks.push(`PEEL Paragraph Analysis`);
          }
        }

        // GCSE Exam Practice
        if (lesson.exam_practice && lesson.exam_practice.length > 0) {
          lesson.exam_practice.forEach((ep) => {
            if (ep.question) {
              tasks.push(`Exam Practice (${ep.marks} marks): ${ep.question}`);
            } else if (ep.marks) {
              tasks.push(`GCSE Exam Practice (${ep.marks} marks)`);
            } else {
              tasks.push(`GCSE Exam Practice`);
            }
          });
        }

        // Comprehension & Sources
        if (lesson.comprehension && lesson.comprehension.length > 0) {
          const quizLabels = ['Knowledge Recall Quiz', 'Comprehension Activity', 'Core Knowledge Check', `Recall Quiz (${lesson.comprehension.length} questions)`];
          tasks.push(quizLabels[idx % quizLabels.length]);
        }

        // Interpretations
        if (lesson.historical_interpretations) {
          tasks.push(`Historical Interpretations: ${lesson.historical_interpretations.title || 'Evaluating Historians'}`);
        }

        // Extract heavy tasks from narrative_blocks
        // Skip if formative_assessment already provided a clean assessment question
        const hasCleanAssessment =
          lesson.formative_assessment &&
          (lesson.formative_assessment.question ||
            (Array.isArray(lesson.formative_assessment) &&
              lesson.formative_assessment.some((fa) => fa.question)));

        if (!hasCleanAssessment && lesson.narrative_blocks) {
          lesson.narrative_blocks.forEach((block) => {
            if (block.tasks) {
              block.tasks.forEach((t) => {
                if (t.type === 'extended_writing' || t.type === 'peel_paragraph') {
                  let q = t.question || t.instruction || 'Extended Writing';
                  // Sanitize: strip HTML tags, newline escapes, and limit length
                  q = q
                    .replace(/<[^>]+>/g, '')
                    .replace(/\\n/g, ' ')
                    .split('\n')[0]
                    .replace(/^Task\s+\d+:\s*/i, '')
                    .trim();
                  if (q.length > 150) q = q.substring(0, 147) + '...';

                  let concept = 'Argumentation';
                  if (discFocus.toLowerCase().includes('causation')) concept = 'Causation';
                  else if (discFocus.toLowerCase().includes('change'))
                    concept = 'Change & Continuity';
                  else if (discFocus.toLowerCase().includes('significance'))
                    concept = 'Significance';
                  else if (discFocus.toLowerCase().includes('utility')) concept = 'Source Utility';

                  tasks.push(`PEEL Paragraph (${concept}): ${q}`);
                } else if (t.type === 'creative_writing') {
                  let q = t.question || t.instruction || 'Creative Writing';
                  q = q
                    .replace(/<[^>]+>/g, '')
                    .replace(/\\n/g, ' ')
                    .split('\n')[0]
                    .replace(/^Task\s+\d+:\s*/i, '')
                    .trim();
                  if (q.length > 150) q = q.substring(0, 147) + '...';
                  tasks.push(`Creative Task: ${q}`);
                }
              });
            }
          });
        }

        // Source tasks from data.js or metadata fallback
        const metaL = sourcePeelMeta[uid]?.lessons?.[idx];
        const hasSourceTasks = lesson.source_tasks?.length > 0 || (metaL && metaL.source_task_count > 0);
        const hasPeelTasks = (metaL && metaL.peel_task_count > 0);

        if (hasSourceTasks) {
          const sourceLabels = ['Evaluating Primary Evidence', 'Interrogating Historical Sources', 'Primary Source Analysis', 'Working with Contemporary Accounts'];
          tasks.push(sourceLabels[idx % sourceLabels.length]);
        }
        if (hasPeelTasks) {
          const peelLabels = ['Extended Writing (PEEL)', 'Structured Paragraph', 'Exam Practice Writing', 'Analytical Essay'];
          tasks.push(peelLabels[idx % peelLabels.length]);
        }

        let tasksHTML =
          tasks.length > 0
            ? `<ul class="task-list">` +
              Array.from(new Set(tasks))
                .map((t) => `<li>${t}</li>`)
                .join('') +
              `</ul>`
            : '<span style="color:#94a3b8; font-style:italic;">Narrative exploration and class discussion</span>';

        html += `
                        <tr>
                            <td>
                                <div class="lesson-num">Lesson ${idx + 1}</div>
                                <div class="lesson-title">${lesson.title || 'Untitled Lesson'}</div>
                            </td>
                            <td>
                                ${objsHTML}
                                ${hinge ? `<span class="hinge-question">Hinge Q: ${hinge}</span>` : ''}
                            </td>
                            
                            <td>
                                ${tasksHTML}
                            </td>
                        </tr>
                    `;
      });

      html += `</tbody></table>`;
    }

    if (vocabulary && vocabulary.length > 0) {
      const words = vocabulary
        .map((v) => v.term || v.word || v.keyword)
        .filter((w) => w && w !== 'undefined')
        .map((w) => w.trim());

      const uniqueWords = Array.from(new Set(words));

      if (uniqueWords.length > 0) {
        html += `
                        <div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 6px; margin-top: 30px; margin-bottom: 30px;">
                            <strong style="color: #0f172a; font-family: 'Outfit', sans-serif;">Key Vocabulary:</strong> 
                            <span style="color: #475569;">${uniqueWords.join(', ')}</span>
                        </div>
                    `;
      }
    }

    html += `</div>`;
  }

  html += `</body></html>`;
  const outPath = path.join(publicDir, 'scheme_of_work.html');
  fs.writeFileSync(outPath, html);
  return outPath;
}

(async () => {
  const dbPath = path.join(publicDir, 'database.json');
  const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

  // Dynamically enrich the db with real data.js imports to ensure we don't miss nested arrays (like exam_practice, intent, peel_paragraph)
  for (const [yearGroup, unitIds] of Object.entries(curriculumMap)) {
    for (const uid of unitIds) {
      if (['cold_war', 'second_world_war', 'the_shoah'].includes(uid)) {
        continue; // Do not parse their data.js files
      }
      const dataPath = path.join(publicDir, 'units', uid, 'data.js');
      if (fs.existsSync(dataPath)) {
        try {
          // Dynamically import the ES module
          const dataModule = await import(require('url').pathToFileURL(dataPath).href);
          if (dataModule && dataModule.unitData) {
            if (!db[uid]) db[uid] = { data: {} };
            if (dataModule.unitData.lessons) {
              db[uid].data.lessons = dataModule.unitData.lessons;
            }
            if (dataModule.unitData.teacher_notes) {
              db[uid].data.teacher_notes = dataModule.unitData.teacher_notes;
            }
          }
        } catch (e) {
          console.error('Error importing data.js for', uid, e);
        }
      }
    }
  }

  console.log('Generating HTML templates...');
  const overviewHtmlPath = generateOverviewHTML(db);

  console.log('Launching Puppeteer to create PDFs...');
  const browser = await puppeteer.launch({ headless: 'new' });

  // 1. Generate Overview PDF
  console.log('Rendering Curriculum Overview PDF...');
  const page1 = await browser.newPage();
  await page1.goto(require('url').pathToFileURL(overviewHtmlPath).href, {
    waitUntil: 'networkidle0',
  });
  const overviewPdfPath = path.join(pdfsDir, 'whole_school_curriculum_overview.pdf');
  await page1.pdf({
    path: overviewPdfPath,
    format: 'A4',
    printBackground: true,
    displayHeaderFooter: true,
    headerTemplate: '<div></div>',
    footerTemplate:
      '<div style="font-size:10px; width:100%; text-align:center; font-family: sans-serif; color: #94a3b8;">Meoncross School History Department - Curriculum Overview | Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>',
    margin: { top: '15mm', right: '15mm', bottom: '25mm', left: '15mm' },
  });
  console.log('✅ Success! Overview PDF saved to: ' + overviewPdfPath);

  // 2. Generate SOW PDFs per Year Group
  for (const [stage, stageMap] of Object.entries(fullCurriculumMap)) {
    for (const [yearGroup, unitIds] of Object.entries(stageMap)) {
      const safeYearName = yearGroup.toLowerCase().replace(' ', '_');
      const htmlPath = generateSOWHTML(db, yearGroup, unitIds);

      console.log(`Rendering ${yearGroup} Scheme of Work PDF...`);
      const page = await browser.newPage();
      await page.goto(require('url').pathToFileURL(htmlPath).href, { waitUntil: 'networkidle0' });

      // Adjust layout for standard portrait width
      const pdfPath = path.join(pdfsDir, `${safeYearName}_sow.pdf`);
      await page.pdf({
        path: pdfPath,
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `<div style="font-size:10px; width:100%; text-align:center; font-family: sans-serif; color: #94a3b8;">Meoncross School History Department - ${yearGroup} Scheme of Work | Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>`,
        margin: { top: '15mm', right: '15mm', bottom: '25mm', left: '15mm' },
      });
      console.log(`✅ Success! ${yearGroup} Scheme of Work PDF saved to: ` + pdfPath);
      await page.close();
    }
  }

  await browser.close();
})();
