const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');
const { PATHS } = require('./config.cjs');

const publicDir = PATHS.PUBLIC;
const pdfsDir = PATHS.PDFS;

if (!fs.existsSync(pdfsDir)) {
  fs.mkdirSync(pdfsDir, { recursive: true });
}

// Year Group Mappings
const curriculumMapPath = path.join(__dirname, 'curriculum_map.json');
const fullCurriculumMap = JSON.parse(fs.readFileSync(curriculumMapPath, 'utf8'));

// Source/PEEL metadata (auto-generated by diagnose script)
const sourcePeelPath = path.join(publicDir, 'source_peel_metadata.json');
const sourcePeelMeta = fs.existsSync(sourcePeelPath)
  ? JSON.parse(fs.readFileSync(sourcePeelPath, 'utf8'))
  : {};

// Flatten for the overview PDF mapping
const curriculumMap = { ...fullCurriculumMap.KS3, ...fullCurriculumMap.KS4 };

const enquiryPatchMap = {
  the_shoah:
    'How did a modern, civilized nation commit the systematic murder of six million Jewish people?',
  cold_war:
    'Why did the ideological clash between Capitalism and Communism bring the world to the brink of nuclear destruction?',
};

const unitCurriculumOutlines = {
  the_shoah: [
    {
      title: 'Pre-War Jewish Life & Roots of Antisemitism',
      obj: 'Analyse pre-1933 Jewish European diversity; differentiate religious vs Nazi racial antisemitism.',
      hinge:
        'Why did the Nazis shift from traditional prejudice to pseudoscientific racial ideology?',
      evidence:
        'Pre-1933 Jewish community archives & family photographs; 19th-century European pseudoscientific racial charts.',
      debate:
        'Functionalist vs Intentionalist origins: Long-standing European prejudice vs Hitler’s ideological radicalism.',
      assessment:
        '[8 Marks] Explain the difference between traditional religious anti-Judaism and Nazi racial antisemitism.',
    },
    {
      title: 'Escalation of Nazi Persecution (1933–1939)',
      obj: 'Trace legal and social exclusion from 1933 anti-Jewish decrees to the Nuremberg Laws and Kristallnacht.',
      hinge: 'How did state decrees and street violence work together to isolate German Jews?',
      evidence:
        'Official 1935 Nuremberg Laws legislation text; Contemporary Berliner Tageblatt reports on the 1938 Kristallnacht pogrom.',
      debate:
        'Cumulative radicalisation: Grassroots SA street violence vs top-down bureaucratic and judicial exclusion.',
      assessment:
        '[PEEL Paragraph] Explain why the Nuremberg Laws marked a decisive turning point in Nazi persecution.',
    },
    {
      title: 'War, Ghettos & The Einsatzgruppen (1939–1941)',
      obj: 'Examine sealed ghettos in occupied Poland and the mass shootings of the mobile Einsatzgruppen.',
      hinge: 'How did the invasion of the USSR mark a radical shift toward systematic murder?',
      evidence:
        'Emanuel Ringelblum’s Warsaw Ghetto underground archive (Oyneg Shabes); Einsatzgruppen execution field reports.',
      debate:
        'Christopher Browning vs Daniel Goldhagen debate: Peer conformity in "Ordinary Men" vs eliminationist antisemitism.',
      assessment:
        '[8 Marks] How useful are Warsaw Ghetto diaries for investigating civilian survival and resistance?',
    },
    {
      title: 'The "Final Solution" & Extermination Camps (1942–1945)',
      obj: 'Assess the Wannsee Conference and the industrialised murder network at Auschwitz-Birkenau.',
      hinge: 'What differentiated Nazi extermination camps from conventional wartime prisons?',
      evidence:
        '1942 Wannsee Conference Protocol (Heydrich); Auschwitz-Birkenau railway transport manifests and blueprints.',
      debate:
        'Hannah Arendt’s "Banality of Evil" and state bureaucracy vs deliberate ideological fanaticism.',
      assessment:
        '[Evaluative Essay] Explain why the Wannsee Conference accelerated the transition to extermination camps.',
    },
    {
      title: 'Jewish Resistance, Liberation & Legacy',
      obj: 'Investigate armed/spiritual resistance (Warsaw Uprising); evaluate the Nuremberg Trials and legacy.',
      hinge:
        'How do historians balance intentionalist vs functionalist explanations for the Holocaust?',
      evidence:
        'Sobibor and Treblinka prisoner revolt testimonies; 1945–46 Nuremberg Military Tribunal indictment documents.',
      debate:
        'Historiographical verdict: The "twisted road" to Auschwitz vs deliberate long-term master planning.',
      assessment:
        '[12-Mark Essay] To what extent was the "Final Solution" planned from the inception of the Nazi regime?',
    },
  ],
  cold_war: [
    {
      title: 'Collapse of the Grand Alliance (1943–1945)',
      obj: 'Compare Capitalism vs Communism; analyse superpower tensions at Tehran, Yalta, and Potsdam.',
      hinge: 'Was Cold War hostility inevitable once Nazi Germany was defeated?',
      evidence:
        'Tehran, Yalta, and Potsdam conference minutes (1943–45); Winston Churchill’s 1946 "Iron Curtain" speech transcript.',
      debate:
        'Orthodox (Soviet expansionism) vs Revisionist (US atomic diplomacy) vs Post-Revisionist (mutual misperception).',
      assessment:
        '[8 Marks] Explain why tensions between the Grand Alliance increased following the 1945 Potsdam Conference.',
    },
    {
      title: 'Containment & Crisis: Truman to Berlin (1947–1949)',
      obj: 'Explain the Truman Doctrine, Marshall Aid, and the causes and outcome of the Berlin Blockade.',
      hinge: 'Why did Stalin choose a blockade rather than military invasion of West Berlin?',
      evidence:
        'President Truman’s Address to Congress (1947); Soviet Ministry of Foreign Affairs cables on the Berlin Blockade (1948).',
      debate:
        'Containment policy: Defensive national security perimeter vs aggressive imperialist economic expansion.',
      assessment:
        '[8 Marks] Explain the importance of the Berlin Airlift (1948–49) for Cold War superpower relations.',
    },
    {
      title: 'Nuclear Arms Race & Cuban Missile Crisis (1950–1962)',
      obj: 'Evaluate Mutually Assured Destruction (MAD); analyse Kennedy and Khrushchev during October 1962.',
      hinge: 'Which leader made the decisive concession that averted nuclear war in 1962?',
      evidence:
        'CIA U-2 reconnaissance aerial photography of San Cristóbal (Oct 1962); Declassified correspondence between JFK and Khrushchev.',
      debate:
        'Crisis decision-making: Rational diplomatic conflict management vs near-fatal military miscalculation and luck.',
      assessment:
        '[12-Mark Essay] Explain why the Cuban Missile Crisis was resolved without direct military conflict.',
    },
    {
      title: 'Détente & Proxy Conflicts (1963–1979)',
      obj: 'Examine superpower treaties (SALT I, Helsinki) and proxy war dynamics (Vietnam, Afghanistan).',
      hinge: 'Did Détente represent genuine peace or tactical delay by the superpowers?',
      evidence:
        'Strategic Arms Limitation Treaty (SALT I) text (1972); Helsinki Final Act agreements on European human rights (1975).',
      debate:
        'Détente: Genuine international stabilization breakthrough vs cynical tactical breathing space during the arms race.',
      assessment:
        '[8 Marks] Explain one consequence of the Helsinki Accords (1975) for international diplomacy.',
    },
    {
      title: 'Fall of the Berlin Wall & End of USSR (1980–1991)',
      obj: 'Analyse Gorbachev’s Glasnost and Perestroika; explain the collapse of the Berlin Wall and the USSR.',
      hinge:
        'Did internal economic failure or Western pressure cause the fall of Soviet Communism?',
      evidence:
        'Mikhail Gorbachev’s Perestroika reform addresses (1986); International television news dispatches on the Berlin Wall (Nov 1989).',
      debate:
        'Triumphalist (Reagan defense buildup) vs Structuralist (systemic Soviet economic bankruptcy) historiographical debate.',
      assessment:
        '[16-Mark Essay] "Internal economic failure was the main reason for the collapse of Soviet rule." How far do you agree?',
    },
  ],
  second_world_war: [
    {
      title: 'Outbreak of Global Conflict & Blitzkrieg (1939–1940)',
      obj: 'Examine the invasion of Poland and the fall of France; assess the evacuation at Dunkirk.',
      hinge: 'How did German Blitzkrieg tactics overcome French defensive fortifications?',
      evidence:
        'Wehrmacht tactical operational maps (Fall Gelb, 1940); Churchill’s wartime parliamentary address ("Fight on the beaches").',
      debate:
        'Military historiography: Revolutionary tactical doctrine (Blitzkrieg) vs Allied doctrinal rigidity and French command paralysis.',
      assessment:
        '[PEEL Paragraph] Explain why the evacuation of Dunkirk was portrayed as a psychological victory in Britain.',
    },
    {
      title: 'The Battle of Britain & The Blitz (1940–1941)',
      obj: 'Investigate the RAF’s defense in the Battle of Britain; evaluate civilian morale under the Blitz.',
      hinge: 'Why did the Luftwaffe fail to establish air superiority over southern England?',
      evidence:
        'Fighter Command Dowding System radar interception logs; Mass-Observation civilian diaries during the London and Portsmouth Blitz.',
      debate:
        'The "Myth of the Blitz": Unbroken civilian unity and resilience vs suppressed industrial strikes and social panic.',
      assessment:
        '[8 Marks] How useful are Mass-Observation diaries for investigating civilian morale during the 1940 Blitz?',
    },
    {
      title: 'Turning Points: Barbarossa & Stalingrad (1941–1943)',
      obj: 'Analyse Hitler’s invasion of the USSR and the catastrophic German defeat at Stalingrad.',
      hinge:
        'Why was the Battle of Stalingrad the decisive strategic turning point in the European war?',
      evidence:
        'Field Marshal Paulus’s 6th Army encirclement communiqués; Soviet Red Army combat orders (Order No. 227: "Not one step back!").',
      debate:
        'Eastern Front historiography: German logistical and climate failure vs Soviet industrial mobilization and deep battle doctrine.',
      assessment:
        '[12-Mark Essay] Explain why the Battle of Stalingrad was the decisive turning point in the European war.',
    },
    {
      title: 'Total War, Empire Troops & Atlantic War',
      obj: 'Uncover the vital contributions of Indian, African, and Commonwealth forces; explore U-boat war.',
      hinge: 'How crucial were Allied convoy supply lines to sustaining Britain’s war effort?',
      evidence:
        'Photographic archives of the 4th Indian Division in North Africa; Admiralty Atlantic convoy casualty and tonnage logs.',
      debate:
        'Imperial historiography: De-centering anglocentric narratives to evaluate Commonwealth and Indian manpower as decisive catalysts.',
      assessment:
        '[8 Marks] Explain the importance of Commonwealth and Empire troops to the Allied war effort in 1940–1943.',
    },
    {
      title: 'D-Day, Defeat of Nazism & Atomic Bomb (1944–1945)',
      obj: 'Examine Normandy Landings (Operation Overlord); assess the decision to use the atomic bomb on Japan.',
      hinge: 'Was the dropping of the atomic bomb military necessity or geopolitical signalling?',
      evidence:
        'Supreme Allied Headquarters Overlord assault maps; President Truman’s Potsdam decision log on the Manhattan Project (1945).',
      debate:
        'The Atomic Bomb debate: Gar Alperovitz (Cold War atomic diplomacy) vs traditional military necessity (saving invasion lives).',
      assessment:
        '[16-Mark Essay] To what extent was the atomic bomb dropped to intimidate the Soviet Union rather than defeat Japan?',
    },
  ],
  post_war_britain: [
    {
      title: 'The Welfare State & The Birth of the NHS (1945–1951)',
      obj: 'Examine the Beveridge Report; investigate the founding of the NHS in 1948 by Aneurin Bevan.',
      hinge:
        'Why did the British public reject Churchill in 1945 in favour of Labour’s welfare reforms?',
      evidence:
        'Sir William Beveridge’s 1942 Report ("Five Giants"); 1948 Ministry of Health public information leaflets for the NHS.',
      debate:
        'Post-war consensus: Universalist socialist transformation vs cross-party pragmatic compromise to avoid social unrest.',
      assessment:
        '[PEEL Paragraph] Explain why the British electorate voted for Attlee’s Labour government over Churchill in 1945.',
    },
    {
      title: 'The Empire Windrush & Post-War Migration',
      obj: 'Investigate the arrival of HMT Empire Windrush (1948); assess Caribbean contributions and prejudice.',
      hinge:
        'How did British immigration policy contrast with the lived experiences of arriving migrants?',
      evidence:
        'Original passenger manifests of HMT Empire Windrush (June 1948); Contemporary Pathé newsreel dispatches at Tilbury Docks.',
      debate:
        'Post-colonial migration: British Nationality Act 1948 citizenship rights vs institutional hostility and colour bars.',
      assessment:
        '[8 Marks] How useful are oral history testimonies for an enquiry into the experiences of the Windrush generation?',
    },
    {
      title: '1960s Social Revolution & Civil Rights in Britain',
      obj: 'Explore youth culture, legalisation reforms, and the 1963 Bristol Bus Boycott.',
      hinge: 'How did the Bristol Bus Boycott directly catalyse Britain’s 1965 Race Relations Act?',
      evidence:
        'Paul Stephenson’s Bristol Bus Boycott press statements (1963); Hansard parliamentary debates on the Race Relations Act 1965.',
      debate:
        'Grassroots direct action vs legislative reform: Assessing whether public boycotts or political elites drove racial equality laws.',
      assessment:
        '[8 Marks] Explain the significance of the 1963 Bristol Bus Boycott for modern British civil rights.',
    },
    {
      title: 'Deindustrialisation & Winter of Discontent (1970–1979)',
      obj: 'Analyse economic crisis, trade union disputes, and the political fallout of 1978–79.',
      hinge: 'What caused the breakdown of post-war consensus politics during the 1970s?',
      evidence:
        'Daily Mail and Sun front-page headlines ("Crisis? What Crisis?"); Trade Union Congress strike ballots and picket photographs.',
      debate:
        'Economic crisis historiography: Militant trade union disruption vs systemic capitalist industrial obsolescence.',
      assessment:
        '[PEEL Paragraph] Explain how the Winter of Discontent (1978–79) paved the way for Margaret Thatcher’s election victory.',
    },
    {
      title: 'Thatcherism & The Making of Modern Britain (1979–2000)',
      obj: 'Evaluate Thatcher’s economic revolution (privatisation, Miners’ Strike); assess multicultural Britain.',
      hinge: 'How far did Thatcherism permanently redefine British society and economic life?',
      evidence:
        'National Coal Board pit closure schedules (1984); Conservative election manifestos on council house sales ("Right to Buy").',
      debate:
        'The Thatcherite Legacy: Necessary modernisation of a stagnant economy vs catastrophic destruction of working-class communities.',
      assessment:
        '[16-Mark Essay] "Margaret Thatcher’s economic policies did more harm than good to British society." How far do you agree?',
    },
  ],
};

const commonHead = `
    <head>
        <meta charset="UTF-8">
        <title>Meoncross School History Department</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=Outfit:wght@300;400;500;600;700;800&display=swap');
            body { font-family: 'Outfit', sans-serif; color: #1e293b; background: #fff; margin: 0; padding: 0; font-size: 8.5pt; line-height: 1.35; }
            h1, h2, h3, h4 { font-family: 'Playfair Display', serif; color: #1b365d; margin-top: 0; }
            .cover-page { height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; background: #f8fafc; border: 8px solid #facc15; padding: 30px; box-sizing: border-box; }
            .cover-title { font-size: 38pt; font-weight: 700; color: #1b365d; margin-bottom: 14px; }
            .cover-subtitle { font-size: 20pt; color: #facc15; font-family: 'Outfit', sans-serif; font-weight: 300; text-transform: uppercase; letter-spacing: 2px; }
            .page-break { page-break-before: always; }
            .container { padding: 15px 25px; }
            .header-banner { background: #1b365d; color: #fff; padding: 12px 18px; text-align: center; border-radius: 6px; margin-bottom: 16px; border-bottom: 3px solid #facc15; }
            .header-banner h1 { color: #fff; margin: 0; font-size: 16pt; }
            .year-section { margin-bottom: 16px; }
            .year-title { background: #facc15; color: #1b365d; padding: 5px 12px; border-radius: 4px; font-size: 11pt; margin-bottom: 8px; display: inline-block; font-family: 'Outfit', sans-serif; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }
            .unit-card { page-break-inside: avoid; border: 1px solid #cbd5e1; border-radius: 6px; padding: 8px 12px; margin-bottom: 8px; background: #f8fafc; border-left: 4px solid #1b365d; }
            .unit-card h3 { font-size: 11pt; margin: 0 0 3px 0; color: #1b365d; }
            .unit-card .enquiry { font-weight: 600; color: #b89c30; font-size: 8.5pt; margin-bottom: 3px; }
            .unit-card .desc { font-size: 8pt; color: #475569; margin: 0; line-height: 1.3; }
            
            /* SOW Styles */
            .sow-unit-container { margin-bottom: 25px; page-break-inside: auto; }
            .sow-unit-header { background: #1b365d; color: #fff; padding: 10px 16px; border-radius: 6px 6px 0 0; border-bottom: 3px solid #facc15; margin-bottom: 12px; }
            .sow-unit-header h2 { color: #fff; margin: 0 0 4px 0; font-size: 16pt; }
            .sow-unit-header p { margin: 0; color: #e2e8f0; font-family: 'Outfit', sans-serif; font-size: 9.5pt; }
            .primer-box { background: #fef3c7; border: 1px solid #fde68a; border-left: 4px solid #d97706; padding: 8px 12px; border-radius: 4px; margin-bottom: 12px; font-size: 8pt; line-height: 1.35; }
            .primer-box h4 { margin: 0 0 4px 0; color: #92400e; font-family: 'Outfit', sans-serif; text-transform: uppercase; font-size: 8.5pt; letter-spacing: 1px; }
            
            table { width: 100%; border-collapse: collapse; margin-bottom: 16px; page-break-inside: auto; font-size: 8pt; }
            tr { page-break-inside: avoid; page-break-after: auto; border-bottom: 1px solid #e2e8f0; }
            tr:nth-child(even) { background-color: #f8fafc; }
            th { background: #0f172a; color: #ffffff; text-align: left; padding: 7px 9px; font-family: 'Outfit', sans-serif; font-weight: 600; font-size: 8pt; border: none; }
            td { padding: 6px 8px; border: none; vertical-align: top; font-size: 7.8pt; line-height: 1.3; color: #334155; }
            
            .lesson-num { font-weight: 700; color: #1b365d; white-space: nowrap; font-size: 8pt; }
            .lesson-title { font-weight: 700; margin-bottom: 2px; color: #1e40af; font-size: 8.5pt; }
            
            .hinge-question { color: #b91c1c; font-style: italic; font-weight: 600; margin-top: 4px; display: block; border-left: 2px solid #ef4444; padding-left: 6px; font-size: 7.5pt; }
            
            ul.obj-list { margin: 2px 0 0 0; padding-left: 14px; font-size: 7.8pt; }
            ul.obj-list li { margin-bottom: 2px; }
            
            /* SOW 3-Tier Task Extractor Styles */
            .sow-three-tier { display: flex; flex-direction: column; gap: 4.5px; }
            .tier-box { background: #ffffff; border: 1px solid #e2e8f0; border-radius: 4px; padding: 4px 7px; box-shadow: 0 1px 2px rgba(0,0,0,0.02); }
            .tier-label { font-size: 6.8pt; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 2px; }
            .tier-evidence { border-left: 3.5px solid #1e3a8a; }
            .tier-evidence .tier-label { color: #1e3a8a; }
            .tier-debate { border-left: 3.5px solid #b45309; }
            .tier-debate .tier-label { color: #b45309; }
            .tier-assessment { border-left: 3.5px solid #0f766e; }
            .tier-assessment .tier-label { color: #0f766e; }
            .tier-content { font-size: 7.3pt; color: #1e293b; line-height: 1.28; }
            .tier-assessment .tier-content { font-weight: 600; color: #0f172a; }
        </style>
    </head>
`;

function cleanText(str) {
  if (!str) return '';
  return String(str)
    .replace(/<[^>]+>/g, '')
    .replace(/\\n/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function extractLessonThreeTier(lesson, uid, unitData, idx) {
  // 1. Primary Evidence & Source Analysis
  const sources = [];

  // Dedicated known primary sources per unit & lesson for maximum pedagogical precision
  const curatedSources = {
    water_and_sanitation: {
      0: [
        "Housesteads Fort Roman communal latrines (Hadrian's Wall)",
        "Seneca's moral treatise on Roman baths",
        'Fishbourne Roman Palace mosaics',
      ],
      1: [
        'Canterbury Cathedral Waterworks Plan (c. 1165)',
        'City of London Sanitary Ordinance of 1357',
        'Monastic reredorter latrine architecture',
      ],
      2: [
        "Sir John Harington's 1596 'Ajax' Toilet Diagram",
        "Samuel Pepys' 1660 Diary on cellar privies",
        'The Cowdray Engraving of Tudor Portsmouth (1545)',
      ],
      3: [
        "Chadwick's 1842 Report on the Sanitary Condition of the Labouring Population",
        "Dr John Snow's Broad Street Cholera Spot Map (1854)",
        'Portsmouth cholera burial registers',
      ],
      4: [
        "Punch Cartoon 'The Silent Highwayman' (1858 Great Stink)",
        "Bazalgette's Victorian intercepting sewer blueprints (1859–1865)",
      ],
      5: [
        "Dr John Snow's 1854 Broad Street Cholera Spot Map",
        'Soho mortality records & Eley Brothers percussion cap factory logs',
      ],
    },
    great_war: {
      0: [
        'Source A: Map of the newly created German Empire (1871)',
        "Bismarck's 'Blood and Iron' speech transcript (1862)",
      ],
      1: [
        'Map A: The Annexation of Alsace-Lorraine (Treaty of Frankfurt, 1871)',
        'Source B: The Black Spot (La Tache Noire) by Albert Bettannier (1887)',
        "Source A: Anton von Werner's Proclamation of the German Empire at Versailles",
      ],
      2: [
        'Source A: The 1879 Dual Alliance Treaty between Germany and Austria-Hungary',
        "Punch Cartoon 'Dropping the Pilot' (1890)",
        "Kaiser Wilhelm II's 'Place in the Sun' declaration",
      ],
      3: [
        'Source A: Blueprint of HMS Dreadnought (1906)',
        'German Navy Laws propaganda poster (Tirpitz)',
        "British Daily Mail 'We Want Eight and We Won't Wait' articles",
      ],
      4: [
        'Source A: Map of European Strategic Railway Timetables (1914)',
        "Source B: General Alfred von Schlieffen's war memorandum (1905)",
        'Belgian diplomatic protest over violation of neutrality',
      ],
      5: [
        'Source A: Trench map of the Ypres Salient (1914)',
        'Private soldier field postcards & 1st Battalion Hampshire Regiment war diaries',
        'Contemporary aerial reconnaissance photography of trench systems',
      ],
      6: [
        'Source A: The Western Mail front page on the Christmas Truce (1914)',
        'Letter from Captain Sir Edward Hulse (Scots Guards, 1914)',
        'Imperial War Museum oral history recordings of Saxon and British soldiers',
      ],
    },
  };

  if (curatedSources[uid] && curatedSources[uid][idx]) {
    sources.push(...curatedSources[uid][idx]);
  }

  // Check lesson.sources
  if (lesson.sources && Array.isArray(lesson.sources)) {
    lesson.sources.forEach((s) => {
      const title = s.title || s.caption || s.provenance;
      if (title) sources.push(cleanText(title));
    });
  }

  // Check lesson.primary_source
  if (lesson.primary_source) {
    const ps = lesson.primary_source.title || lesson.primary_source.caption;
    if (ps) sources.push(cleanText(ps));
  }

  // Check gcse_task.sources
  if (lesson.gcse_task?.sources && Array.isArray(lesson.gcse_task.sources)) {
    lesson.gcse_task.sources.forEach((s) => {
      if (s.title) sources.push(cleanText(s.title));
    });
  }

  // Check lesson.exam_practice.stimulus
  if (lesson.exam_practice?.stimulus && Array.isArray(lesson.exam_practice.stimulus)) {
    lesson.exam_practice.stimulus.forEach((s) => {
      if (s.title) sources.push(cleanText(s.title));
    });
  }

  // Check narrative_blocks
  if (lesson.narrative_blocks && Array.isArray(lesson.narrative_blocks)) {
    lesson.narrative_blocks.forEach((b) => {
      if (b.source?.title) sources.push(cleanText(b.source.title));
      else if (b.source?.caption) sources.push(cleanText(b.source.caption));
      else if (typeof b.source === 'string' && b.source.startsWith('Source'))
        sources.push(cleanText(b.source));

      if (
        b.image_alt &&
        (b.image_alt.includes('Source') ||
          b.image_alt.includes('1') ||
          b.image_alt.includes('cartoon') ||
          b.image_alt.includes('photograph') ||
          b.image_alt.includes('map') ||
          b.image_alt.includes('Treaty') ||
          b.image_alt.includes('Statute') ||
          b.image_alt.includes('engraving'))
      ) {
        let alt = cleanText(b.image_alt);
        if (alt.length > 90) alt = alt.slice(0, 87) + '...';
        sources.push(alt);
      }
    });
  }

  // Deduplicate and filter sources
  const cleanSources = Array.from(new Set(sources))
    .filter(
      (s) =>
        s &&
        s.length > 5 &&
        !s.toLowerCase().includes('quiz') &&
        !s.toLowerCase().includes('portrait card') &&
        !s.toLowerCase().includes('local link'),
    )
    .slice(0, 3);

  // 2. Disciplinary Debate / Historian Focus
  let debate = '';

  const curatedDebates = {
    water_and_sanitation: {
      0: 'Roman engineering triumphalism vs lived public health reality: lead piping & parasite transmission',
      1: 'Medieval hygiene myths: Religious purity and monastic engineering vs urban municipal paralysis',
      2: 'Laissez-faire policy debate & Roy Porter on early modern infrastructure limits; technological innovation vs municipal failure',
      3: 'Industrial urbanisation: Miasma theory vs early contagionist epidemiology; laissez-faire vs state health intervention',
      4: 'The Great Stink of 1858: Parliamentary self-interest and physical stench vs municipal laissez-faire ideology',
      5: "Snow's empirical epidemiological mapping vs the entrenched medical establishment and Board of Health",
    },
  };

  if (curatedDebates[uid] && curatedDebates[uid][idx]) {
    debate = curatedDebates[uid][idx];
  } else if (lesson.historians_corner?.title) {
    debate =
      `${cleanText(lesson.historians_corner.title)}: ${cleanText(lesson.historians_corner.text || '')}`.slice(
        0,
        150,
      );
  } else if (lesson.historical_interpretations) {
    const hi = lesson.historical_interpretations;
    const title =
      hi.title ||
      (typeof hi === 'string'
        ? hi
        : 'Evaluating competing academic interpretations and historiographical perspectives');
    debate = cleanText(title);
  } else if (lesson.teacher_notes?.objectives) {
    const debObj = lesson.teacher_notes.objectives.find(
      (o) =>
        o.objective &&
        (o.objective.toLowerCase().includes('debate') ||
          o.objective.toLowerCase().includes('evaluate') ||
          o.objective.toLowerCase().includes('extent') ||
          o.objective.toLowerCase().includes('interpret') ||
          o.objective.toLowerCase().includes('contrast')),
    );
    if (debObj) {
      debate = cleanText(debObj.objective);
    }
  }

  if (!debate) {
    const concept =
      lesson.disciplinary_concept ||
      lesson.disciplinary_focus ||
      lesson.historical_concept ||
      'Historical Enquiry';
    debate = `Core Disciplinary Concept: ${concept} & Causal Argumentation`;
  }

  // 3. Core Written Assessment
  let assessment = '';

  if (lesson.extended?.question) {
    assessment = cleanText(lesson.extended.question);
  } else if (lesson.gcse_task?.topic) {
    assessment = `[8 Marks] How useful are Sources A and B for an enquiry into ${cleanText(lesson.gcse_task.topic)}?`;
  } else if (lesson.exam_practice) {
    const qList = Array.isArray(lesson.exam_practice)
      ? lesson.exam_practice
      : lesson.exam_practice.questions || [];
    if (qList.length > 0) {
      assessment = qList
        .map((q) => {
          const m = q.marks ? `[${q.marks} Marks] ` : '';
          return `${m}${cleanText(q.question)}`;
        })
        .join(' • ');
    }
  } else if (lesson.peel_paragraph?.question) {
    assessment = `[PEEL Paragraph] ${cleanText(lesson.peel_paragraph.question)}`;
  } else if (lesson.formative_assessment?.question) {
    assessment = `[Assessment Task] ${cleanText(lesson.formative_assessment.question)}`;
  } else if (lesson.lesson_assessment?.question) {
    assessment = `[Assessment Task] ${cleanText(lesson.lesson_assessment.question)}`;
  } else if (lesson.narrative_blocks) {
    const writtenTask = lesson.narrative_blocks
      .flatMap((b) => b.tasks || [])
      .find((t) => t.type === 'extended_writing' || t.type === 'peel_paragraph');
    if (writtenTask) {
      assessment = `[Written Task] ${cleanText(writtenTask.question || writtenTask.text || writtenTask.instruction)}`;
    }
  }

  if (!assessment) {
    assessment = `[Written Synthesis] Complete structured analytical enquiry response in pupil workbook.`;
  }

  if (assessment.length > 190) {
    assessment = assessment.slice(0, 187) + '...';
  }

  const evidenceText =
    cleanSources.length > 0
      ? cleanSources.join('; ')
      : 'Contemporary primary excerpts and archival evidence.';
  return {
    evidence: evidenceText,
    sources: evidenceText,
    debate,
    assessment,
  };
}

function generateOverviewHTML(db) {
  let html = `<!DOCTYPE html><html lang="en">${commonHead}<body>`;

  html += `
        <div class="cover-page">
            <div class="cover-title">Meoncross School History Department</div>
            <div class="cover-subtitle">5-Year Curriculum Overview (2026-2027)</div>
            <div style="margin-top: 30px; font-size: 12pt; color: #475569;">Key Stages 3 &amp; 4 (Years 7 – 11)</div>
        </div>
        <div class="page-break"></div>
        <div class="container">
            <div class="header-banner">
                <h1>History Curriculum Map &amp; Enquiry Architecture</h1>
            </div>
    `;

  for (const [yearGroup, unitIds] of Object.entries(curriculumMap)) {
    html += `<div class="year-section"><div class="year-title">${yearGroup}</div>`;
    for (const uid of unitIds) {
      const unitData = db[uid]?.data;
      if (!unitData) continue;

      const title = unitData.title || uid;
      let enquiry = unitData.enquiry || unitData.enquiry_question || '';
      if (enquiryPatchMap[uid]) {
        enquiry = enquiryPatchMap[uid];
      }

      const desc =
        unitData.desc ||
        (unitData.lessons && unitData.lessons.length
          ? 'An in-depth study featuring ' + unitData.lessons.length + ' lessons.'
          : '');

      html += `
                <div class="unit-card">
                    <h3>${title}</h3>
                    ${enquiry ? `<div class="enquiry"><strong style="color:#1b365d">Enquiry:</strong> ${enquiry}</div>` : ''}
                    <div class="desc">${desc}</div>
                </div>
            `;
    }
    html += `</div>`;
  }
  html += `</div></body></html>`;

  const outPath = path.join(publicDir, 'curriculum_overview.html');
  fs.writeFileSync(outPath, html);
  return outPath;
}

function generateSOWHTML(db, yearGroup, unitIds) {
  let html = `<!DOCTYPE html><html lang="en">${commonHead}<body>`;

  html += `
        <div class="cover-page">
            <div class="cover-title">Meoncross School History Department</div>
            <div class="cover-subtitle">${yearGroup} Scheme of Work (2026-2027)</div>
            <div style="margin-top: 30px; font-size: 12pt; color: #475569;">Curriculum Planning &amp; Lesson Companion</div>
        </div>
    `;

  const isKS4 = yearGroup === 'Year 10' || yearGroup === 'Year 11';

  if (!isKS4) {
    // Key Stage 3 Preamble: Exactly 1 clean, authoritative, positive page
    html += `
        <div class="page-break"></div>
        <div class="container" style="padding-top: 25px;">
            <div class="header-banner">
                <h1>Key Stage 3 Curriculum Intent &amp; Pedagogical Architecture</h1>
            </div>
            
            <div style="margin-bottom: 16px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 5px; font-size: 13pt;">1. Curriculum Rationale &amp; Local Maritime Heritage</h2>
                <p style="margin-top: 0; font-size: 8.5pt; color: #475569; line-height: 1.4;">
                    Our Key Stage 3 history curriculum is intentionally constructed to link national and global historical narratives with the distinctive maritime geography and lived environment of Meoncross pupils. From the industrial revolution of the Fareham ironmaster (Henry Cort at Funtley) to the strategic supremacy of Portsmouth Royal Dockyard and the profound sacrifices recorded on the Stubbington village war memorials, history is made tangible, relevant, and deeply rooted in our coastal community.
                </p>
            </div>

            <div style="margin-bottom: 16px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 5px; font-size: 13pt;">2. Disciplinary Progression &amp; Historical Enquiry</h2>
                <p style="margin-top: 0; font-size: 8.5pt; color: #475569; line-height: 1.4;">
                    Across Years 7, 8, and 9, disciplinary thinking progresses sequentially to secure the foundational skills required for GCSE excellence:
                </p>
                <ul style="color: #334155; font-size: 8pt; line-height: 1.4; margin: 4px 0 0 0; padding-left: 18px;">
                    <li style="margin-bottom: 4px;"><strong>Chronological Rigour &amp; Global Encounters:</strong> De-centering traditional anglocentric narratives by examining early global trade, Indigenous perspectives in Australia, and African resistance to the Transatlantic Slave Trade alongside British social transformations.</li>
                    <li style="margin-bottom: 4px;"><strong>Causation &amp; Consequence:</strong> Moving from simple direct triggers in Year 7 to evaluating multi-tiered, long-term geopolitical catalysts (e.g. European alliance systems, naval arms races).</li>
                    <li style="margin-bottom: 4px;"><strong>Source Utility &amp; Forensic Evidence:</strong> Progressing from basic comprehension to rigorous interrogation of provenance, evaluating authorial motive, audience, and historical reliability.</li>
                    <li style="margin-bottom: 4px;"><strong>Historiographical Debate:</strong> Engaging pupils with active academic debates (e.g., assessing the Magna Carta, or challenging the 'Lions led by Donkeys' narrative of the Great War) grounded in historical evidence.</li>
                </ul>
            </div>

            <div style="margin-bottom: 14px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 5px; font-size: 13pt;">3. Adaptive Teaching, Dual Coding &amp; Inclusion</h2>
                <p style="margin-top: 0; font-size: 8.5pt; color: #475569; line-height: 1.4;">
                    Pupils work through bespoke printed A4 workbooks closely paired with our digital learning portal. Standardized PEE/PEEL Structure Strips, Causal Connective Banks, consistent dual coding, and digital accessibility features offload working memory, ensuring all SEND and lower-attaining pupils achieve ambitious historical progress with zero cognitive overload.
                </p>
            </div>
        </div>
    `;
  } else {
    // Key Stage 4 (GCSE) Preamble: Exactly 1 clean, authoritative Edexcel specification framework page
    html += `
        <div class="page-break"></div>
        <div class="container" style="padding-top: 25px;">
            <div class="header-banner">
                <h1>Key Stage 4 Curriculum Architecture &amp; Edexcel GCSE Specification</h1>
            </div>
            
            <div style="margin-bottom: 14px;">
                <h2 style="color: #1b365d; border-bottom: 2px solid #facc15; padding-bottom: 4px; font-size: 12pt;">Pearson Edexcel GCSE (9–1) History Specification (1HI0)</h2>
                <p style="margin-top: 0; font-size: 8pt; color: #475569; line-height: 1.35;">
                    Meoncross School delivers a balanced 4-unit curriculum covering thematic development, British depth, period conflict, and modern world history:
                </p>
                <table style="font-size: 7.8pt; margin-bottom: 10px;">
                    <thead>
                        <tr>
                            <th style="width: 28%;">Exam Paper &amp; Topic</th>
                            <th style="width: 18%;">Assessment Focus</th>
                            <th style="width: 14%;">Weighting</th>
                            <th style="width: 20%;">Format &amp; Marks</th>
                            <th style="width: 20%;">Taught Cohort</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Paper 1 (1HI0/11):</strong><br>Medicine in Britain (c.1250–present) &amp; Western Front (1914–18)</td>
                            <td>Thematic Study &amp; Historic Environment</td>
                            <td><strong>30%</strong> of GCSE</td>
                            <td>1 hr 15 mins<br>52 marks (incl. 4 SPaG)</td>
                            <td>Year 11</td>
                        </tr>
                        <tr>
                            <td><strong>Paper 2 (1HI0/26):</strong><br>Conflict in the Middle East (1945–1995)</td>
                            <td>Period Study</td>
                            <td><strong>20%</strong> of GCSE</td>
                            <td>50 mins<br>32 marks</td>
                            <td>Year 10</td>
                        </tr>
                        <tr>
                            <td><strong>Paper 2 (1HI0/26):</strong><br>Early Elizabethan England (1558–1588)</td>
                            <td>British Depth Study</td>
                            <td><strong>20%</strong> of GCSE</td>
                            <td>55 mins<br>32 marks</td>
                            <td>Year 11</td>
                        </tr>
                        <tr>
                            <td><strong>Paper 3 (1HI0/31):</strong><br>Weimar and Nazi Germany (1918–1939)</td>
                            <td>Modern Depth Study</td>
                            <td><strong>30%</strong> of GCSE</td>
                            <td>1 hr 20 mins<br>52 marks (incl. 4 SPaG)</td>
                            <td>Year 10</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 10px;">
                <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-left: 4px solid #1b365d; padding: 8px 10px; border-radius: 4px;">
                    <h3 style="color: #1b365d; margin: 0 0 3px 0; font-size: 9pt;">Assessment Objectives (AOs)</h3>
                    <ul style="font-size: 7.5pt; line-height: 1.3; margin: 0; padding-left: 12px; color: #334155;">
                        <li><strong>AO1 (35%):</strong> Demonstrate knowledge and understanding of key features.</li>
                        <li><strong>AO2 (35%):</strong> Explain and analyse events, causes, consequences, and change.</li>
                        <li><strong>AO3 (15%):</strong> Analyse, evaluate, and use contemporary sources.</li>
                        <li><strong>AO4 (15%):</strong> Analyse and evaluate historical interpretations in context.</li>
                    </ul>
                </div>
                <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-left: 4px solid #d97706; padding: 8px 10px; border-radius: 4px;">
                    <h3 style="color: #92400e; margin: 0 0 3px 0; font-size: 9pt;">Standardized Question Frameworks</h3>
                    <ul style="font-size: 7.5pt; line-height: 1.3; margin: 0; padding-left: 12px; color: #334155;">
                        <li><strong>4-mark Consequence:</strong> PEE structure (immediate &amp; long-term).</li>
                        <li><strong>8-mark Narrative:</strong> 3-phase chronological causal flowchart.</li>
                        <li><strong>8-mark Importance:</strong> Analytical criteria for historical impact.</li>
                        <li><strong>2+2 Features:</strong> Concisely identifying and developing features.</li>
                        <li><strong>8-mark Utility:</strong> Evaluating content and provenance (Author/Audience/Motive).</li>
                        <li><strong>16+4 Judgement Essays:</strong> Evaluative criteria with sustained balance.</li>
                    </ul>
                </div>
            </div>

            <div style="background: #eff6ff; border: 1px solid #bfdbfe; padding: 7px 10px; border-radius: 4px;">
                <p style="margin: 0; font-size: 7.8pt; color: #1e40af; line-height: 1.3;">
                    <strong>Mastery Methodology:</strong> GCSE pupils utilize printed Edexcel Mastery Booklets featuring 3-tier models, formula stamps, and walking-talking mock rehearsals, ensuring complete familiarity with mark schemes and timing constraints prior to the final examinations.
                </p>
            </div>
        </div>
    `;
  }

  for (const uid of unitIds) {
    const unitData = db[uid]?.data;
    if (!unitData) continue;

    const title = unitData.title || uid;
    let enquiry = unitData.enquiry || unitData.enquiry_question || '';
    if (enquiryPatchMap[uid]) {
      enquiry = enquiryPatchMap[uid];
    }

    // Fix Vocab Bleed: Reset the vocabulary variable to empty before parsing each new unit
    let vocabulary = [];
    if (unitData.glossary && Array.isArray(unitData.glossary)) {
      vocabulary = unitData.glossary;
    }

    html += `<div class="container sow-unit-container">`;
    html += `
                <div class="sow-unit-header">
                    <h2>${title}</h2>
                    <p><strong>${yearGroup}</strong> ${enquiry ? '| ' + enquiry : ''}</p>
                </div>
            `;

    if (unitData.teacher_notes && unitData.teacher_notes.primer) {
      html += `
                    <div class="primer-box">
                        <h4>Pedagogical Goals & Primer</h4>
                        <div>${unitData.teacher_notes.primer}</div>
                    </div>
                `;
    }

    const outlineLessons = unitCurriculumOutlines[uid];

    if (unitData.lessons && unitData.lessons.length > 0) {
      html += `
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 8pt;">
                        <thead>
                            <tr>
                                <th style="width: 20%">Lesson Number &amp; Title</th>
                                <th style="width: 32%">Learning Objectives &amp; Enquiry</th>
                                <th style="width: 48%">Curriculum Rigour: Evidence, Debate &amp; Assessment</th>
                            </tr>
                        </thead>
                        <tbody>
                `;

      unitData.lessons.forEach((lesson, idx) => {
        // Extract Learning Objectives dynamically
        let objsHTML = '';
        let hinge = '';

        if (
          lesson.learning_objectives &&
          Array.isArray(lesson.learning_objectives) &&
          lesson.learning_objectives.length > 0
        ) {
          // Flat array of strings (Year 8+ format)
          objsHTML =
            `<ul class="obj-list">` +
            lesson.learning_objectives.map((o) => `<li>${o}</li>`).join('') +
            `</ul>`;
        } else if (
          lesson.learning_objectives &&
          Array.isArray(lesson.learning_objectives.scaffolded) &&
          lesson.learning_objectives.scaffolded.length > 0
        ) {
          // Nested object with scaffolded array (Year 7 / legacy format)
          objsHTML =
            `<ul class="obj-list">` +
            lesson.learning_objectives.scaffolded.map((o) => `<li>${o}</li>`).join('') +
            `</ul>`;
        } else if (lesson.intent && Array.isArray(lesson.intent) && lesson.intent.length > 0) {
          objsHTML =
            `<ul class="obj-list">` + lesson.intent.map((o) => `<li>${o}</li>`).join('') + `</ul>`;
        } else if (lesson.learning_objective) {
          objsHTML = `<ul class="obj-list"><li>${lesson.learning_objective}</li></ul>`;
        } else {
          objsHTML = '<span style="color:#94a3b8; font-style:italic;">Historical Enquiry</span>';
        }

        // Extract Hinge Question from teacher_notes if available
        if (unitData.teacher_notes && unitData.teacher_notes.objectives) {
          const lessonObjs = unitData.teacher_notes.objectives.filter(
            (o) =>
              (lesson.learning_objective && o.objective === lesson.learning_objective) ||
              (lesson.learning_objectives &&
                lesson.learning_objectives.scaffolded &&
                lesson.learning_objectives.scaffolded.includes(o.objective)) ||
              (lesson.title && o.objective && o.objective.includes(lesson.title.split(':')[0])) ||
              (lesson.title && lesson.title.includes(o.objective)),
          );
          const hingeObj = lessonObjs.find((o) => o.question);
          if (hingeObj) hinge = hingeObj.question;
        }

        const tier = extractLessonThreeTier(lesson, uid, unitData, idx);

        html += `
                        <tr>
                            <td>
                                <div class="lesson-num">Lesson ${idx + 1}</div>
                                <div class="lesson-title">${lesson.title || 'Untitled Lesson'}</div>
                            </td>
                            <td>
                                ${objsHTML}
                                ${hinge ? `<span class="hinge-question">Hinge Q: ${hinge}</span>` : ''}
                            </td>
                            <td>
                                <div class="sow-three-tier">
                                    <div class="tier-box tier-evidence">
                                        <div class="tier-label">📜 Primary Evidence &amp; Source Analysis:</div>
                                        <div class="tier-content">${tier.evidence}</div>
                                    </div>
                                    <div class="tier-box tier-debate">
                                        <div class="tier-label">⚖️ Disciplinary Debate / Historian Focus:</div>
                                        <div class="tier-content">${tier.debate}</div>
                                    </div>
                                    <div class="tier-box tier-assessment">
                                        <div class="tier-label">✍️ Core Written Assessment:</div>
                                        <div class="tier-content">${tier.assessment}</div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    `;
      });

      html += `</tbody></table>`;
    } else if (outlineLessons && outlineLessons.length > 0) {
      html += `
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 8pt;">
                        <thead>
                            <tr>
                                <th style="width: 20%">Lesson Number &amp; Title</th>
                                <th style="width: 32%">Learning Objectives &amp; Enquiry</th>
                                <th style="width: 48%">Curriculum Rigour: Evidence, Debate &amp; Assessment</th>
                            </tr>
                        </thead>
                        <tbody>
                `;
      outlineLessons.forEach((l, lIdx) => {
        html += `
                        <tr>
                            <td>
                                <div class="lesson-num">Lesson ${lIdx + 1}</div>
                                <div class="lesson-title">${l.title}</div>
                            </td>
                            <td>
                                <ul class="obj-list"><li>${l.obj}</li></ul>
                                <span class="hinge-question">Hinge Q: ${l.hinge}</span>
                            </td>
                            <td>
                                <div class="sow-three-tier">
                                    <div class="tier-box tier-evidence">
                                        <div class="tier-label">📜 Primary Evidence &amp; Source Analysis:</div>
                                        <div class="tier-content">${l.evidence || 'Contemporary primary excerpts and archival evidence.'}</div>
                                    </div>
                                    <div class="tier-box tier-debate">
                                        <div class="tier-label">⚖️ Disciplinary Debate / Historian Focus:</div>
                                        <div class="tier-content">${l.debate || 'Historiographical interpretation and historical debate.'}</div>
                                    </div>
                                    <div class="tier-box tier-assessment">
                                        <div class="tier-label">✍️ Core Written Assessment:</div>
                                        <div class="tier-content">${l.assessment || l.tasks || 'Structured written assessment.'}</div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    `;
      });
      html += `</tbody></table>`;
    }

    if (vocabulary && vocabulary.length > 0) {
      const words = vocabulary
        .map((v) => v.term || v.word || v.keyword)
        .filter((w) => w && w !== 'undefined')
        .map((w) => w.trim());

      const uniqueWords = Array.from(new Set(words));

      if (uniqueWords.length > 0) {
        html += `
            <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-left: 3px solid #1b365d; padding: 5px 8px; border-radius: 4px; margin: 6px 0 12px 0; font-size: 7.5pt;">
                <strong style="color: #1b365d;">Unit Key Vocabulary:</strong> 
                <span style="color: #475569;">${uniqueWords.join(' • ')}</span>
            </div>
        `;
      }
    }

    html += `</div>`;
  }

  html += `</body></html>`;
  const outPath = path.join(publicDir, 'scheme_of_work.html');
  fs.writeFileSync(outPath, html);
  return outPath;
}

(async () => {
  const dbPath = path.join(publicDir, 'database.json');
  const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

  // Dynamically enrich the db with real data.js imports to ensure we don't miss nested arrays (like exam_practice, intent, peel_paragraph)
  for (const [yearGroup, unitIds] of Object.entries(curriculumMap)) {
    for (const uid of unitIds) {
      if (['cold_war', 'second_world_war', 'the_shoah'].includes(uid)) {
        continue; // Do not parse their data.js files
      }
      const rootDataPath = path.join(__dirname, '..', 'units', uid, 'data.js');
      const pubDataPath = path.join(publicDir, 'units', uid, 'data.js');
      const dataPath = fs.existsSync(rootDataPath) ? rootDataPath : pubDataPath;
      if (fs.existsSync(dataPath)) {
        try {
          // Dynamically import the ES module
          const dataModule = await import(require('url').pathToFileURL(dataPath).href);
          const uData = dataModule?.unitData || dataModule?.default;
          if (uData) {
            if (!db[uid]) db[uid] = { data: {} };
            if (uData.lessons) {
              db[uid].data.lessons = uData.lessons;
            }
            if (uData.teacher_notes) {
              db[uid].data.teacher_notes = uData.teacher_notes;
            }
          }
        } catch (e) {
          console.error('Error importing data.js for', uid, e);
        }
      }
    }
  }

  console.log('Generating HTML templates...');
  const overviewHtmlPath = generateOverviewHTML(db);

  console.log('Launching Puppeteer to create PDFs...');
  const browser = await puppeteer.launch({ headless: 'new' });

  // 1. Generate Overview PDF
  console.log('Rendering Curriculum Overview PDF...');
  const page1 = await browser.newPage();
  await page1.goto(require('url').pathToFileURL(overviewHtmlPath).href, {
    waitUntil: 'networkidle0',
  });
  const overviewPdfPath = path.join(pdfsDir, 'whole_school_curriculum_overview.pdf');
  await page1.pdf({
    path: overviewPdfPath,
    format: 'A4',
    printBackground: true,
    displayHeaderFooter: true,
    headerTemplate: '<div></div>',
    footerTemplate:
      '<div style="font-size:8pt; width:100%; text-align:center; font-family: sans-serif; color: #94a3b8;">Meoncross School History Department - Curriculum Overview | Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>',
    margin: { top: '8mm', right: '10mm', bottom: '12mm', left: '10mm' },
  });
  console.log('✅ Success! Overview PDF saved to: ' + overviewPdfPath);

  // 2. Generate SOW PDFs per Year Group
  for (const [stage, stageMap] of Object.entries(fullCurriculumMap)) {
    for (const [yearGroup, unitIds] of Object.entries(stageMap)) {
      const safeYearName = yearGroup.toLowerCase().replace(' ', '_');
      const htmlPath = generateSOWHTML(db, yearGroup, unitIds);

      console.log(`Rendering ${yearGroup} Scheme of Work PDF...`);
      const page = await browser.newPage();
      await page.goto(require('url').pathToFileURL(htmlPath).href, { waitUntil: 'networkidle0' });

      // Adjust layout for standard portrait width
      const pdfPath = path.join(pdfsDir, `${safeYearName}_sow.pdf`);
      await page.pdf({
        path: pdfPath,
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `<div style="font-size:8pt; width:100%; text-align:center; font-family: sans-serif; color: #94a3b8;">Meoncross School History Department - ${yearGroup} Scheme of Work | Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>`,
        margin: { top: '8mm', right: '10mm', bottom: '12mm', left: '10mm' },
      });
      console.log(`✅ Success! ${yearGroup} Scheme of Work PDF saved to: ` + pdfPath);
      await page.close();
    }
  }

  await browser.close();

  // Synchronize updated SOW PDFs to Google Drive Department File if available
  try {
    const { syncAdminPdfsToDrive } = require('./sync_admin_pdfs_to_drive.cjs');
    syncAdminPdfsToDrive();
  } catch (err) {
    // Non-fatal if Google Drive is unmounted
  }
})();
