/**
 * Dual-Numbering Unit Test: Question Sync Auditor
 *
 * Verifies that runtime question numbering in assignQuestionNumbers() (src/engine/lesson_renderer.js & src/core_app.js)
 * strictly matches the canonical question indexing generated by generate_pupil_workbooks.cjs
 * for all lessons across curriculum units (Years 7–11).
 *
 * Safeguards printed pupil workbooks and textbooks from accidental desynchronization with the digital app.
 */

const fs = require('fs');
const path = require('path');

const databasePath = path.join(__dirname, '../public/database.json');
if (!fs.existsSync(databasePath)) {
  console.error('❌ Error: public/database.json not found. Run database build first.');
  process.exit(1);
}

const db = JSON.parse(fs.readFileSync(databasePath, 'utf8'));

// Dynamically extract assignQuestionNumbers from src/engine/lesson_renderer.js to test true runtime code
const rendererSrc = fs.readFileSync(
  path.join(__dirname, '../src/engine/lesson_renderer.js'),
  'utf8',
);
const fnStart = rendererSrc.indexOf('export function assignQuestionNumbers');
const fnEnd = rendererSrc.indexOf('export function renderPoetryDossiersHTML');
if (fnStart === -1 || fnEnd === -1) {
  console.error(
    '❌ Error: Could not locate assignQuestionNumbers in src/engine/lesson_renderer.js',
  );
  process.exit(1);
}
const fnCode = rendererSrc.slice(fnStart, fnEnd).replace('export function', 'function');
eval(fnCode);

/**
 * Extracts canonical question numbering as generated by generate_pupil_workbooks.cjs
 */
function extractCanonicalWorkbookNumbering(lesson, unitId) {
  const items = [];
  let globalQNum = 1;
  const isGCSE = ['cme_new', 'edexcel_medicine', 'eee', 'weimar_nazi_germany'].includes(unitId);
  const isGreatWar = unitId === 'great_war' || unitId === 'great_war_part2';

  // 1. Primary Source
  if (lesson.primary_source && lesson.primary_source.question) {
    items.push({
      id: 'primary_source',
      qNum: globalQNum++,
      label: lesson.primary_source.question.slice(0, 45),
    });
  }

  // 2. Sources (non-GCSE units)
  if (lesson.sources && lesson.sources.length > 0 && !isGCSE) {
    lesson.sources.forEach((s, idx) => {
      if (s.question) {
        items.push({ id: `source_${idx}`, qNum: globalQNum++, label: s.question.slice(0, 45) });
      }
    });
  }

  // 3. Narrative Blocks
  if (lesson.narrative_blocks) {
    lesson.narrative_blocks.forEach((b, bIdx) => {
      if (b.source && b.source.question) {
        items.push({
          id: `nb_${bIdx}_src`,
          qNum: globalQNum++,
          label: b.source.question.slice(0, 45),
        });
      }
      if (b.tasks) {
        b.tasks.forEach((t, tIdx) => {
          if (t && typeof t === 'object' && t.type !== 'vocab_match') {
            items.push({
              id: `nb_${bIdx}_t${tIdx}`,
              qNum: globalQNum++,
              label: (t.question || t.text || '').slice(0, 45),
            });
          }
        });
      }
    });
  }

  // 4. Pair Share (for all units except Great War)
  if (lesson.pair_share && !isGreatWar) {
    items.push({
      id: 'pair_share',
      qNum: globalQNum++,
      label: (lesson.pair_share.prompt || '').slice(0, 45),
    });
  }

  // 5. Standard Tasks
  if (lesson.tasks && lesson.tasks.length > 0) {
    lesson.tasks.forEach((t, tIdx) => {
      if (
        t.type !== 'gcse_exam_practice' &&
        t.type !== 'exam_practice' &&
        t.type !== 'drawing' &&
        t.type !== 'draw'
      ) {
        items.push({
          id: `task_${tIdx}`,
          qNum: globalQNum++,
          label: (t.question || t.text || '').slice(0, 45),
        });
      }
    });
  }

  // 6. Historian's Corner
  if (lesson.historians_corner && !lesson.historians_corner.textbook_only) {
    if (lesson.historians_corner.stretch_question) {
      items.push({
        id: 'historians_corner',
        qNum: globalQNum++,
        label: lesson.historians_corner.stretch_question.slice(0, 45),
      });
    }
  }

  // 7. Exam Practice Tasks
  if (lesson.tasks && lesson.tasks.length > 0) {
    lesson.tasks.forEach((t, tIdx) => {
      if (t.type === 'gcse_exam_practice' || t.type === 'exam_practice') {
        items.push({
          id: `task_${tIdx}`,
          qNum: globalQNum++,
          label: (t.question || t.text || '').slice(0, 45),
        });
      }
    });
  }

  // 8. Pair Share (for Great War)
  if (lesson.pair_share && isGreatWar) {
    items.push({
      id: 'pair_share',
      qNum: globalQNum++,
      label: (lesson.pair_share.prompt || '').slice(0, 45),
    });
  }

  // 9. Extended Writing
  if (lesson.extended && lesson.extended.question) {
    items.push({
      id: 'extended',
      qNum: globalQNum++,
      label: lesson.extended.question.slice(0, 45),
    });
  }

  // 10. GCSE Task
  if (lesson.gcse_task) {
    if (lesson.gcse_task.tasks && Array.isArray(lesson.gcse_task.tasks)) {
      lesson.gcse_task.tasks.forEach((t, tIdx) => {
        items.push({
          id: `gcse_task_${tIdx}`,
          qNum: globalQNum++,
          label: (t.question || t.text || '').slice(0, 45),
        });
      });
    } else if (lesson.gcse_task.topic) {
      items.push({
        id: 'gcse_task',
        qNum: globalQNum++,
        label: lesson.gcse_task.topic.slice(0, 45),
      });
    }
  }

  return items;
}

// Units to audit (academic curriculum across Years 7-11)
// Note: trip_ypres is a fully digital battlefield tour companion with no printed pupil workbooks
const targetUnits = [
  'water_and_sanitation',
  'medieval_england',
  'early_modern_world',
  'industrialisation_and_empire',
  'the_shoah',
  'post_war_britain',
  'great_war',
  'great_war_part2',
  'australia',
  'cold_war',
  'edexcel_medicine',
  'eee',
  'cme_new',
  'weimar_nazi_germany',
];

console.log('================================================================');
console.log('🔍 DUAL-NUMBERING SYNC TEST: Printed Workbooks vs Digital App');
console.log('================================================================\n');

let totalUnitsChecked = 0;
let totalLessonsChecked = 0;
let totalQuestionsChecked = 0;
let totalErrors = 0;

targetUnits.forEach((unitId) => {
  const uData = db[unitId]?.data;
  if (!uData || !uData.lessons) {
    console.warn(`⚠️ Warning: Unit ${unitId} missing from database.json. Skipping.`);
    return;
  }

  totalUnitsChecked++;
  let unitErrors = 0;

  uData.lessons.forEach((lesson, lIdx) => {
    totalLessonsChecked++;

    // Deep clone lesson to prevent mutating database
    const lClone = JSON.parse(JSON.stringify(lesson));
    assignQuestionNumbers(lClone, unitId);
    const expected = extractCanonicalWorkbookNumbering(lesson, unitId);

    // Collect actual digital question assignments
    const actual = [];
    if (lClone.primary_source?.question) {
      actual.push({ id: 'primary_source', qNum: lClone.primary_source.qNum });
    }
    if (
      lClone.sources &&
      !['cme_new', 'edexcel_medicine', 'eee', 'weimar_nazi_germany'].includes(unitId)
    ) {
      lClone.sources.forEach((s, idx) => {
        if (s.question) actual.push({ id: `source_${idx}`, qNum: s.qNum });
      });
    }
    if (lClone.narrative_blocks) {
      lClone.narrative_blocks.forEach((b, bIdx) => {
        if (b.source?.question) actual.push({ id: `nb_${bIdx}_src`, qNum: b.source.qNum });
        if (b.tasks) {
          b.tasks.forEach((t, tIdx) => {
            if (t && typeof t === 'object' && t.type !== 'vocab_match') {
              actual.push({ id: `nb_${bIdx}_t${tIdx}`, qNum: t.qNum });
            }
          });
        }
      });
    }
    if (lClone.pair_share) {
      actual.push({ id: 'pair_share', qNum: lClone.pair_share.qNum });
    }
    if (lClone.tasks) {
      lClone.tasks.forEach((t, tIdx) => {
        if (t && typeof t === 'object' && t.type !== 'drawing' && t.type !== 'draw') {
          actual.push({ id: `task_${tIdx}`, qNum: t.qNum });
        }
      });
    }
    if (lClone.historians_corner?.stretch_question && !lClone.historians_corner.textbook_only) {
      actual.push({ id: 'historians_corner', qNum: lClone.historians_corner.qNum });
    }
    if (lClone.extended?.question) {
      actual.push({ id: 'extended', qNum: lClone.extended.qNum });
    }
    if (lClone.gcse_task) {
      if (lClone.gcse_task.tasks && Array.isArray(lClone.gcse_task.tasks)) {
        lClone.gcse_task.tasks.forEach((t, tIdx) => {
          actual.push({ id: `gcse_task_${tIdx}`, qNum: t.qNum });
        });
      } else {
        actual.push({ id: 'gcse_task', qNum: lClone.gcse_task.qNum });
      }
    }

    totalQuestionsChecked += expected.length;

    // Check count parity
    if (actual.length !== expected.length) {
      unitErrors++;
      totalErrors++;
      console.error(`❌ [${unitId}] L${lIdx + 1} ('${lesson.title}'): Question count mismatch!`);
      console.error(
        `   Canonical printed: ${expected.length} questions | Digital runtime: ${actual.length} questions`,
      );
      return;
    }

    // Check individual question index alignment
    for (let i = 0; i < expected.length; i++) {
      const exp = expected[i];
      const act = actual.find((a) => a.id === exp.id);
      if (!act || act.qNum !== exp.qNum) {
        unitErrors++;
        totalErrors++;
        console.error(`❌ [${unitId}] L${lIdx + 1} item '${exp.id}':`);
        console.error(
          `   Expected printed Q${exp.qNum} vs Digital runtime Q${act ? act.qNum : 'NONE'}`,
        );
        console.error(`   Question text: "${exp.label}..."\n`);
      }
    }
  });

  if (unitErrors === 0) {
    console.log(
      `✅ [${unitId.padEnd(28)}] ${String(uData.lessons.length).padStart(2)} lessons synced`,
    );
  }
});

console.log('\n================================================================');
if (totalErrors === 0) {
  console.log(
    `🎉 SUCCESS: All ${totalUnitsChecked} curriculum units (${totalLessonsChecked} lessons, ${totalQuestionsChecked} questions) are 100% synchronized!`,
  );
  console.log('   Printed pupil materials for September match the digital app runtime.');
  console.log('================================================================\n');
  process.exit(0);
} else {
  console.error(`💥 FAILURE: ${totalErrors} question numbering discrepancies detected!`);
  console.error('   Please resolve the above digital mismatches before committing.');
  console.error('================================================================\n');
  process.exit(1);
}
