export const PEEL_DATA = {
  "subtopic_1_1": {
    "question": "Explain why Black Americans faced segregation and discrimination in the Southern states in the early 1950s.",
    "point": "One key reason why Black Americans faced segregation in the early 1950s was because Southern states legally enforced the Jim Crow system.",
    "evidence": "For example, under the Plessy v. Ferguson 'separate but equal' ruling of 1896, public facilities, schools, and transport were legally separated by race.",
    "explanation": "As a result, Black Americans were forced to use inferior facilities, which institutionalised racial discrimination and reinforced their second-class citizen status on a daily basis.",
    "link": "Therefore, legal segregation in the South was maintained by state laws to preserve white supremacy."
  },
  "subtopic_1_2": {
    "question": "Explain why school desegregation in the South was difficult to achieve between 1954 and 1958.",
    "point": "School desegregation in the South was extremely difficult to achieve because Southern state governors actively resisted federal rulings.",
    "evidence": "In September 1957, Governor Orval Faubus of Arkansas deployed the state's National Guard to physically block the Little Rock Nine from entering Central High School.",
    "explanation": "This action showed that local Southern politicians were willing to openly defy federal court orders to prevent racial integration in schools.",
    "link": "Consequently, this political resistance created a major constitutional crisis that required President Eisenhower to send federal troops to enforce integration."
  },
  "subtopic_1_3": {
    "question": "Explain why the Montgomery Bus Boycott was successful in ending transit segregation.",
    "point": "The Montgomery Bus Boycott was successful because of the highly disciplined organization and economic solidarity of the Black community.",
    "evidence": "Under the leadership of the MIA, around 90% of Black bus riders boycotted the buses for 381 days, setting up an efficient carpool system to travel.",
    "explanation": "This unity deprived the private bus company of 70% of its daily revenue, forcing them into financial crisis while the legal challenge moved through the courts.",
    "link": "Therefore, the combination of economic pressure and community discipline forced Montgomery transit to desegregate."
  },
  "subtopic_1_4": {
    "question": "Explain why white Southern opponents successfully resisted civil rights reforms in the late 1950s.",
    "point": "White Southern opponents successfully resisted civil rights reforms in the late 1950s by organizing collective political and economic opposition.",
    "evidence": "In 1956, over 100 Southern congressmen signed the Southern Manifesto to encourage defiance, while White Citizens' Councils used economic terror to fire civil rights supporters.",
    "explanation": "This coordinated response intimidated local activists and pressured school boards to delay integration indefinitely, rendering many reforms symbolic.",
    "link": "Thus, Southern opposition successfully preserved segregation through political obstruction and economic intimidation."
  },
  "subtopic_2_1": {
    "question": "Explain why student-led protests (sit-ins and Freedom Rides) succeeded in accelerating desegregation in the early 1960s.",
    "point": "Student-led protests in the early 1960s succeeded because they directly targeted the profits of segregated businesses and drew massive media attention.",
    "evidence": "In 1960, the Greensboro Sit-ins disrupted Woolworth's sales, losing the company $200,000, while the 1961 Freedom Rides exposed brutal white violence on television.",
    "explanation": "The national media coverage of peaceful students being attacked shocked the public and forced the federal government to intervene to protect interstate passengers.",
    "link": "As a result, direct action forced desegregation because it made the financial and political cost of segregation too high to maintain."
  },
  "subtopic_2_2": {
    "question": "Explain why the federal government was forced to pass the Civil Rights Act of 1964 and the Voting Rights Act of 1965.",
    "point": "The federal government was forced to pass major civil rights legislation in the mid-1960s due to the public outrage generated by Southern white brutality.",
    "evidence": "For example, the SCLC's 1963 Birmingham campaign and 1965 Selma march saw peaceful protesters attacked by police dogs, fire hoses, and tear gas on national television.",
    "explanation": "This televised brutality created immense domestic and international pressure, forcing President Johnson and Congress to intervene and pass the Civil Rights Act of 1964 and the Voting Rights Act of 1965.",
    "link": "Therefore, mass direct action forced the federal government to outlaw segregation and literacy tests to restore public order."
  },
  "subtopic_2_3": {
    "question": "Explain why the Black Power movement grew in popularity in the mid-to-late 1960s.",
    "point": "The Black Power movement grew rapidly in the late 1960s because many young Black Americans felt that mainstream non-violence had failed to address economic inequality.",
    "evidence": "Organizations like the Black Panthers, founded in 1966, rejected passive resistance, instead promoting armed self-defense and community social programs in northern ghettos.",
    "explanation": "This militant approach appealed to urban youth who were frustrated by persistent police brutality, poor housing, and high unemployment in Northern cities.",
    "link": "Consequently, the slow progress of legal reforms shifted the movement towards radical self-reliance and racial pride."
  },
  "subtopic_2_4": {
    "question": "Explain why major race riots erupted in Northern and Western US cities between 1965 and 1968.",
    "point": "Major race riots erupted in Northern cities in the late 1960s due to deep-seated frustrations over systemic police brutality and economic neglect.",
    "evidence": "Riots in Watts (1965) and Detroit (1967) resulted in dozens of deaths, and the 1968 Kerner Commission warned that America was dividing into two unequal societies.",
    "explanation": "Although Southern segregation was legally dismantled, Northern Black communities still suffered from housing discrimination, poverty, and aggressive policing, leading to explosive unrest.",
    "link": "Thus, the riots reflected a violent rejection of persistent social and economic inequality outside the South."
  },
  "subtopic_3_1": {
    "question": "Explain why the United States increased its involvement in Vietnam under President Eisenhower and President Kennedy.",
    "point": "The United States increased its involvement in Vietnam in the 1950s and early 1960s to prevent the spread of communism in Southeast Asia.",
    "evidence": "Following the defeat of the French in 1954, the US backed Ngo Dinh Diem's South Vietnamese government with millions of dollars in financial aid and military advisers.",
    "explanation": "Under the 'domino theory', US leaders believed that if South Vietnam fell to communism, neighboring countries like Laos and Cambodia would also fall.",
    "link": "Therefore, the fear of communist expansion led the US to commit itself to supporting a corrupt South Vietnamese regime."
  },
  "subtopic_3_2": {
    "question": "Explain why President Johnson escalated US military combat operations in Vietnam in 1964 and 1965.",
    "point": "President Johnson escalated US military combat operations in 1964 and 1965 because he believed South Vietnam was on the verge of collapsing.",
    "evidence": "Following the Gulf of Tonkin Incident in August 1964, Congress passed the Gulf of Tonkin Resolution, giving Johnson the power to wage war without a formal declaration.",
    "explanation": "Believing that airstrikes alone were not enough, Johnson deployed the first 3,500 combat marines in March 1965 to protect US airbases and prevent a communist victory.",
    "link": "As a result, the perceived threat to South Vietnamese stability led to the rapid escalation of US combat troops to over 200,000 by the end of 1965."
  },
  "subtopic_3_3": {
    "question": "Explain why US military search-and-destroy tactics struggled to defeat the Vietcong guerrilla forces.",
    "point": "US military search-and-destroy tactics struggled to defeat the Vietcong because they failed to match the VC's elusive guerrilla warfare and local support.",
    "evidence": "The Vietcong used a complex network of underground tunnels to hide from US patrols, set deadly booby traps, and blended into local peasant populations.",
    "explanation": "US operations relied on heavy bombing and chemical defoliants (like Agent Orange), which killed civilians and destroyed crops, driving the rural peasants to support the Vietcong.",
    "link": "Consequently, superior US technology and firepower were ineffective against a guerrilla enemy that possessed local support and infinite patience."
  },
  "subtopic_3_4": {
    "question": "Explain why President Nixon implemented the policy of Vietnamization while expanding the war into Cambodia and Laos.",
    "point": "President Nixon implemented the policy of Vietnamization to reduce US casualties while expanding the war to destroy communist supply lines in neighboring countries.",
    "evidence": "Between 1969 and 1970, Nixon began withdrawing US troops to hand over combat to the ARVN, but secretly ordered the invasion of Cambodia to destroy Vietcong bases.",
    "explanation": "While Nixon wanted to satisfy the American public by bringing troops home, he believed that South Vietnam could only survive if the Ho Chi Minh Trail and sanctuaries were destroyed.",
    "link": "Therefore, Nixon's strategy attempted to secure 'peace with honour' by strengthening the ARVN while intensifying military pressure across Indochina."
  },
  "subtopic_4_1": {
    "question": "Explain why opposition to the Vietnam War grew so rapidly within the United States between 1968 and 1971.",
    "point": "Opposition to the Vietnam War grew rapidly between 1968 and 1971 because events exposed government deception and the brutal reality of the conflict.",
    "evidence": "The publication of the My Lai Massacre in 1969 and the leak of the Pentagon Papers in 1971 shocked the public and revealed that officials had lied about the war's progress.",
    "explanation": "This created a massive 'credibility gap', convincing millions of Americans, particularly students, that the war was both unwinnable and morally corrupt, leading to massive protests like Kent State.",
    "link": "Consequently, the loss of moral legitimacy destroyed domestic public support for the war effort."
  },
  "subtopic_4_2": {
    "question": "Explain why a large section of the American public (the 'Silent Majority') supported Nixon's war policies.",
    "point": "A large section of the American public (the 'Silent Majority') supported Nixon's war policies because they felt alienated by the radicalism of anti-war protesters.",
    "evidence": "In a televised speech in November 1969, Nixon appealed to the moderate, patriotic citizens who supported his goal of 'peace with honour' rather than immediate withdrawal.",
    "explanation": "Many working-class Americans felt that the anti-war movement was unpatriotic, lawless, and disrespectful to US soldiers, which Nixon successfully exploited for political support.",
    "link": "Thus, Nixon maintained political power by positioning himself as the defender of traditional values and public order against radical protesters."
  },
  "subtopic_4_3": {
    "question": "Explain why South Vietnam collapse so quickly after the withdrawal of US troops in 1973.",
    "point": "South Vietnam collapsed rapidly in 1975 because it was economically and militarily crippled after the withdrawal of US support.",
    "evidence": "Following the 1973 Paris Peace Accords, US combat troops withdrew, and in 1974, Congress cut military and financial aid to South Vietnam by over 50%.",
    "explanation": "Without US air support and funding, the ARVN suffered from low morale, ammunition shortages, and corruption, making them unable to resist the massive North Vietnamese invasion of 1975.",
    "link": "Therefore, the complete withdrawal of US military power left South Vietnam vulnerable to rapid defeat."
  },
  "subtopic_4_4": {
    "question": "Explain why the United States ultimately failed to achieve its objectives in Vietnam.",
    "point": "The United States ultimately failed in Vietnam because it underestimated the determination of the communist forces and could not win the support of the Vietnamese peasants.",
    "evidence": "The Vietcong and North Vietnamese viewed the war as a nationalist struggle for independence, losing over a million soldiers but refusing to surrender, even after massive US bombings.",
    "explanation": "In contrast, the US was supporting a corrupt, unpopular South Vietnamese government, and US military tactics (such as search-and-destroy and chemical defoliants) alienated the local population.",
    "link": "Consequently, the US could not defeat a highly motivated enemy that had the support of its own people."
  }
};
