const fs = require('fs');
const path = require('path');

const dataPath = path.resolve(__dirname, '../edexcel_medicine/data.js');
let fileContent = fs.readFileSync(dataPath, 'utf8');

const q4NotebookLM = {
  0: {
    q: "Explain why there was so little progress in understanding the causes of disease in the medieval period (c1250–c1500). (12 marks)",
    a: "The primary reason why medical understanding of disease causation remained stagnant during the medieval period was the absolute control of the Catholic Church over medical education and university curricula. Because the Church maintained a monopoly on libraries, book production, and the copying of manuscripts, it strictly promoted the classical writings of Galen—whose theories of a balanced, purposeful \"Creator\" and the human soul aligned perfectly with Christian creation theology. Consequently, the Church actively discouraged any practical experimentation or scientific inquiry that might challenge Galen’s anatomical or humoural errors, going so far as to imprison independent scholars like Roger Bacon who advocated for experimental research.<br><br>This meant that trainee physicians at medical universities like Oxford and Cambridge spent their seven to ten years of study memorising ancient texts rather than treating patients, while rare human dissections were used strictly as demonstrations to prove Galen’s books were correct rather than to make new discoveries.<br><br>As a result, medieval medical thinking was trapped in a cycle of religious conformity and uncritical respect for ancient authority, ensuring that the unscientific Theory of the Four Humours remained the unchallenged medical standard for over two centuries."
  },
  1: {
    q: "Explain why bleeding and purging were such common treatments in the medieval period (c1250–c1500). (12 marks)",
    a: "Bleeding and purging were widely used as standard treatments in medieval England because they were logical, rational clinical therapies directly rooted in the universally accepted Theory of the Four Humours. Developed by Hippocrates and Galen, this theory taught that good health was maintained only when the body's four core fluids (blood, phlegm, yellow bile, and black bile) were in perfect balance, and that any illness was the direct result of an internal fluid excess or deficiency.<br><br>This meant that when a patient exhibited symptoms—such as sneezing excess phlegm during a winter cold or coughing up blood—physicians broke down each symptom separately as an imbalance that required active physical extraction to restore harmony. Consequently, medical practitioners regularly prescribed bloodletting (phlebotomy via cutting a vein, applying leeches, or cupping) and digestive purges (using herbal emetics or laxatives) to physically drain the excess humours from the patient's body.<br><br>Because these treatments matched what people could observe with their own eyes—such as the sweating out of a fever or the vomiting of bile—they felt highly effective to both doctors and patients, which solidified their dominant status as the primary \"rational\" remedies of the era."
  },
  2: {
    q: "Explain why the Black Death spread so rapidly in Britain in 1348. (12 marks)",
    a: "The rapid and devastating transmission of the Black Death in 1348 was heavily accelerated by the total lack of correct scientific knowledge regarding infectious pathogens, which led medieval authorities and citizens to employ counterproductive preventative measures. Because people had no concept of germs or the microscopic bacteria (Yersinia pestis) carried by flea-bitten rats, they blamed the epidemic on supernatural planetary alignments or the presence of corrupt, bad air known as miasma.<br><br>This led to a complete failure to implement effective biological quarantine measures, with desperate local populations huddling together in large daily religious processions and crowded church services to beg God for forgiveness. Similarly, religious flagellants traveled barefoot between towns publicly whipping themselves to show penance, which actively carried the highly contagious flea-borne and airborne pneumonic pathogens directly into previously uninfected rural communities.<br><br>As a result, these crowded, unhygienic religious gatherings turned into biological hotspots, allowing the plague to multiply unchecked and ultimately kill an estimated 40% of the English population in just two years."
  },
  3: {
    q: "Explain why the Renaissance period (c1500–c1700) was a period of rapid progress in anatomical knowledge. (12 marks)",
    a: "The rapid acceleration of anatomical knowledge during the Medical Renaissance was driven primarily by the invention of the printing press (c.1440), which permanently transformed the speed and accuracy with which scientific ideas were communicated. Prior to the press, medical texts had to be laboriously copied by hand by monastic scribes, making them incredibly rare, highly expensive, and prone to severe copying errors and anatomical distortions.<br><br>This technological bottleneck was shattered when Johannes Gutenberg's moveable type allowed pioneering anatomists like Andreas Vesalius to supervise the cheap, rapid, and standardized mass-production of identical scientific books. This meant that Vesalius’s landmark work on human dissection, De Humani Corporis Fabrica (1543), could be distributed simultaneously to universities across Europe containing his exceptionally detailed, mathematically precise anatomical woodcuts with no risk of copying errors.<br><br>Consequently, medical students no longer had to rely on corrupt translations of Galen's texts; they could use Vesalius's standardized drawings and printed \"fugitive sheets\" with layered paper flaps to study correct internal skeletal, muscular, and vascular structures, establishing dissection as a fashionable, practical, and highly progressive discipline."
  },
  4: {
    q: "Explain why there was little change in medical treatments during the Renaissance period (c1500–c1700), despite new anatomical discoveries. (12 marks)",
    a: "Daily medical treatments experienced very little change during the Renaissance because the era's major anatomical and physiological breakthroughs had no direct, practical clinical application for treating sick patients. While pioneers like Andreas Vesalius disproved Galen’s skeletal errors and William Harvey proved the circulation of blood in 1628, these discoveries did not explain the underlying biological causes of disease.<br><br>This meant that while a physician might now understand that the heart acted as a muscular pump rather than blood being absorbed by the tissues, they still lacked microscopes powerful enough to see microscopic bacteria or prove how pathogens entered the body. Consequently, because there was no alternative scientific framework to replace classical medicine, both the general public and professional physicians clung to the familiar Theory of the Four Humours as the only logical explanation for daily illnesses.<br><br>As a result, when royal doctors gathered in 1685 to treat the critically ill King Charles II, their lack of a modern germ-based treatment forced them to fall back on traditional medieval therapies, prescribing the same harmful bleeding, purging, and blistering techniques that had been used for centuries."
  },
  5: {
    q: "Explain why the government’s response to the Great Plague of 1665 was more effective than its response to the Black Death of 1348. (12 marks)",
    a: "The response to the Great Plague of 1665 was far more effective because the central government and municipal authorities abandoned their traditional medieval inactivity and took direct, highly organized administrative responsibility to prevent the spread of disease. During the Black Death of 1348, the king's government collected no taxes for public health and possessed very little administrative power, leaving town mayors entirely unequipped to enforce quarantine or restrict travel.<br><br>In contrast, in 1665, local officials strictly enforced King Charles II’s royal decree through structured, state-funded containment schemes. This led directly to the Lord Mayor of London hiring poor citizens as specialized municipal officers, including watchmen to board up and guard infected households for a compulsory 28-day quarantine, and searchers to systematically locate and remove plague corpses for burial in mass graves outside the city walls.<br><br>As a result of this rigorous administrative enforcement and the publication of weekly Bills of Mortality, the government was able to monitor hot spots, ban large gatherings like theaters, and restrict the movement of infected citizens, demonstrating a level of structured disease prevention that did not exist in 1348."
  },
  6: {
    q: "Explain why Louis Pasteur’s Germ Theory (1861) was a major turning point in medicine. (12 marks)",
    a: "Louis Pasteur's publication of Germ Theory in 1861 represented a monumental turning point in medicine because it permanently disproved the unscientific theory of spontaneous generation, establishing the true biological cause of decay and infectious disease. For centuries, medical progress had been entirely blocked because scientists believed that microbes naturally generated from decaying organic matter, meaning they viewed bacteria as a symptom of decay rather than its cause.<br><br>By using his elegant swan-neck flask experiments to prove that sterile liquids remained fresh unless exposed to airborne microbes, Pasteur scientifically demonstrated that microscopic pathogens cause disease. This led to a profound paradigm shift, turning medicine away from unscientific guesswork about humours or miasmas toward a rational, evidence-based focus on identifying and destroying specific pathogens.<br><br>As a result, Germ Theory provided the essential scientific blueprint that enabled subsequent, life-saving breakthroughs, including Robert Koch’s isolation of the tuberculosis bacillus in 1882, Joseph Lister’s development of antiseptic surgery, and the creation of targeted chemical vaccinations."
  },
  7: {
    q: "Explain why Joseph Lister's development of carbolic acid was so significant in the history of surgery. (12 marks)",
    a: "Joseph Lister’s development of carbolic acid in 1865 was highly significant because it systematically resolved the devastating problem of post-operative infection, which had previously made surgery a fatal last resort. In the mid-nineteenth century, while anesthetics had solved the problem of pain, surgical mortality actually rose because surgeons operated in unwashed clothes and used dirty instruments, carrying deadly bacteria deep into open wounds.<br><br>By applying Pasteur's Germ Theory (1861), Lister realized that post-operative sepsis was caused by invisible airborne microbes entering open flesh. Consequently, he developed a complete antiseptic regime using carbolic acid to wash his hands, sterilize surgical tools, soak patient bandages, and continuously mist the operating theater air.<br><br>This resulted in a dramatic drop in surgical mortality rates in his wards from 46% to 15%, physically proving the validity of Germ Theory in clinical practice. This led directly to surgeons being able to perform much longer, highly complex, and previously impossible internal operations safely, while laying the intellectual foundations for the transition to entirely sterile, aseptic surgical environments by 1900."
  },
  8: {
    q: "Explain why there was rapid progress in public health in the second half of the nineteenth century (c1850–c1900). (12 marks)",
    a: "A key factor driving rapid progress in public health during the late nineteenth century was a major political shift—namely, the passing of the 1867 Reform Act, which forced the British government to abandon its traditional \"laissez-faire\" policy. Prior to 1867, the government maintained a policy of non-interference, passing only optional (\"permissive\") public health acts because wealthy, tax-paying voters refused to pay local rates to clean up working-class slums.<br><br>The 1867 Reform Act changed this political landscape by giving working-class men in towns the right to vote for the first time. This meant that to win elections, politicians had to directly address the horrific living conditions of the urban working class, who suffered the most from dirty water and lack of sanitation.<br><br>This political pressure resulted in the landmark 1875 Public Health Act, which completely abandoned laissez-faire by making it compulsory for all local town councils to provide clean drinking water, dispose of sewage, build public toilets, and employ sanitary inspectors."
  },
  9: {
    q: "Explain why the discovery of the structure of DNA was a significant breakthrough in understanding the causes of illness. (12 marks)",
    a: "The discovery of the double-helix structure of DNA in 1953 by James Watson, Francis Crick, and Rosalind Franklin was highly significant because it unlocked a completely new genetic paradigm of medicine, allowing doctors to identify the internal, hereditary causes of non-communicable diseases. Prior to the mid-twentieth century, medical causation was dominated by Pasteur's Germ Theory, which was structurally unable to explain why some babies were born with debilitating conditions or why healthy adults developed chronic, non-infectious illnesses.<br><br>By decoding the human genetic blueprint, this molecular breakthrough allowed scientists to look inside the human cell and understand how specific instructions are passed from parents to offspring. This led directly to the launch of the Human Genome Project (1990–2003), which successfully mapped all three billion chemical base pairs in human DNA.<br><br>As a result, modern medical science has been able to identify the specific mutated or faulty genes responsible for hereditary conditions—such as cystic fibrosis, Down's syndrome, and haemophilia—while enabling predictive screening tests (like checking for mutated BRCA1/2 genes) to identify a patient's risk of developing chronic illnesses like breast cancer long before any physical symptoms manifest."
  },
  10: {
    q: "Explain why there was rapid progress in the development of penicillin in the 1940s. (12 marks)",
    a: "The rapid development of penicillin from a laboratory curiosity into a mass-produced, life-saving drug was driven primarily by the institutional intervention of the United States Government under the urgent pressures of the Second World War. Although Alexander Fleming discovered the antibacterial properties of the mold by accident in 1928, and Howard Florey and Ernst Chain successfully purified the active compound at Oxford in 1940, they lacked the immense funding and industrial capability required to produce it in large quantities.<br><br>This production bottleneck was solved when the US entered the war in December 1941 and realized penicillin's immense military value for treating infected battlefield wounds and preventing fatal gas gangrene. Consequently, the US Government intervened on an unprecedented scale, providing massive federal grants to Florey's team and funding American chemical companies to develop giant deep-fermentation tanks.<br><br>This wartime mobilization led directly to a manufacturing revolution, scaling up production from virtually nothing to over 2.3 million doses in time to treat Allied casualties on D-Day in June 1944, proving that government-backed industrial technology was essential to turning scientific research into a universally accessible cure."
  },
  11: {
    q: "Explain why the British government took a more active role in preventing disease in the period c1900–present. (12 marks)",
    a: "A major reason why the British government took a highly active, compulsory role in preventing disease after 1900 was the astronomical rise in the cost of running the National Health Service (NHS), which made preventative medicine far more cost-effective than clinical treatment. In the late twentieth and early twenty-first centuries, as high-tech diagnostic scans, specialized drug therapies, and complex surgical operations became incredibly expensive, treating chronic, non-communicable lifestyle illnesses placed an unsustainable financial burden on taxpayers.<br><br>Consequently, the government abandoned any remaining \"laissez-faire\" attitudes and realized that actively preventing disease was a financial necessity to safeguard the state’s resources. This led directly to the launch of aggressive, state-funded lifestyle campaigns—such as Public Health England's digital Change4Life campaign to combat obesity and Type 2 diabetes—alongside highly coercive, compulsory legislation.<br><br>As a result, the state utilized its legal authority to force behavioral changes, passing consecutive laws to ban television cigarette adverts in 1965, implement the 2007 ban on smoking in enclosed public workplaces, and levy sugar taxes on soft drinks to actively prevent chronic diseases before they required expensive hospital care."
  },
  12: {
    q: "Explain why the creation of the National Health Service (NHS) in 1948 improved public health in Britain. (12 marks)",
    a: "The launch of the National Health Service (NHS) on 5 July 1948 led to an immediate and massive improvement in public health because it permanently removed the prohibitive financial barriers that had historically prevented the poorest sectors of society from accessing medical treatment. Prior to 1948, despite major pharmaceutical and scientific breakthroughs, millions of working-class citizens, particularly women and children, could not afford GP consultations, medicines, or hospital stays, relying instead on traditional home remedies or charitable voluntary hospitals of variable quality.<br><br>By nationalizing all British hospitals and providing healthcare that was entirely free at the point of delivery, funded through national taxation, the government ensured that medical care was distributed based on clinical need rather than wealth. This meant that the general population gained equal, universal access to trained General Practitioners (GPs), professional nursing, and advanced surgeries.<br><br>This led directly to the highly successful, coordinated delivery of national preventative schemes—including free childhood vaccination programs against diphtheria and polio—which rapidly dropped infant mortality rates and significantly raised the nation's average life expectancy."
  }
};

const startIndex = fileContent.indexOf('{');
const endIndex = fileContent.lastIndexOf('}');

const prefix = fileContent.substring(0, startIndex);
const suffix = fileContent.substring(endIndex + 1);
const jsonStr = fileContent.substring(startIndex, endIndex + 1);

let data = eval('(' + jsonStr + ')');

for (let i = 0; i <= 12; i++) {
  if (data.lessons[i] && data.lessons[i].gcse_task && data.lessons[i].gcse_task.tasks) {
    // Find the 12-mark question by matching parts of the string
    let targetTask = data.lessons[i].gcse_task.tasks.find(t => t.text.includes("Explain why") || t.text.includes("12-mark"));
    if (!targetTask) {
       // Just take the first one if not found
       targetTask = data.lessons[i].gcse_task.tasks[0];
    }
    
    if (targetTask) {
      targetTask.text = q4NotebookLM[i].q;
      targetTask.model = q4NotebookLM[i].a;
    }
  }
}

const newJsonStr = JSON.stringify(data, null, 2);
const newContent = prefix + newJsonStr + suffix;

fs.writeFileSync(dataPath, newContent, 'utf8');
console.log('Successfully injected and paragraph-split NotebookLM Q4 answers into Core Medicine using AST/eval logic!');
