const fs = require('fs');
const path = require('path');

const dataPath = path.resolve(__dirname, '../edexcel_medicine/data.js');
let dataString = fs.readFileSync(dataPath, 'utf8');

// Convert to commonjs
let tempFile = dataString.replace('export const unitData = ', 'module.exports = ');
fs.writeFileSync(path.resolve(__dirname, 'temp_data3.js'), tempFile);
delete require.cache[require.resolve('./temp_data3.js')];
const unitData = require('./temp_data3.js');

const extractedExamsPath = path.resolve(__dirname, 'extracted_exams.json');
const extractedExams = JSON.parse(fs.readFileSync(extractedExamsPath, 'utf8'));

const ktToLessonIndex = {
  "1.1": 0, "1.2": 1, "1.3": 2,
  "2.1": 3, "2.2": 4, "2.3": 5,
  "3.1": 6, "3.2": 7, "3.3": 8,
  "4.1": 9, "4.2": 10, "4.3": 11, "4.4": 12
};

const newModels = {
  // KT1.1 (12 marks) - 3 paragraphs
  "1.1": `<strong>Grade 9 Model Answer (12 marks):</strong><br><br>One reason there was so little change was the power and influence of the Church. During the Middle Ages, the Catholic Church controlled medical training in universities and the copying of books in monasteries. The Church promoted the ancient ideas of Galen because his theory that the human body was perfectly designed fit seamlessly with the Christian belief in a single Creator. Therefore, the immense power and authority of the Church meant there was so little change in ideas, as anyone who dared to question Galen was seen as committing heresy and challenging God Himself, preventing any new medical theories from being developed.<br><br>A second reason for the lack of change was the reliance on book learning and a deep respect for tradition. In medieval society, a good physician was judged by how many books they had read, rather than how many patients they had successfully treated. Medical education was entirely based on reading the texts of Hippocrates and Galen rather than observing patients or experimenting. Even when dissections were occasionally carried out, they were only used to prove Galen right, not to discover new ideas. Consequently, this absolute respect for tradition led to so little change in ideas, as physicians were trained to blindly accept ancient texts as unquestionable facts rather than investigating new causes of disease.<br><br>A final reason was the lack of science and technology. In the period c1250–c1500, the microscope had not yet been invented. Furthermore, the printing press was only invented towards the end of this period (c.1440), meaning that for most of the Middle Ages, the Church had a monopoly on writing and distributing information. Ultimately, this lack of scientific technology meant there was so little change, as physicians physically did not have the equipment required to discover microbes or the means to share new ideas widely, leaving them with no choice but to continue believing in the Four Humours and miasma.`,

  // KT1.2 (16 marks) - 3 paragraphs and a conclusion
  "1.2": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I somewhat agree that the Theory of the Four Humours was the main idea about the cause of disease in the Middle Ages, but there were other equally important beliefs, such as supernatural causes. On the one hand, the Four Humours was the dominant scientific theory. Created by Hippocrates and developed by Galen, it stated that the body contained four liquids and illness occurred when they became unbalanced. This theory was heavily promoted by the Catholic Church because Galen's idea that the body was perfectly designed fit well with the Christian belief in a Creator. Because the Church controlled medical education at universities, all physicians were trained to believe the Four Humours was the absolute truth.<br><br>However, supernatural beliefs were arguably just as important for the average person. The vast majority of people were highly religious and believed that disease was a direct punishment from God for their sins. When the Black Death struck in 1348, people did not blame unbalanced humours; they blamed God's anger and responded by praying and fasting. Furthermore, astrology was also a major belief. Physicians regularly consulted zodiac charts and believed that the misalignment of the planets was a primary cause of major epidemics.<br><br>Finally, everyday people strongly believed in the Miasma theory—the idea that disease was caused by bad air filled with foul smells from swamps or unwashed bodies. This was often seen as a more practical explanation for localized outbreaks than the complex Four Humours.<br><br>In conclusion, while the Four Humours was the main 'official' medical theory taught to physicians, I only partially agree with the statement. For the vast majority of ordinary people, supernatural causes (God and astrology) and miasma were the most common and important explanations for why they got sick.`,

  // KT1.3 (16 marks) - 3 paragraphs and a conclusion
  "1.3": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I strongly disagree that there was rapid change in the treatment of disease during the Renaissance. While there were significant discoveries in anatomy, everyday treatments remained remarkably similar to the medieval period. On the one hand, there were major scientific breakthroughs. The most significant was Andreas Vesalius, who published 'The Fabric of the Human Body' in 1543. Vesalius proved Galen wrong on hundreds of points (such as the jaw bone being one bone, not two). This was a major change because it encouraged other doctors to dissect bodies themselves and question ancient texts, laying the foundation for modern anatomy.<br><br>However, despite these anatomical discoveries, medical treatments did not change at all. The vast majority of physicians still believed in the Theory of the Four Humours. Because they did not know about germs, they continued to prescribe medieval treatments like bloodletting, purging, and herbal remedies. William Harvey proved that blood circulates around the body in 1628, but this discovery had absolutely no impact on everyday medical treatment because blood transfusions were not yet possible, and doctors still relied on the Humours to cure sickness.<br><br>Furthermore, supernatural treatments remained incredibly popular throughout the Renaissance. During the Great Plague of 1665, people still relied on prayer, fasting, and carrying lucky charms to ward off the disease, just as they had done during the Black Death 300 years earlier. Miasma also remained a dominant theory, with people lighting fires and smoking tobacco to 'purify' the air.<br><br>In conclusion, I completely disagree with the statement. While the Renaissance saw rapid change in anatomical knowledge thanks to figures like Vesalius and Harvey, there was virtually no change in the actual treatment of disease, because physicians still fundamentally believed in the Four Humours and miasma.`,

  // KT2.1 (12 marks) - 3 paragraphs
  "2.1": `<strong>Grade 9 Model Answer (12 marks):</strong><br><br>One reason for the rapid change was the invention of the printing press (c.1440). In the medieval period, the Church controlled the copying of books and could suppress any new ideas that challenged Galen. However, the printing press allowed scientists like Vesalius to mass-produce their anatomical drawings and share their findings across Europe rapidly. This meant that new medical theories could be spread faster than ever before, completely removing the Church's monopoly on medical education and allowing physicians to read about new discoveries.<br><br>A second reason was the foundation of the Royal Society in 1660. The Royal Society received a royal charter from King Charles II, which gave them incredible prestige. Their motto, 'Take nobody's word for it', actively encouraged scientists to challenge ancient ideas like the Four Humours and conduct their own experiments. They published a scientific journal called 'Philosophical Transactions', which allowed doctors across Europe to share their research, significantly accelerating the pace of medical discovery.<br><br>A final reason was the work of individual geniuses like Thomas Sydenham. Known as the 'English Hippocrates', Sydenham published 'Observationes Medicae' in 1676. He argued that doctors should not rely on ancient books, but should closely observe the patient's symptoms and record them. He also theorized that diseases were like plants with different species, meaning they required specific cures rather than the universal treatments of bleeding and purging. His emphasis on practical observation caused a rapid change in how illnesses were diagnosed.`,

  // KT2.2 (16 marks) - 3 paragraphs and a conclusion
  "2.2": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I disagree with the statement. While individuals like Vesalius were crucial for correcting anatomical mistakes, the invention of the printing press was arguably the most significant factor because it allowed those individual discoveries to actually spread and change medical education. On the one hand, individuals were vital for challenging the old ideas. Andreas Vesalius dissected human bodies himself and proved Galen wrong on over 300 points, such as proving the human jaw is one bone, not two. By publishing 'The Fabric of the Human Body', he single-handedly revolutionized anatomy and encouraged others to dissect for themselves.<br><br>However, without the printing press, Vesalius's work would have had very little impact. In the medieval period, the Church controlled the copying of books, meaning any text that challenged Galen would simply not have been copied. The printing press allowed Vesalius's highly detailed anatomical drawings to be mass-produced accurately and distributed across Europe. The printing press was the true engine of the Renaissance, as it completely removed the Church's ability to censor new ideas.<br><br>Furthermore, institutions like the Royal Society were also incredibly significant. Founded in 1660, the Royal Society provided a centralized hub for scientists to meet, conduct experiments, and share their findings in their journal, 'Philosophical Transactions'. This institutional support gave scientific research credibility and encouraged a culture of challenging ancient texts, which was essential for destroying the dominance of the Four Humours.<br><br>In conclusion, I disagree that individuals were the most significant factor. While brilliant individuals provided the discoveries, it was the printing press that was the most significant factor because it allowed those discoveries to bypass Church control and reach universities across the continent, sparking the medical Renaissance.`,

  // KT2.3 (16 marks) - 3 paragraphs and a conclusion
  "2.3": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I partially agree with the statement. William Harvey's discovery of the circulation of the blood was a massive turning point in anatomical understanding, but it had almost no practical impact on everyday medical treatment during the Renaissance. On the one hand, Harvey's discovery in 1628 completely destroyed Galen's ancient theories. Galen had taught that the liver constantly manufactured new blood which was burned up in the muscles. By dissecting cold-blooded animals and experimenting with human veins, Harvey proved that the heart acts as a pump, circulating the same blood in a one-way system. This was a monumental breakthrough that laid the foundation for modern surgery and anatomy.<br><br>However, despite the brilliance of his discovery, it did absolutely nothing to improve medical treatment at the time. Harvey himself admitted that his discovery had not helped him cure a single patient. Because doctors did not yet understand blood groups, early attempts at blood transfusions were disastrous and often killed the patient. Furthermore, because germs had not yet been discovered, doctors continued to use medieval treatments like bloodletting and purging.<br><br>The lack of high-tech equipment also limited the impact of Harvey's discovery. Harvey could not prove exactly how arteries and veins connected because microscopes were not yet powerful enough to see capillaries. It wasn't until Marcello Malpighi used a stronger microscope in 1661 that capillaries were finally observed, fully confirming Harvey's theory long after it was first published.<br><br>In conclusion, I partially agree. Harvey's discovery was the most significant *theoretical* breakthrough of the Renaissance, as it permanently destroyed Galen's authority on anatomy. However, because it could not be used to actually cure anyone, its *practical* significance was virtually non-existent until the 20th century when successful blood transfusions became possible.`,

  // KT3.1 (12 marks) - 3 paragraphs
  "3.1": `<strong>Grade 9 Model Answer (12 marks):</strong><br><br>One reason why the Germ Theory was so important was because it permanently destroyed the ancient theories of Miasma and Spontaneous Generation. Before 1861, doctors believed that rotting matter created microbes (Spontaneous Generation) or that 'bad air' caused disease (Miasma). Louis Pasteur's Germ Theory proved that the reverse was true: microbes in the air caused matter to rot, and these specific microbes were the true cause of disease. This completely revolutionized the medical understanding of illness and finally provided a scientifically accurate foundation for all future medical research.<br><br>A second reason for its importance was that it directly led to the development of antiseptics in surgery. Joseph Lister read Pasteur's work and realized that if microbes in the air caused flesh to rot, they must also be causing the lethal infections that killed surgical patients. In 1865, Lister started using carbolic acid to kill these germs during operations. This dramatically reduced the surgical death rate from infection and proved that Germ Theory had incredibly significant, life-saving practical applications.<br><br>A final reason was that it enabled Robert Koch to identify specific disease-causing microbes. Koch took Pasteur's theory and applied it directly to human diseases, successfully identifying the specific bacteria that caused Anthrax (1876), Tuberculosis (1882), and Cholera (1883). By identifying the specific germs, Koch paved the way for scientists to start developing targeted vaccines and chemical 'magic bullets' to hunt down and kill those exact microbes inside the human body.`,

  // KT3.2 (16 marks) - 3 paragraphs and a conclusion
  "3.2": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I disagree that Florence Nightingale was the most important individual in improving hospitals. While Nightingale vastly improved hygiene and the nursing profession, it was Louis Pasteur's Germ Theory that fundamentally transformed hospitals from places of rest into modern centers of scientific treatment. On the one hand, Nightingale's impact on hospital conditions was enormous. During the Crimean War (1854), she introduced strict hygiene measures—scrubbing floors, opening windows, and providing clean bedding—which dropped the death rate from 40% to 2%. When she returned to Britain, she promoted the 'Pavilion Plan' for hospital design and established the first professional nursing school in 1860, transforming nursing into a highly respected profession.<br><br>However, Nightingale's improvements were ultimately based on the incorrect 'miasma' theory. She believed disease was caused by bad air, which is why she focused heavily on ventilation. It was Louis Pasteur's Germ Theory (1861) that actually proved microbes caused disease. Pasteur's scientific breakthrough was far more important because it eventually forced hospitals to move beyond mere cleanliness and adopt strict aseptic techniques (like sterilizing instruments and wearing surgical gowns) to actively kill the specific germs causing infections.<br><br>Furthermore, the improvements in surgery by individuals like Joseph Lister and James Simpson were vital to transforming hospitals. Simpson's discovery of chloroform (1847) solved the problem of pain, and Lister's use of carbolic acid (1865) solved the problem of infection. These surgical breakthroughs allowed hospitals to perform complex, life-saving operations, permanently changing their purpose from 'care' to 'cure'.<br><br>In conclusion, I disagree with the statement. Nightingale was the most important individual for improving nursing and basic hygiene, but Pasteur's Germ Theory was the true catalyst for transforming hospitals into modern, scientifically-driven institutions capable of safely performing complex surgical cures.`,

  // KT3.3 (16 marks) - 3 paragraphs and a conclusion
  "3.3": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I partially agree that the discovery of Carbolic Acid was the most significant turning point, as it solved the biggest killer in surgery (infection), but Simpson's discovery of chloroform was the first essential step in making complex surgery possible. On the one hand, Joseph Lister's use of carbolic acid in 1865 was a monumental breakthrough. Before Lister, up to 50% of patients who survived the pain of surgery later died from gangrene and sepsis. By spraying carbolic acid in the operating theatre and soaking bandages in it, Lister directly applied Pasteur's Germ Theory to kill the microbes causing the infections. This drastically reduced the death rate and proved that surgery could be safe.<br><br>However, James Simpson's discovery of chloroform as an anaesthetic in 1847 was the first major barrier broken. Before anaesthetics, patients often died of clinical shock from the immense pain, and surgeons had to operate in a matter of seconds. Chloroform allowed patients to sleep peacefully through the procedure. This was incredibly significant because it gave surgeons the time required to attempt much longer, more complex internal operations that would have previously been impossible.<br><br>Furthermore, one could argue that Louis Pasteur's Germ Theory (1861) was the true underlying turning point. Lister's entire concept of using carbolic acid was completely reliant upon Pasteur's discovery that microbes in the air caused decay. Without Germ Theory, the development of antiseptics and the later move to aseptic surgery (using steam-sterilized instruments) would never have happened.<br><br>In conclusion, I partially agree. Carbolic acid was the most significant *practical* turning point because it solved the lethal problem of infection, but it was entirely reliant on the *scientific* turning point of Pasteur's Germ Theory, and would not have been possible without Simpson first conquering the barrier of pain.`,

  // KT4.1 (12 marks) - 3 paragraphs
  "4.1": `<strong>Grade 9 Model Answer (12 marks):</strong><br><br>One reason for the rapid progress in public health was the work of John Snow and the 1854 cholera epidemic. During the outbreak in Soho, London, Snow mapped the deaths and noticed they clustered around the Broad Street water pump. By removing the handle from the pump, the deaths stopped, proving that cholera was a waterborne disease, not caused by miasma. Although the government initially rejected his theory, Snow's undeniable statistical evidence paved the way for future investment in clean water supplies.<br><br>A second crucial reason was the 'Great Stink' of 1858. The River Thames had become dangerously polluted with raw sewage, and during a particularly hot summer, the smell became so overpowering that Parliament had to soak its curtains in chemicals. This direct physical threat finally broke the government's 'laissez-faire' (leave it alone) attitude. Terrified of the miasma, the government immediately gave Joseph Bazalgette £3 million to design and build a massive new sewer system for London, which drastically reduced waterborne diseases.<br><br>A final reason was the scientific proof provided by Louis Pasteur's Germ Theory (1861). Before 1861, local councils refused to pay for clean water because they didn't believe in microbes. Once Pasteur scientifically proved that germs caused disease, the government could no longer ignore the problem. This directly led to the 1875 Public Health Act, which legally forced all local councils to provide clean water, build sewers, and employ Medical Officers of Health, resulting in rapid nationwide progress in public health.`,

  // KT4.2 (16 marks) - 3 paragraphs and a conclusion
  "4.2": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I partially agree that the discovery of DNA was the most significant breakthrough, as it revolutionized our understanding of genetics, but the understanding of lifestyle factors has arguably saved more lives on a practical level. On the one hand, the discovery of the structure of DNA by Watson and Crick in 1953 was a monumental scientific turning point. For the first time, scientists could understand the actual cause of hereditary and genetic diseases, such as Down's Syndrome and cystic fibrosis, which Pasteur's Germ Theory could not explain. This breakthrough paved the way for the Human Genome Project, opening the door for modern gene therapy and highly targeted treatments.<br><br>However, the understanding of lifestyle factors has had a much more immediate and widespread impact on public health. In the mid-20th century, scientific research conclusively proved that smoking causes lung cancer, completely changing how the public viewed tobacco. Similarly, the modern understanding that poor diets and lack of exercise lead to obesity, Type 2 diabetes, and heart disease has allowed millions of people to actively prevent illness before it occurs.<br><br>Furthermore, advancements in high-tech diagnosis have been incredibly significant. In the modern period, doctors no longer have to guess what is wrong based on external symptoms. The invention of the MRI (1970s) and CT scans allows doctors to look inside the body and pinpoint the exact location of tumours or internal bleeding without making a single cut, vastly improving the speed and accuracy of diagnosis.<br><br>In conclusion, I partially agree. While the discovery of DNA was the most significant *scientific* breakthrough for understanding the human body, the discovery of how lifestyle factors cause disease has been a more significant *practical* breakthrough, empowering millions of people to actively change their habits and prevent fatal diseases.`,

  // KT4.3 (16 marks) - 3 paragraphs and a conclusion
  "4.3": `<strong>Grade 9 Model Answer (16 marks):</strong><br><br>I disagree that Alexander Fleming was the most important individual in the development of penicillin. While his initial discovery was vital, it was the work of Florey and Chain, combined with government funding, that actually turned it into a life-saving drug. It is true that Fleming was the first to discover penicillin in 1928. By chance, he noticed that a mould had grown on a petri dish and was actively killing the deadly Staphylococcus bacteria around it. He published his findings in a scientific journal in 1929. However, Fleming was a poor communicator and failed to secure funding to purify it, eventually abandoning his research and leaving it as a mere laboratory curiosity.<br><br>The most important individuals were actually Florey and Chain. In 1939, they read Fleming's forgotten paper and assembled a dedicated research team at Oxford University. Crucially, Chain managed to purify the mould into a usable drug, and Florey proved it worked by successfully curing mice, and later temporarily curing a human patient (Albert Alexander) in 1941. Without Florey and Chain's determination and brilliant chemistry, penicillin would never have progressed beyond Fleming's petri dish.<br><br>Furthermore, the role of institutions and governments was absolutely vital for mass production. Florey and Chain could not mass-produce the drug in Britain due to WWII. Florey travelled to America, where the US Government provided massive funding to chemical companies (like Pfizer) to grow penicillin in huge industrial vats. This meant that by D-Day in 1944, there was enough penicillin to treat every Allied casualty.<br><br>In conclusion, I disagree with the statement. Fleming provided the initial spark, but Florey and Chain were far more important because they proved it was a viable medicine, and the US government was the ultimate key to mass-producing it to save millions of lives.`,

  // KT4.4 (12 marks) - 3 paragraphs
  "4.4": `<strong>Grade 9 Model Answer (12 marks):</strong><br><br>One major reason for rapid progress in disease prevention after 1900 was government-funded mass vaccination campaigns. Following the success of the compulsory smallpox vaccine in the 19th century, the 20th-century government took active responsibility for national immunization. In the 1940s and 1950s, the government launched massive, nationwide campaigns to vaccinate children against deadly diseases like diphtheria and polio. By funding and organizing these campaigns at a national level, rather than leaving it to individual choice, the government successfully eradicated polio from the UK and drastically reduced child mortality.<br><br>A second reason was the introduction of strict government legislation to improve the environment, such as the Clean Air Acts. Following the Great Smog of London in 1952, which killed over 4,000 people due to severe respiratory issues, the government realized it had to intervene. The Clean Air Acts of 1956 and 1968 created 'smoke-free zones' and forced factories and homes to stop burning highly polluting coal. This proactive legislation drastically improved air quality and rapidly reduced the prevalence of respiratory diseases like bronchitis.<br><br>A final reason was the growing scientific understanding of lifestyle factors and the resulting government health campaigns. As scientific research proved undeniable links between behaviors and disease (e.g., smoking causing lung cancer, or poor diet causing diabetes), the government launched massive preventative campaigns. Examples include making cigarette advertising illegal, enforcing plain packaging, and launching the 'Sugar Tax' in 2018. Because treating these diseases is incredibly expensive for the NHS, the government rapidly progressed its prevention strategies to actively stop people from making unhealthy lifestyle choices in the first place.`
};

for (const kt in newModels) {
  const lessonIndex = ktToLessonIndex[kt];
  if (lessonIndex !== undefined && unitData.lessons[lessonIndex] && unitData.lessons[lessonIndex].extended) {
    // 1. Restore the correct Q2/Q1 from extracted_exams
    let correctQuestionText = null;
    if (extractedExams[kt]) {
      // Find the 12-mark or 16-mark question from extractedExams
      for (const item of extractedExams[kt]) {
        if (item.q.includes('12 marks') || item.q.includes('16 marks')) {
          correctQuestionText = item.q;
          break;
        }
      }
    }
    
    if (correctQuestionText) {
      // Remove any trailing " * Teacher Note on Exam Technique:" stuff that got bundled into the Q text originally
      let cleanQ = correctQuestionText.split('* Teacher Note')[0].trim();
      // Replace \n with <br> for bullet points
      cleanQ = cleanQ.replace(/\n\*\s/g, '<br>• ');
      unitData.lessons[lessonIndex].extended.question = cleanQ;
    }

    // 2. Inject the fully formatted Model Answer WITHOUT the teacher note
    unitData.lessons[lessonIndex].extended.model = newModels[kt];
  }
}

// Convert back to string format
const newString = 'export const unitData = ' + JSON.stringify(unitData, null, 2) + ';\n';
fs.writeFileSync(dataPath, newString);
console.log('Successfully injected 13 formatted Model Answers (3 paras / 4 paras) and REMOVED teacher notes.');
