const fs = require('fs');
const path = require('path');

const newSources = [
  {
    "enquiry": "the conditions of the trench system and the terrain at the Ypres Salient",
    "source_a": {
      "provenance": "Source A: From a letter sent by Private Arthur Higgins of the 2nd Battalion, Lancashire Fusiliers, to his sister in November 1917. He was stationed in the low-lying trenches near Passchendaele during the Third Battle of Ypres.",
      "content": "We are living in a frozen swamp, or rather a sea of thick, sucking mud. There are no proper communication trenches left here; the shells have smashed everything flat. To move anywhere, we have to scramble over slippery duckboards laid across deep craters. Yesterday, a man in our section slipped off the path into the waterlogged slime. It took four of us with ropes to pull him out before he sank completely. The damp cold gets right into your bones, and our feet are permanently wet and numb."
    },
    "source_b": {
      "provenance": "Source B: An official British Army photograph taken in October 1917, showing stretcher bearers transporting a wounded soldier near Hooge in the Ypres Salient.",
      "content": "The photograph shows a landscape completely devastated by heavy artillery bombardment. The ground is heavily churned up, containing massive, waterlogged shell craters that are filled to the brim with stagnant water and deep mud. No defined trench lines or vegetation are visible in the background. Four stretcher-bearers are struggling to walk through knee-deep mud while carrying a casualty on a wooden stretcher. They are using shoulder slings to support the weight of the stretcher as they navigate the slippery, uneven terrain."
    },
    "q8": {
      "question": "2 (a). How useful are Sources A and B for an enquiry into the conditions of the trench system and the terrain at the Ypres Salient? Explain your answer, using Sources A and B and your knowledge of the historical context. (8 marks)",
      "model": "Model Answer: Source A is highly useful for investigating the trench conditions and terrain at Ypres. In terms of content, the letter details how heavy shelling had destroyed the communication trenches, leaving a swamp-like terrain of waterlogged slime and deep mud where soldiers literally sank and suffered from wet, numb feet. This is supported by historical context; during the Third Battle of Ypres (Passchendaele) in late 1917, relentless rain combined with heavy artillery fire destroyed the natural drainage systems of Flanders, turning the clay soil into a quagmire. This extreme dampness led to thousands of cases of trench foot, which sometimes required amputation. The provenance enhances its utility; as a private letter from a soldier on the frontline, it provides an authentic, uncensored personal account of the daily physical suffering and environmental hazards. Although personal letters can be subjective or contain emotional exaggeration, this reflects the genuine psychological and physical toll of the Ypres terrain.\\n\\nSource B is also highly useful for this enquiry. Its content provides clear visual evidence of the devastating impact of the terrain, showing a landscape pulverized by shelling and covered in massive waterlogged craters. It also highlights the extreme difficulty of transporting casualties, showing four stretcher bearers struggling through knee-deep mud carrying a stretcher with shoulder slings. This is supported by historical context, as we know that in the thick mud of Ypres, standard two-man stretcher teams were completely inadequate. The army had to use teams of four, six, or even eight men to carry a single casualty, making the evacuation process dangerously slow. The delay in getting wounded men through this waterlogged terrain to Casualty Clearing Stations (CCS) often allowed fatal infections like gas gangrene and tetanus (caused by soil bacteria) to develop in wounds. The provenance is useful because it is an official contemporary photograph from October 1917, providing an accurate, real-time visual record of the Hooge sector during the offensive. While official photographs were sometimes staged or selected for censorship purposes to avoid showing horrific casualties, it remains highly useful for showing the actual state of the ground and the logistical difficulties medical staff faced."
    },
    "q4": {
      "question": "2 (b). How could you follow up Source A to find out more about the conditions of the trench system and the terrain at the Ypres Salient? In your answer, you must give the question you would ask and the type of source you could use. (4 marks)",
      "model": "Model Answer:\\n* Detail in Source A that I would follow up: 'The damp cold gets right into your bones, and our feet are permanently wet and numb.'\\n* Question I would ask: What measures and treatments did medical officers in the Ypres sector implement to reduce the high number of casualties caused by trench foot?\\n* What type of source I could use: RAMC medical records or war diaries of the 2nd Battalion, Lancashire Fusiliers from late 1917.\\n* How this might help answer my question: These official records would detail the specific preventative strategies used in the trenches (such as the distribution of dry socks and whale oil) and provide statistical data on how many men were evacuated with trench foot."
    }
  },
  {
    "enquiry": "the effects of the trench environment on soldiers' health (such as Trench Foot and Shell Shock)",
    "source_a": {
      "provenance": "Source A: From the personal diary of Lieutenant Henry Vance, serving with the 1st Battalion, Royal Warwickshire Regiment, near the Somme during the winter of December 1916.",
      "content": "We have been stuck in these waterlogged ditches for six days without a single dry stitch of clothing. Private Miller is in a terrible state; his feet are swollen to twice their size, completely numb and turning black at the toes. I ordered him to rub them with whale oil, but we ran out of dry socks days ago. Worse still is the mental state of young Davies. After the heavy bombardment last night, he began shaking uncontrollably, weeping, and has lost the ability to speak. He just stares blankly at the wall of the dugout, jumping violently at every distant blast. I had to have him led away to the dressing station as 'NYD Nervous'."
    },
    "source_b": {
      "provenance": "Source B: From an official report by Captain J. C. Dunn, a Medical Officer with the Royal Army Medical Corps (RAMC), compiled during his sanitary inspection of a frontline battalion in the Somme sector, December 1916.",
      "content": "The physical and mental exhaustion of the men is reaching a critical limit due to the winter conditions. In this battalion alone, over eighty cases of severe foot-rot (trench foot) have been recorded this week, primarily caused by prolonged standing in knee-deep water. Compulsory daily foot inspections have been ordered, and officers must ensure whale oil is vigorously rubbed into the skin. Additionally, twelve men have been evacuated with severe nervous tremors and mutism following heavy shelling. To prevent the spread of panic, these psychiatric cases are being classified as 'NYD.N' (Not Yet Diagnosed: Nervous) and are to be treated locally in France rather than evacuated home."
    },
    "q8": {
      "question": "2 (a). How useful are Sources A and B for an enquiry into the effects of the trench environment on soldiers' health? Explain your answer, using Sources A and B and your knowledge of the historical context. (8 marks)",
      "model": "Model Answer: Source A is highly useful for investigating the effects of the trench environment on soldiers' health. In terms of content, the source provides direct, first-hand evidence of both the physical and psychological toll of the trenches, detailing how standing in waterlogged ditches led to the physical rotting of trench foot (feet turning swollen, numb, and black) and how constant heavy bombardment caused severe shell shock (manifesting as uncontrollable shaking, weeping, and mutism). This is supported by historical context; we know that the freezing, wet winter of 1916 on the Somme destroyed trench drainage, forcing soldiers to stand in mud for days, which restricted blood flow and caused gangrenous trench foot. The provenance of Source A further enhances its utility; as a private diary entry written by a frontline officer, it provides an uncensored, emotionally raw, and immediate record of the daily suffering of his men. While personal diaries can be subjective, the description is highly typical of the conditions faced by troops on the Western Front at this time.\\n\\nSource B is also highly useful for this enquiry. Its content provides an invaluable official and statistical overview of the health crisis, showing that the environmental conditions led to a massive loss of manpower, with eighty cases of trench foot and twelve nervous evacuations in a single battalion in just one week. It also highlights the army's compulsory preventative measures, such as rubbing whale oil during daily inspections, and the official policy of classifying shell shock under the code 'NYD.N' to treat patients locally in France. This is supported by historical context; the British Army feared that shell shock was a contagious form of hysteria that would undermine morale and deplete the front lines, so they banned the term 'shell shock' and used 'NYD.N' (Not Yet Diagnosed: Nervous) so men could be rested and returned to duty quickly rather than receiving a 'Blighty' evacuation to Britain. The provenance of Source B makes it highly useful as it is an official report by a trained RAMC Medical Officer. Because he was directly responsible for the sanitation and health of the battalion, he had access to accurate medical registries and was in a prime position to provide a reliable, objective overview of these illnesses."
    },
    "q4": {
      "question": "2 (b). How could you follow up Source A to find out more about the effects of the trench environment on soldiers' health? In your answer, you must give the question you would ask and the type of source you could use. (4 marks)",
      "model": "Model Answer:\\n* Detail in Source A that I would follow up: 'After the heavy bombardment last night, he began shaking uncontrollably, weeping, and has lost the ability to speak... led away to the dressing station as NYD Nervous.'\\n* Question I would ask: How effective were the frontline psychiatric rest stations established by the RAMC in France at treating soldiers suffering from shell shock and returning them to active duty?\\n* What type of source I could use: RAMC medical admission and discharge registers, or war diaries from specialized neurological units on the Western Front.\\n* How this might help answer my question: These official records would provide statistical data on the percentage of 'NYD.N' casualties who successfully recovered and returned to their battalions after short-term rest, compared to those who had to be permanently evacuated to specialist hospitals in Britain."
    }
  },
  {
    "enquiry": "the types of wounds and injuries caused by high-explosive shells and shrapnel",
    "source_a": {
      "provenance": "Source A: From the diary of Captain Ronald Thornton, a surgeon working at No. 12 Casualty Clearing Station near Hazebrouck, during the Battle of Arras, April 1917.",
      "content": "Today has been a succession of horrors. The wounds from shellfire are shocking; the heavy explosives tear flesh to ribbons and shatter bone completely. Treated a young private whose thigh was mangled by shrapnel; the jagged metal fragments had driven muddy pieces of his woollen trousers deep into the muscle. These shrapnel wounds are jagged and filthy, unlike neat bullet holes. We also had several head injuries from soldiers caught in the open. Without their steel Brodie helmets, their skulls would have been completely pulverized."
    },
    "source_b": {
      "provenance": "Source B: From an official report on wartime casualties compiled by the British Army Medical Services, detailing wounds treated in the Somme sector between July and November 1916.",
      "content": "An analysis of casualties admitted to forward surgical stations indicates that high-explosive shells and shrapnel remain the primary cause of severe trauma, responsible for approximately 58% of all battlefield wounds. These artillery projectiles cause extensive tissue damage, compound fractures of the extremities, and deep penetration of foreign matter. Gunshot wounds from rifles and machine guns account for 39% of injuries. In contrast to bullet wounds, shrapnel-inflicted trauma is characterized by a high incidence of immediate contamination and muscle necrosis, frequently requiring radical surgical debridement or amputation to prevent systemic infection."
    },
    "q8": {
      "question": "2 (a). How useful are Sources A and B for an enquiry into the types of wounds and injuries caused by high-explosive shells and shrapnel on the Western Front? Explain your answer, using Sources A and B and your knowledge of the historical context. (8 marks)",
      "model": "Model Answer: Source A is highly useful for investigating the types of wounds caused by shellfire and shrapnel. In terms of content, the surgeon's diary describes how high explosives 'tear flesh to ribbons and shatter bone completely' and details how jagged shrapnel fragments carried contaminated woollen uniform fabric deep into human muscle tissue. It also notes that artillery shellfire caused devastating, fatal head injuries. This is supported by historical context; we know that shrapnel was particularly lethal because the metal dragged dirty pieces of the uniform, which were covered in soil containing gas gangrene and tetanus spores from the heavily fertilized Belgian and French farmlands, deep into wounds. It also matches our knowledge that head injuries were common before the introduction of the steel Brodie helmet in 1915, which reduced fatal head injuries by 80%. The provenance of Source A enhances its utility; written by an RAMC surgeon at a forward Casualty Clearing Station (CCS) during the Battle of Arras in April 1917, it provides an authentic, expert, and uncensored first-hand record of the clinical reality of blast injuries. Although personal diaries can be subjective, his professional observations of wound characteristics are highly accurate and reliable.\\n\\nSource B is also highly useful for this enquiry. Its content provides a valuable statistical and objective overview of the wound types, establishing that high explosives and shrapnel caused 58% of all wounds and explaining that these injuries were characterized by compound fractures and high rates of infection, compared to machine gun or rifle bullets which caused 39% of injuries. This is supported by historical context, as we know that the sheer volume of shrapnel-related tissue damage and subsequent gangrene infections forced military surgeons to abandon traditional antiseptic methods and develop radical preventative surgery, such as wound excision (debridement) or amputation. The provenance of Source B makes it extremely useful as it is an official report compiled by the British Army Medical Services. Because it is based on large-scale data from the Somme sector in 1916, it provides a highly representative and typical picture of Western Front casualties, serving as a reliable benchmark to verify the individual surgical observations made in Source A."
    },
    "q4": {
      "question": "2 (b). How could you follow up Source A to find out more about the types of wounds and injuries caused by high-explosive shells and shrapnel? In your answer, you must give the question you would ask and the type of source you could use. (4 marks)",
      "model": "Model Answer:\\n* Detail in Source A that I would follow up: 'the jagged metal fragments had driven muddy pieces of his woollen trousers deep into the muscle.'\\n* Question I would ask: How did RAMC medical officers combat the high rates of tetanus infections that resulted from muddy clothing being dragged into shrapnel wounds?\\n* What type of source I could use: RAMC medical registers or anti-tetanus serum logs from Casualty Clearing Stations in 1917.\\n* How this might help answer my question: These official logs would record the exact percentage of wounded soldiers who received the ATS inoculation and show whether it successfully prevented the onset of tetanus symptoms."
    }
  },
  {
    "enquiry": "the problems of transporting the wounded and the work of the RAMC and FANY",
    "source_a": {
      "provenance": "Source A: From the diary of Corporal Eleanor Vance, a volunteer driver with the First Aid Nursing Yeomanry (FANY), stationed near the Ypres Salient during the Third Battle of Ypres, September 1917.",
      "content": "We have been driving our motor ambulances back and forth from the dressing stations to the Casualty Clearing Station since dawn. The terrain is an absolute nightmare. The roads are entirely destroyed by shellfire, leaving deep, waterlogged craters and thick clay mud that reaches our axles. Several times my ambulance got bogged down, and we had to rely on passing soldiers to push us out. The poor wounded inside are severely shaken by the constant jolting, which must be excruciating for those with shattered limbs. The heavy rain is relentless."
    },
    "source_b": {
      "provenance": "Source B: From an article in the Journal of the Royal Army Medical Corps (RAMC), published in 1915, evaluating transport problems during the early stages of the war in northern France.",
      "content": "The evacuation of casualties from the firing line remains severely hampered by environmental and logistical difficulties. Stretcher-bearers must carry wounded men through narrow, muddy, zig-zag communication trenches under active shellfire, a process requiring up to six or eight men for a single casualty. Furthermore, horse-drawn ambulance wagons struggle on waterlogged roads, often worsening bone fractures due to violent shaking. The initial provision of motor ambulances was totally inadequate for the high casualty rates, forcing many walking wounded to make their own way back to railheads."
    },
    "q8": {
      "question": "2 (a). How useful are Sources A and B for an enquiry into the problems of transporting the wounded and the work of the RAMC and FANY? Explain your answer, using Sources A and B and your knowledge of the historical context. (8 marks)",
      "model": "Model Answer: Source A is highly useful for investigating the problems of transport and the work of the FANY. In terms of content, the diary details how FANY drivers navigated motor ambulances through waterlogged shell craters and deep mud near the Ypres Salient, and how the poor road conditions caused severe 'jolting' which worsened the suffering of wounded men. This is supported by historical context; we know that the terrain of the Ypres Salient was a marshy quagmire due to destroyed drainage systems and heavy autumn rain in 1917. This made transportation exceptionally difficult, often stalling the chain of evacuation and delaying vital surgery at the Casualty Clearing Stations (CCS). The provenance of Source A enhances its utility; as a contemporary private diary written by a FANY volunteer in September 1917, it offers a direct, first-hand, and uncensored account of the physical hazards and active frontline duties of women in the FANY, who were officially permitted to drive motor ambulances from January 1916.\\n\\nSource B is also highly useful for this enquiry. Its content provides a valuable overview of the transport problems across the whole evacuation route, explaining how narrow, zig-zag communication trenches slowed down stretcher bearers, how horse-drawn wagons on waterlogged roads worsened injuries, and how the initial lack of motor ambulances left many wounded stranded. This is supported by historical context, as we know that in 1914, the British military leadership sent no motor ambulances to France, relying instead on horse-drawn carriages that could not cope with the terrain or casualty numbers. Stretcher bearers faced extreme physical exhaustion, and trenches were constructed in a zig-zag pattern to prevent blasts from travelling down the line, which made carrying stretchers around corners very difficult, sometimes requiring up to eight men. The provenance of Source B makes it highly useful because it is a contemporary article from the official RAMC journal in 1915. Since it was written by RAMC medical professionals to analyze transport failures, it offers a reliable, expert, and highly objective assessment of early-war transport logistics."
    },
    "q4": {
      "question": "2 (b). How could you follow up Source A to find out more about the problems of transporting the wounded and the work of the RAMC and FANY? In your answer, you must give the question you would ask and the type of source you could use. (4 marks)",
      "model": "Model Answer:\\n* Detail in Source A that I would follow up: 'The poor wounded inside are severely shaken by the constant jolting, which must be excruciating for those with shattered limbs.'\\n* Question I would ask: How did the introduction of the Thomas splint in the chain of evacuation resolve the issue of wounded soldiers dying from blood loss and shock during rough ambulance transport?\\n* What type of source I could use: Official British Army medical statistics or RAMC casualty reports comparing leg wound survival rates from 1915 and 1916.\\n* How this might help answer my question: Comparing survival rates before and after December 1915 (when the Thomas splint was introduced) would demonstrate whether keeping leg fractures rigid during bumpy transport reduced deaths from internal bleeding and shock from 80% to under 20%."
    }
  },
  {
    "enquiry": "new medical techniques used to deal with infections and injuries on the Western Front",
    "source_a": {
      "provenance": "Source A: From a personal journal written by Major Richard Sterling, a surgeon working with the Royal Army Medical Corps (RAMC) at a Casualty Clearing Station during the Battle of the Somme, August 1916.",
      "content": "The heavily fertilized French soil is our greatest enemy; it is crawling with gas gangrene and tetanus spores. Today we treated deep wounds by performing radical excision, cutting away every shred of dead, blackened muscle and dirty uniform fabric before infection could spread. Standard carbolic antiseptics are useless against this gangrene. For the deeper lacerations, we have begun trialling a new system where we insert rubber tubes to continuously irrigate the open wounds with a sterilised sodium hypochlorite salt solution. When kept up every few hours, it works wonders at keeping the flesh clean."
    },
    "source_b": {
      "provenance": "Source B: An official British Army photograph showing a casualty undergoing treatment at a Base Hospital in Boulogne, 1917.",
      "content": "The photograph shows a wounded soldier lying in a clean hospital ward, with a complex apparatus suspended above his bed. Several thin rubber tubes run from glass bottles of antiseptic liquid directly into a deep wound in his leg. This is the Carrel-Dakin irrigation method in active use. A nursing sister is adjusting the flow valves on the tubes, which flush the wound at regular intervals. In the background, a portable, mobile X-ray machine is positioned next to another bed, with a technician adjusting the electrical cables linked to a generator outside."
    },
    "q8": {
      "question": "2 (a). How useful are Sources A and B for an enquiry into new medical techniques used to deal with infections and injuries on the Western Front? Explain your answer, using Sources A and B and your knowledge of the historical context. (8 marks)",
      "model": "Model Answer: Source A is highly useful for investigating new medical techniques developed to combat battlefield infections. In terms of content, the source details two major clinical innovations: 'excision' (debridement), which involved cutting away dead, infected tissue and dirty clothing, and the trialling of continuous wound irrigation using a sterilized sodium hypochlorite salt solution (the Carrel-Dakin method) because standard carbolic antiseptics were useless. This is supported by historical context; we know that the soil of France and Belgium was heavily manured, meaning wounds were instantly contaminated with anaerobic bacteria causing gas gangrene. Traditional aseptic surgery was impossible near the front, and antiseptics did not work inside deep wounds, forcing doctors to develop debridement to remove infected flesh quickly, and the Carrel-Dakin method to sterilize deep wounds. The provenance of Source A is useful because it is a personal journal from an RAMC surgeon at a Casualty Clearing Station (CCS) during the Battle of the Somme in August 1916. This provides an expert, first-hand, and contemporary record of how forward surgeons experimented with new techniques to handle the overwhelming casualty rates and infection crises of a major offensive.\\n\\nSource B is also highly useful for this enquiry. Its content provides clear visual evidence of the physical administration of these new techniques in a clinical ward. It shows the Carrel-Dakin apparatus in active use, with rubber tubes running from glass bottles into a patient's leg wound, and displays a portable mobile X-ray unit being adjusted by a technician. This is supported by historical context, as we know that the Carrel-Dakin method was highly effective but required a complex setup of continuous flushing every few hours, which was very labor-intensive for nursing staff. Furthermore, mobile X-ray units housed in vans were a crucial development on the Western Front, as they could be driven close to the front line to help surgeons locate shrapnel and bullet fragments in wounds, allowing them to excise the tissue before gas gangrene set in. The provenance of Source B makes it highly useful as it is an official British Army photograph from 1917. While official photos were sometimes staged or carefully composed for propaganda or record-keeping purposes, it provides a highly reliable, detailed, and accurate visual record of how standardized and advanced these antiseptic and diagnostic technologies had become in Base Hospitals by 1917."
    },
    "q4": {
      "question": "2 (b). How could you follow up Source A to find out more about new medical techniques used to deal with infections and injuries on the Western Front? In your answer, you must give the question you would ask and the type of source you could use. (4 marks)",
      "model": "Model Answer:\\n* Detail in Source A that I would follow up: 'we have begun trialling a new system where we insert rubber tubes to continuously irrigate the open wounds with a sterilised sodium hypochlorite salt solution.'\\n* Question I would ask: What were the main practical difficulties nurses and medical staff faced when preparing and administering the Carrel-Dakin chemical solution during times of heavy casualties?\\n* What type of source I could use: Personal diaries or memoirs of nurses (such as VADs or volunteer nurses) who served at Base Hospitals or CCSs on the Western Front in 1917.\\n* How this might help answer my question: These personal accounts would explain the daily logistical challenges of preparing and administering the Carrel-Dakin solution (which could only be kept fresh for six hours and had to be run every few hours) when dealing with an overwhelming number of patients."
    }
  }
];

const dataPath = path.join(__dirname, '../edexcel_medicine/data.js');
let dataContent = fs.readFileSync(dataPath, 'utf8');

const jsonContent = dataContent.replace('export const unitData = ', '').trim().replace(/;$/, '');
let unitData = JSON.parse(jsonContent);

let index = 0;
unitData.lessons.forEach(lesson => {
    if (lesson.id && lesson.id.startsWith('lesson_5_') && index < 5) {
        const generatedData = newSources[index];
        
        lesson.gcse_task = {
            topic: generatedData.enquiry,
            sources: [
                {
                    type: "text",
                    title: generatedData.source_a.provenance,
                    text: generatedData.source_a.content
                },
                {
                    type: "text",
                    title: generatedData.source_b.provenance,
                    text: generatedData.source_b.content
                }
            ],
            question: generatedData.q8.question,
            model: generatedData.q8.model,
            follow_up: {
                question: generatedData.q4.question,
                model: generatedData.q4.model
            }
        };
        
        index++;
    }
});

const jsContent = `export const unitData = ${JSON.stringify(unitData, null, 2)};\n`;
fs.writeFileSync(dataPath, jsContent);
console.log("Successfully injected all 5 source pairs and questions into edexcel_medicine data.js!");
