const fs = require('fs');
const path = require('path');

const dataPath = path.resolve(__dirname, '../edexcel_medicine/data.js');
let fileContent = fs.readFileSync(dataPath, 'utf8');

const essays = {
  "lesson_1_1": `**To a very large extent, I agree that the Theory of the Four Humours was the main idea about the cause of disease in medieval England (c1250–c1500).** While other unscientific explanations—such as divine punishment and miasma—co-existed and were widely believed, the Four Humours served as the primary, universally accepted "rational" framework through which medical practitioners and educated society understood, diagnosed, and physically treated sickness. 

The primary reason for the absolute dominance of this theory was its endorsement by the ancient Roman physician Claudius **Galen**, whose extensive writings built directly upon the earlier work of Hippocrates. Galen argued that the human body contained four core liquids: **blood, phlegm, yellow bile, and black bile**, which corresponded directly to the seasons, elements, and physical qualities (hot, cold, wet, dry). Sickness was explained as a natural imbalance of these fluids—for instance, a cold was viewed as an excess of cold, wet phlegm in winter. Galen also introduced the **Theory of Opposites**, which taught that a humoural imbalance should be treated with its opposite quality. This practical, logical framework was highly convincing to medieval people because it matched daily bodily observations—such as sneezing excess phlegm during a cold or sweating out a hot fever.

Furthermore, the theory was maintained as the unchallenged medical standard because **the Church** controlled medieval education, universities, and the copying of medical manuscripts. Because Galen’s anatomical writings argued that the human body was so incredibly complex and purposeful that it must have been designed by a single "Creator," his ideas aligned perfectly with Christian creation theology. **Consequently**, the Church strictly promoted Galen's books as absolute truth and made them the sole basis of medical training for physicians. The Church also banned human dissection and actively discouraged any independent scientific research or questioning of classical texts, viewing intellectual deviation as a sin. This institutional monopoly ensured that generations of physicians graduated from universities like Oxford and Cambridge after seven to ten years of study without ever challenging the humoural model.

However, the Theory of the Four Humours was not the sole explanation for illness at this time, as medieval society also deeply believed in **supernatural causes and the theory of miasma**. The Church itself taught that disease was sent directly by God as a punishment for human sin or to test a person's faith, as seen in the societal view of leprosy as a physical mark of sin. This belief led people to seek spiritual preventions and treatments, such as prayer, fasting, pilgrimages to holy shrines, and buying indulgences. Additionally, people blamed astrology, utilizing **Almanacs** (star charts) to determine how the alignment of planets like Mars and Saturn caused outbreaks like the Black Death in 1348. People also believed in **miasma**—the unscientific idea that bad, foul-smelling air rising from rotting organic matter or swamps corrupted the body's humours. 

**In conclusion, I agree to a very large extent that the Four Humours was the main idea about the cause of disease.** While religious and astrological beliefs were incredibly popular, they were rarely viewed as contradictory to humoural theory. Instead, medieval people seamlessly integrated these concepts: they believed that God used the movement of the planets to create a corrupted miasma, which, once inhaled, physically upset the internal balance of the patient's humours. Because the Four Humours sat at the center of this integrated medical worldview and dictated almost all physical treatments (such as bloodletting and purging), it was undoubtedly the dominant medical idea of the Middle Ages.`,
  
  "lesson_1_2": `**I disagree with the statement that the physician was the most important provider of care and treatment in the years c1250–c1500, as physicians were a highly exclusive, expensive luxury whose practical treatments were often ineffective and entirely inaccessible to the vast majority of the population.** Instead, care was overwhelmingly decentralized, with female family members and traditional community healers serving as the true backbone of medieval healthcare.

It is true that for the wealthy elite and royalty, the university-trained physician was regarded as the most prestigious and important medical professional. To qualify, a physician had to undergo a highly rigorous and lengthy academic **medical training** program lasting between seven and ten years at a university. This education was entirely book-based, requiring students to read and memorize Latin translations of ancient Greek and Roman texts by Hippocrates and Galen, rather than gaining practical clinical experience. During diagnosis, physicians rarely touched the patient; instead, they analyzed astrology charts (using an Almanac) to check planetary alignments and examined urine samples for color, thickness, and smell to check humoural balance. They then wrote a diagnostic brief and directed other, lower-status practitioners—such as surgeons or apothecaries—to carry out physical treatments like bloodletting.

However, for the ordinary peasant or townsperson, the physician was completely irrelevant. Because university training was so lengthy and expensive, there were very few qualified physicians in England, and their high fees meant only the rich could afford their services. Instead, the most important source of daily care and treatment for the general population was provided by female family members using traditional **herbal remedies** in the home. Women, such as mothers and wives, had a vast, practical knowledge of local plants, herbs, and home remedies passed down through generations. They prepared mixtures containing active natural ingredients—like garlic, onions, honey, and wine—which modern scientists have proven possessed genuine antibacterial properties that actively killed pathogens and promoted wound healing. 

Furthermore, other practically trained, highly accessible healers played a far more significant role in the daily treatment of the sick than physicians. **Apothecaries** mixed and sold herbal medicines, spices, and simple chemical compounds. Because they did not attend university, they were far cheaper than physicians, serving as the "pharmacists" most peasants directly consulted for minor ailments. For physical treatments, ordinary citizens relied on **barber-surgeons**. Barber-surgeons were trained through practical apprenticeships rather than books, using sharp tools to perform haircuts alongside minor surgical procedures like lancing boils, pulling teeth, and carrying out bloodletting (phlebotomy). Additionally, the Church operated around **1,100 charity hospitals** by 1500. Run by monks and nuns, these hospitals did not provide medical cures, but they were highly important centers of spiritual care, rest, and hot meals for the poor and elderly.

**In conclusion, I disagree with the statement that the physician was the most important provider of care and treatment.** While physicians held the highest professional status and possessed the most prestigious academic **medical training**, their practical impact was limited to the wealthy. For the other 95% of medieval society, the real work of medicine was carried out at a grassroots level by local apothecaries, barber-surgeons, and, above to all, women in the home, whose use of **herbal remedies** provided the only accessible and biologically effective treatments of the era.`,
  
  "lesson_1_3": `**To a moderate extent, I agree that medical care and treatment was ineffective because it was based on Claudius Galen’s incorrect theoretical ideas.** Basing treatments on Galen's flawed understanding of anatomy and physiology did lead directly to useless and dangerous clinical practices. However, Galen’s authority was merely a symptom of a much larger structural cause: the absolute control of the Church over education, which actively prevented scientific **dissection** and exploration, combined with a total lack of diagnostic technology.

On the one hand, medical care was heavily undermined because physicians based their treatments on Galen's unscientific Theory of the Four Humours and the Theory of Opposites. Because Galen lacked correct knowledge of human anatomy, his books contained major anatomical errors—such as claiming that the liver produced blood, that blood flowed through invisible holes in the cardiac septum, and that the human lower jaw consisted of two separate bones. **Consequently**, when physicians attempted to treat illnesses, they targeted incorrect humoural causes. This led directly to the near-universal practice of **bloodletting** (phlebotomy via cutting a vein, applying leeches, or cupping) and purging. Rather than helping, draining blood from critically ill, infected, or elderly patients severely weakened their immune systems and often directly accelerated their deaths, proving that relying on Galen made clinical medicine highly dangerous.

On the other hand, the primary reason why these flawed ideas remained dominant was because **the Church** used its immense power to freeze medical knowledge and outlaw anatomical investigation. Because Galen’s writings referred to a single design by a "Creator," his books aligned perfectly with Christian creation theology, leading the Church to declare his texts infallible. The Church strictly controlled the universities and libraries, ensuring only Galen’s works were copied and taught. To protect this dogma, the Church actively banned human **dissection** for scientific research, believing that the physical body had to be buried whole to allow the soul to go to heaven. In rare academic demonstrations, the body was dissected by an untrained assistant while the university professor sat far away, reading Galen’s words aloud strictly to prove the book was correct. If an anatomical detail on the table contradicted the text, the professor would claim the body itself was deformed rather than questioning Galen, completely blocking any progress.

Furthermore, medical care was ineffective due to **external societal and technological factors** that had nothing to do with Galen. Even if physicians had abandoned Galen, they lacked the fundamental scientific tools required to understand disease. In an era before the invention of powerful microscopes, it was physically impossible to see microscopic bacteria or prove that pathogens caused infections. This lack of technology left medieval people with no alternative but to rely on other unscientific, un-Galenic ideas, such as believing that God sent epidemics as a punishment for sin, that planetary alignments caused the Black Death, or that bad air (miasma) bred sickness. These beliefs led to equally ineffective non-Galenic treatments, such as public self-flagellation, praying, fasting, carrying lucky charms, or burning sweet herbs on street corners to purify the air.

**In conclusion, I only agree to a moderate extent that Galen was the main cause of ineffective medical care.** While it is true that humoural treatments like **bloodletting** were biologically useless and clinically harmful, Galen's ideas did not survive on their own merit. The true root cause of medical stagnation was the institutional authority of the Church, which used its control over libraries and education to ban **dissection** and prosecute free-thinkers. Without the freedom to experiment, and lacking the microscope technology required to discover microbes, medieval medical care was structurally doomed to remain ineffective.`,
  
  "lesson_2_3": `**To a very large extent, I agree that quarantine was the most effective method used to prevent the spread of the Great Plague in London in 1665.** In an era before the development of Germ Theory, when the biological cause of the plague (the *Yersinia pestis* bacteria carried by fleas on rats) was entirely unknown, physically separating the sick from the healthy was the only genuine, practical way to reduce the rate of transmission. However, its effectiveness was severely limited by unscientific **miasma-based preventions** and the administrative limits of seventeenth-century enforcement.

On the one hand, quarantine represented a highly progressive, organized municipal response that actively saved lives by isolating active pathogens. Under a strict royal decree issued by King Charles II, local aldermen and the Mayor of London took direct administrative responsibility for containment. When a member of a household caught the plague, the entire family was subjected to a compulsory **28-day quarantine** inside their home. To enforce this, the city hired specialized **watchmen** who stood guard outside the boarded-up doors of infected houses to prevent anyone from entering or leaving. The front door was painted with a red cross and the words "Lord have mercy on us" to warn the public. By keeping infected individuals off the streets, quarantine successfully broke the chain of airborne pneumonic transmission, protecting the wider public from immediate contagion.

On the other hand, the overall effectiveness of quarantine was heavily undermined by the continued dominance of **the miasma theory** (bad air), which led authorities to waste resources on useless preventative measures. Because people still believed that the plague was caused by inhaling corrupted, foul-smelling air, they focused on purifying the atmosphere rather than tackling the fleas and rats that actually spread the disease. Londoners burned massive barrels of pitch and tar on street corners to keep the bad air away, and carried "posies" of sweet-smelling herbs. This miasma belief was even integrated into the design of specialized **plague doctors**, who wore leather outfits and bird-shaped masks filled with sweet-smelling herbs like camphor and dried flowers. While these measures kept doctors from smelling rotting filth, they did nothing to stop fleas from biting them, making miasmic prevention completely ineffective.

Furthermore, other preventative actions taken by the government and individuals were highly contradictory, with some actually worsening the epidemic. For example, believing that domestic animals carried the corrupt miasma in their fur, the Mayor of London ordered the systematic slaughter of over **40,000 dogs and 200,000 cats**. This was a catastrophic mistake; by killing the natural predators of rats, the rat population exploded, which rapidly increased the number of plague-carrying fleas in the city’s overcrowded slums. For individuals, the most effective prevention was simply **escaping the city**. Rich merchants, lawyers, and King Charles II immediately fled London for less populated rural areas. However, while this saved the wealthy, it was inaccessible to the poor and often carried the plague directly into rural villages.

**In conclusion, I agree to a very large extent that quarantine was the most effective prevention method.** While escaping the city was highly effective for individuals, as a public health strategy, quarantine was the only measure that actively disrupted the spread of disease within London. Although the unscientific belief in **the miasma theory** led to useless actions like burning tar and slaughtering cats, and although families locked inside by **watchmen** often caught the disease and died together, the physical containment of the sick remains the most rational and biologically successful preventative measure of the pre-modern era.`,
  
  "lesson_3_1": `**I agree to a very large extent that Louis Pasteur’s publication of Germ Theory in 1861 was the most significant turning point in the history of medicine.** Prior to 1861, medical science was entirely blocked by unscientific, unproven beliefs such as spontaneous generation and miasma. By proving that microscopic pathogens are the active cause of decay and disease, Pasteur provided the essential scientific foundation that transformed medicine from medieval guesswork into a rigorous, evidence-based science, directly enabling subsequent breakthroughs in surgery, public health, and immunology.

Before Pasteur’s discovery, the prevailing scientific consensus was the unscientific theory of **spontaneous generation**. This theory argued that microscopic organisms (microbes) naturally generated *from* decaying organic matter—meaning scientists viewed bacteria as a harmless symptom of decay rather than its cause. Utilizing elegant **swan-neck flask experiments**, Pasteur proved that sterile liquids remained completely fresh unless exposed to airborne microbes. By demonstrating that living microbes exist first in the air and are the active cause of decomposition and human illness, Pasteur permanently shattered spontaneous generation. This was a monumental turning point; for the first time in human history, medical science had a correct, proven explanation for what physically caused infections.

However, Pasteur’s theoretical work would have had limited clinical utility without the subsequent breakthroughs of the German bacteriologist **Robert Koch**. While Pasteur established the general theory, Koch developed the precise scientific methodology required to isolate and identify specific pathogens. Koch used agar jelly to grow pure cultures of bacteria and applied industrial dyes to stain transparent microbes, making them visible under microscopes. Using these methods, Koch successfully isolated the specific bacteria responsible for anthrax, tuberculosis (1882), and cholera (1883). Koch's work turned Pasteur's general theory into a practical tool, allowing scientists to hunt down specific "microbe killers" and develop targeted vaccinations against individual killer diseases.

Furthermore, other pre-existing or non-germ-based discoveries were highly significant, but they lacked the universal explanatory power of Germ Theory. For example, in 1796, **Edward Jenner** developed the smallpox vaccination by observing that milkmaids who caught cowpox were immune to smallpox. However, because Jenner had no knowledge of germs, his discovery was a "one-off" breakthrough that he could not scientifically explain or adapt to prevent other diseases. It was only after Pasteur published Germ Theory that Jenner's work was validated, allowing twentieth-century scientists to deliberately engineer vaccines for polio, diphtheria, and measles. Similarly, **John Snow’s 1854 mapping of the Broad Street pump** proved that cholera was transmitted through dirty water, but the government ignored his findings for years because he lacked the biological proof that only Germ Theory and Koch’s subsequent isolation of the cholera bacillus could provide.

**In conclusion, I agree to a very large extent that Germ Theory was the biggest turning point.** While **Robert Koch’s** systematic research was essential for turning the theory into practical clinical treatments, and while Edward Jenner saved millions through smallpox vaccinations, Koch and all subsequent immunologists were entirely dependent on Pasteur's initial theoretical breakthrough. By permanently disproving **spontaneous generation**, Germ Theory united all aspects of medicine—from hospital design and public sanitation to antiseptic surgery and pharmaceuticals—under a single, correct scientific paradigm, representing the ultimate foundation of modern medicine.`,
  
  "lesson_3_2": `**I agree to a very large extent that Joseph Lister's development of carbolic acid in 1865 was the most significant turning point in surgery in the period c1700–c1900.** While James Simpson's discovery of chloroform solved the barrier of physical pain, it actually caused mortality rates to rise by triggering a "Black Period" in surgery. By using carbolic acid to systematically target and defeat post-operative infection—which had historically been the leading cause of death after surgery—Lister physically proved the validity of Germ Theory in clinical practice and laid the direct foundations for the transition to modern, sterile aseptic surgery.

Before Lister's breakthrough, the introduction of chemical anaesthetics like **James Simpson’s chloroform (1847)** had revolutionized the surgical experience by putting patients completely to sleep, eliminating the horror of conscious pain. However, this led directly to the **"Black Period" of surgery (1847–1870)**. Because patients were unconscious, surgeons became overly ambitious, performing much longer, deeper, and more complex internal operations. However, because they still wore dirty, pus-stained clothes, did not wash their hands, and used unsterilized tools, they carried deadly bacteria deep into open wounds, causing a massive surge in fatal post-operative infections like gas gangrene and sepsis. Chloroform solved pain, but it made surgery more lethal.

This crisis was resolved in 1865 when **Joseph Lister** read Louis Pasteur’s 1861 Germ Theory. Lister realized that the rotting of surgical wounds was caused by invisible, living microbes in the air. **Consequently**, Lister developed an aggressive antiseptic regime, utilizing **carbolic acid** to spray the operating theater air, wash his hands and surgical instruments, and soak patient bandages. The impact was immediate and dramatic: mortality rates in Lister’s surgical wards plummeted from **46% to 15%**. For the first time in history, surgeons could operate without a high risk of killing the patient through infection. This was the true turning point; once infection was controlled, surgery transformed from a terrifying, fatal last resort into a safe, curative medical science.

Furthermore, Lister's carbolic acid spray was the direct catalyst for the transition to **aseptic surgery** by 1900. Carbolic acid was highly corrosive, irritating surgeons' skin and damaging patients' lungs. Spurred by Lister's proof that microbes must be kept out of wounds, surgeons developed entirely sterile aseptic techniques. By 1900, rather than spraying chemicals to kill germs during surgery, hospital staff focused on preventing germs from entering the theater in the first place: all surgical instruments were **steam-sterilized** in autoclaves, the theater air was filtered, and surgeons began washing their hands, wearing sterile gowns, face masks, and **rubber gloves**.

**In conclusion, I agree to a very large extent that carbolic acid was the most significant turning point.** While **James Simpson’s** chloroform was a brilliant breakthrough that solved surgical pain, it was clinically counterproductive until the problem of infection was solved. By using **carbolic acid** to apply Pasteur's Germ Theory directly to the human body, **Joseph Lister** conquered post-operative infection, saving millions of lives and providing the essential scientific stepping stone to the sterile, aseptic surgical practices used to this day.`,
  
  "lesson_4_1": `**To a very large extent, I agree that the discovery of the structure of DNA was the most significant breakthrough in understanding the causes of illness in the modern period.** For centuries, medical understanding was restricted to external pathogens or physical trauma. By decoding the human genetic blueprint, the discovery of DNA unlocked a completely new genetic paradigm of medicine, allowing doctors to explain, predict, and target non-communicable, hereditary illnesses. While the identification of lifestyle factors has had a massive practical impact on public health legislation, DNA represents the ultimate scientific frontier of modern medical science.

On the one hand, the mapping of DNA fundamentally transformed medical understanding by proving that many chronic diseases are caused by internal, inherited genetic instructions. In 1953, James **Watson and Crick** successfully mapped the double-helix structure of DNA, relying heavily on the uncredited X-ray crystallography photographs produced by Rosalind Franklin. This molecular breakthrough allowed scientists to look inside the human cell and was scaled up globally through the **Human Genome Project** (launched in 1990 and completed in 2003). By mapping all three billion chemical base pairs, scientists identified the specific mutated or faulty genes responsible for hereditary illnesses like cystic fibrosis, Down's syndrome, and haemophilia. Today, this allows for predictive genetic testing—for instance, individuals can screen for mutated BRCA1/2 genes to assess their hereditary risk of developing breast cancer long before any physical symptoms manifest.

On the other hand, it can be argued that the identification of **lifestyle factors** has been a more significant breakthrough for the health of the general population. While genetic disorders affect a minority, chronic lifestyle-related illnesses are the leading causes of death in modern Britain. Throughout the twentieth century, epidemiological research proved how personal choices regarding tobacco, diet, alcohol, and exercise cause disease. Most notably, a landmark **1950 study by the British Medical Research Council** provided indisputable statistical proof linking smoking directly to lung cancer. This understanding of "nurture" over "nature" led to highly effective government prevention legislation—including raising the legal tobacco buying age to 18, banning cigarette advertising, and implementing the compulsory **2007 ban on smoking in enclosed public workplaces**.

Furthermore, the clinical application of both genetic and lifestyle discoveries was entirely dependent on **advances in modern diagnostic technologies**. In 1900, diagnosis was still highly subjective, based on examining a patient’s physical symptoms. Throughout the twentieth century, this was revolutionized by high-tech diagnostic testing: **blood tests** (from the 1930s) allowed for the non-invasive screening of internal conditions; **X-rays** (from 1895) revealed internal structures; and **CT and MRI scans** constructed detailed, 3D images to locate deep brain tumors and lung cancers when they were the size of a pea. Paired with cellular **biopsies** and electrocardiograms (ECGs), these technologies allowed doctors to pinpoint physical and chemical causes of illness with unprecedented, scientific accuracy.

**In conclusion, I agree to a very large extent that the discovery of DNA was the most significant breakthrough.** While the identification of **lifestyle factors** led to immediate public health campaigns like **Change4Life** that saved millions of lives, and while modern diagnostic machines were essential for clinical testing, these developments represented the perfection of existing nineteenth-century observational science. In contrast, the discovery of DNA by **Watson and Crick** represented an entirely new scientific paradigm. By allowing doctors to actively read and eventually edit the human biological code, DNA permanently altered the future direction of global medicine, shifting the ultimate goal of science from treating symptoms to correcting our genetic blueprint.`,

  "lesson_4_2": `**I disagree with the statement that Alexander Fleming was the most important individual in the development of penicillin, as his contribution was limited to a "one-off" accidental laboratory discovery that he quickly abandoned.** While Fleming deserves credit for identifying the mould’s antibacterial properties, the true medical revolution was achieved by **Howard Florey and Ernst Chain**, whose systematic biochemical work turned penicillin into a stable, usable drug. Furthermore, even their work would have remained restricted to an Oxford laboratory without the wartime intervention of the US Government, which funded and organized the **mass production** of the drug.

On the one hand, Alexander Fleming was a highly important individual because his 1928 discovery provided the essential scientific starting point for the antibiotic age. Working as a bacteriologist at St Mary's Hospital, Fleming returned from a holiday in September 1928 to find that a mould spore (*Penicillium notatum*) had contaminated a petri dish left on his bench. He observed that the mould had completely destroyed the surrounding **staphylococcus** bacteria. Fleming experimented to show that the diluted mould killed harmful bacteria without damaging healthy human cells, and he published his findings in a British medical journal in 1929. This discovery was of critical significance because his published research served as the primary scientific blueprint when other scientists searched for antibiotic substances a decade later.

However, Fleming's significance is heavily limited because he failed to develop penicillin into a usable clinical drug, making **Howard Florey and Ernst Chain** far more important. Fleming struggled to extract and stabilize the active penicillin compound, and by 1931, he had abandoned his research, believing it was too unstable to be used as anything more than a minor surface antiseptic. In 1938–1939, Howard Florey (an Australian pathologist) and Ernst Chain (a German biochemist) revived Fleming’s research at Oxford University after reading his 1929 article. Chain successfully solved the chemical challenges, purifying the active compound and proving its life-saving effectiveness on mice in 1940 and on the first human patient, Albert Alexander, in 1941. Their systematic clinical work proved that penicillin was a highly effective, non-toxic antibiotic capable of destroying fatal blood infections inside the human bloodstream.

Furthermore, the development of penicillin was not driven solely by individuals, but was structurally dependent on the institutional intervention of the US Government and the urgent pressures of the **Second World War**. Despite Florey and Chain’s scientific success, British chemical companies were fully occupied with the wartime manufacturing effort and could not provide assistance. Consequently, in July 1941, Florey traveled to the USA to secure funding, arriving just as the American government realized the drug's immense military value for treating battlefield wounds and preventing fatal gas gangrene. The US Government intervened on an unprecedented scale, providing massive federal grants to Florey's team and funding American pharmaceutical companies to purchase expensive industrial equipment, including **giant deep-fermentation tanks**. This wartime mobilization enabled the **mass production** of penicillin, allowing the pharmaceutical industry to deliver over 2.3 million life-saving doses to treat Allied casualties on D-Day in 1944.

**In conclusion, I disagree with the statement that Alexander Fleming was the most important individual in the development of penicillin.** While Fleming’s accidental observation of the mould destroying **staphylococcus** was a brilliant starting point, his work was clinically useless to sick patients because he lacked the chemical capability to purify it. The true medical revolution was achieved by Howard Florey and Ernst Chain, who turned the theoretical discovery into a stable, usable drug. Ultimately, however, the transition of penicillin from an Oxford laboratory curiosity into a global, life-saving antibiotic industry was only made possible by the US Government’s wartime funding of **mass production** technology, proving that a combination of individuals and institutions was required to achieve this medical milestone.`
};

const startIndex = fileContent.indexOf('{');
const endIndex = fileContent.lastIndexOf('}');
const jsonStr = fileContent.substring(startIndex, endIndex + 1);

const data = eval('(' + jsonStr + ')');

for (const [lessonId, essayText] of Object.entries(essays)) {
  const lesson = data.lessons.find(l => l.id === lessonId);
  if (lesson && lesson.extended) {
    // Format text: convert **...** to <strong>...</strong> and \n\n to <br><br>
    let formattedHtml = essayText.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    formattedHtml = formattedHtml.split('\n\n').join('</p><p style="margin-bottom: 1.5rem;">');
    
    // Add prefix and suffix
    formattedHtml = `<strong>Grade 9 Model Answer (16 marks):</strong><br><br><p style="margin-bottom: 1.5rem;">${formattedHtml}</p>`;
    
    lesson.extended.model = formattedHtml;
  } else {
    console.log("Could not find lesson:", lessonId);
  }
}

const newJsonStr = JSON.stringify(data, null, 2);
const newContent = fileContent.substring(0, startIndex) + newJsonStr + fileContent.substring(endIndex + 1);

fs.writeFileSync(dataPath, newContent, 'utf8');
console.log('Successfully injected all 8 16-mark essays.');
