/**
 * Meoncross School Chess Club Data Registry
 * Configured for Period 6 Thursdays
 * School Houses: Warrior, Dreadnought, Victory, Invincible
 * Year Groups: Years 7–11 (KS3 & KS4)
 */

export const HOUSES = {
  victory: {
    id: 'victory',
    name: 'Victory',
    color: '#1d4ed8',
    colorDark: '#1e3a8a',
    bgLight: '#eff6ff',
    borderColor: '#bfdbfe',
    ship: 'HMS Victory (1765)',
    motto: 'England Expects',
    style: 'Tactical harmony & coordinated pieces',
    icon: 'fa-anchor',
  },
  warrior: {
    id: 'warrior',
    name: 'Warrior',
    color: '#059669',
    colorDark: '#065f46',
    bgLight: '#ecfdf5',
    borderColor: '#a7f3d0',
    ship: 'HMS Warrior (1860)',
    motto: 'Strength & Fortitude',
    style: 'Unbreakable pawn structures & fortress endgames',
    icon: 'fa-shield-halved',
  },
  dreadnought: {
    id: 'dreadnought',
    name: 'Dreadnought',
    color: '#dc2626',
    colorDark: '#991b1b',
    bgLight: '#fef2f2',
    borderColor: '#fecaca',
    ship: 'HMS Dreadnought (1906)',
    motto: 'Fear Nought',
    style: 'Bold attacks & rapid piece mobility',
    icon: 'fa-bolt',
  },
  invincible: {
    id: 'invincible',
    name: 'Invincible',
    color: '#d97706',
    colorDark: '#92400e',
    bgLight: '#fffbeb',
    borderColor: '#fde68a',
    ship: 'HMS Invincible (1907)',
    motto: 'Speed & Precision',
    style: 'Counter-attacking skirmishes & sharp tactics',
    icon: 'fa-chess-knight',
  },
};

export const SCORING_RULES = {
  WIN: 3,
  DRAW: 2,
  PARTICIPATION: 1, // Every player who completes a game earns points for their house!
  GAME_OF_WEEK_BONUS: 2,
};

export const INITIAL_PLAYERS = [
  {
    id: 'p1',
    name: 'Oliver T.',
    year: 9,
    house: 'victory',
    rating: 1240,
    games: 6,
    won: 5,
    drawn: 1,
    lost: 0,
    rank: 1,
  },
  {
    id: 'p2',
    name: 'Sophia R.',
    year: 8,
    house: 'warrior',
    rating: 1210,
    games: 6,
    won: 4,
    drawn: 2,
    lost: 0,
    rank: 2,
  },
  {
    id: 'p3',
    name: 'Ethan M.',
    year: 10,
    house: 'dreadnought',
    rating: 1195,
    games: 7,
    won: 4,
    drawn: 1,
    lost: 2,
    rank: 3,
  },
  {
    id: 'p4',
    name: 'Amelie P.',
    year: 7,
    house: 'invincible',
    rating: 1160,
    games: 5,
    won: 3,
    drawn: 1,
    lost: 1,
    rank: 4,
  },
  {
    id: 'p5',
    name: 'Lucas W.',
    year: 11,
    house: 'victory',
    rating: 1145,
    games: 6,
    won: 3,
    drawn: 2,
    lost: 1,
    rank: 5,
  },
  {
    id: 'p6',
    name: 'Harry C.',
    year: 8,
    house: 'warrior',
    rating: 1120,
    games: 5,
    won: 3,
    drawn: 0,
    lost: 2,
    rank: 6,
  },
  {
    id: 'p7',
    name: 'Mia D.',
    year: 9,
    house: 'dreadnought',
    rating: 1090,
    games: 6,
    won: 2,
    drawn: 2,
    lost: 2,
    rank: 7,
  },
  {
    id: 'p8',
    name: 'Archie B.',
    year: 7,
    house: 'invincible',
    rating: 1075,
    games: 5,
    won: 2,
    drawn: 1,
    lost: 2,
    rank: 8,
  },
  {
    id: 'p9',
    name: 'Freya L.',
    year: 10,
    house: 'warrior',
    rating: 1050,
    games: 4,
    won: 2,
    drawn: 0,
    lost: 2,
    rank: 9,
  },
  {
    id: 'p10',
    name: 'Noah K.',
    year: 8,
    house: 'victory',
    rating: 1030,
    games: 5,
    won: 1,
    drawn: 2,
    lost: 2,
    rank: 10,
  },
  {
    id: 'p11',
    name: 'Isla S.',
    year: 7,
    house: 'dreadnought',
    rating: 1010,
    games: 4,
    won: 1,
    drawn: 1,
    lost: 2,
    rank: 11,
  },
  {
    id: 'p12',
    name: 'Joshua V.',
    year: 9,
    house: 'invincible',
    rating: 990,
    games: 4,
    won: 1,
    drawn: 0,
    lost: 3,
    rank: 12,
  },
  {
    id: 'p13',
    name: 'Evie H.',
    year: 11,
    house: 'warrior',
    rating: 970,
    games: 3,
    won: 1,
    drawn: 0,
    lost: 2,
    rank: 13,
  },
  {
    id: 'p14',
    name: 'George N.',
    year: 7,
    house: 'victory',
    rating: 950,
    games: 4,
    won: 0,
    drawn: 2,
    lost: 2,
    rank: 14,
  },
  {
    id: 'p15',
    name: 'Daisy M.',
    year: 8,
    house: 'dreadnought',
    rating: 930,
    games: 3,
    won: 0,
    drawn: 1,
    lost: 2,
    rank: 15,
  },
  {
    id: 'p16',
    name: 'Arthur F.',
    year: 10,
    house: 'invincible',
    rating: 910,
    games: 3,
    won: 0,
    drawn: 1,
    lost: 2,
    rank: 16,
  },
];

export const INITIAL_MATCHES = [
  {
    id: 'm101',
    date: 'Thursday 15 Oct 2026',
    round: 'Period 6 Session 1',
    white: 'Oliver T.',
    black: 'Sophia R.',
    whiteHouse: 'victory',
    blackHouse: 'warrior',
    result: '1/2-1/2',
    opening: 'Italian Game (Giuoco Piano)',
    notes: 'Hard-fought 42-move rook endgame. Brilliant sportsmanship shown by both players.',
  },
  {
    id: 'm102',
    date: 'Thursday 15 Oct 2026',
    round: 'Period 6 Session 1',
    white: 'Ethan M.',
    black: 'Amelie P.',
    whiteHouse: 'dreadnought',
    blackHouse: 'invincible',
    result: '1-0',
    opening: 'Sicilian Defense',
    notes: 'Dreadnought kingside breakthrough on move 28.',
  },
  {
    id: 'm103',
    date: 'Thursday 15 Oct 2026',
    round: 'Period 6 Session 1',
    white: 'Harry C.',
    black: 'Lucas W.',
    whiteHouse: 'warrior',
    blackHouse: 'victory',
    result: '0-1',
    opening: "Queen's Gambit Declined",
    notes: 'Lucas capitalized on an open c-file to deliver back-rank checkmate.',
  },
  {
    id: 'm104',
    date: 'Thursday 15 Oct 2026',
    round: 'Period 6 Session 1',
    white: 'Archie B.',
    black: 'Mia D.',
    whiteHouse: 'invincible',
    blackHouse: 'dreadnought',
    result: '1-0',
    opening: 'Four Knights Game',
    notes: 'Pin on the f6 knight led to a decisive piece win for Invincible.',
  },
];

export const HISTORICAL_CHESS_SPOTLIGHTS = [
  {
    id: 'lewis_chessmen',
    title: 'The Isle of Lewis Chessmen (c. 1150–1200)',
    period: 'Medieval England & Scandinavia',
    badge: 'Medieval Artefact',
    icon: 'fa-chess-rook',
    excerpt:
      'Discovered buried on a Scottish beach in 1831, these carved walrus-ivory pieces show fierce Viking berserkers biting their shields and regal Norman-style bishops, proving how chess traveled along Viking trade routes to Britain.',
    didYouKnow:
      'The Lewis Warders (rooks) are depicted as wild Scandinavian warriors biting their shields in battle-frenzy!',
  },
  {
    id: 'franklin_morals',
    title: 'Benjamin Franklin: The Morals of Chess (1786)',
    period: 'The Enlightenment & American Revolution',
    badge: 'Enlightenment Philosophy',
    icon: 'fa-scroll',
    excerpt:
      'Franklin argued chess was the supreme discipline for statecraft and historical analysis, developing three vital life virtues: Foresight (looking into future consequences), Circumspection (surveying the whole battlefield), and Caution (avoiding reckless rashness).',
    didYouKnow:
      'Franklin often played chess late into the night against French diplomats in Paris while securing naval alliances for the American War of Independence.',
  },
  {
    id: 'cold_war_fischer',
    title: 'Cold War on 64 Squares: Fischer vs Spassky (1972)',
    period: 'Post-War Britain & The Cold War',
    badge: 'Superpower Rivalry',
    icon: 'fa-chess-king',
    excerpt:
      'During the height of the Cold War, the World Championship match in Reykjavik between American Bobby Fischer and Soviet champion Boris Spassky became a global ideological battle between East and West, watched by millions on television.',
    didYouKnow:
      'Soviet authorities considered world chess dominance proof of the intellectual superiority of their communist system, making Fischer’s win a massive geopolitical earthquake.',
  },
];
